/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/address/edit" |
  "/pages/address/list" |
  "/pages/address/select" |
  "/pages/cart/cart" |
  "/pages/category/category" |
  "/pages/course-group/detail" |
  "/pages/course-group/teams" |
  "/pages/distribution/entry" |
  "/pages/distribution/goods" |
  "/pages/distribution/index" |
  "/pages/distribution/poster" |
  "/pages/distribution/qrcode" |
  "/pages/invite/index" |
  "/pages/marketing/detail" |
  "/pages/me/me" |
  "/pages/me/points" |
  "/pages/order/create" |
  "/pages/order/detail" |
  "/pages/order/list" |
  "/pages/pay/result" |
  "/pages/preview/card" |
  "/pages/preview/product-detail" |
  "/pages/product/detail" |
  "/pages/product/list" |
  "/pages/upgrade/referral-code" |
  "/pages/upgrade/team" |
  "/pages-auth/login" |
  "/pages-auth/register" |
  "/pages-ai/generate/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: '/pages/index/index' | '/pages/category/category' | '/pages/cart/cart' | '/pages/me/me';
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module 'virtual:uni-pages' {
  export type LocationUrl = _LocationUrl;
}
