import { PrismaClient } from '@prisma/client';

import { BOOTSTRAP_FULL_PACKAGE_MENU_IDS } from '../utils/platform-full-package-menu-ids';
import { wipeSuperTenantPlatformDict } from '../utils/wipe-super-tenant-dict';
import { seedSysMenuAndRoleMenu } from './sys-menu-and-role-menu';

export async function runPlatformBootstrap(prisma: PrismaClient): Promise<void> {
  console.log('开始导入种子数据...');

  // sys_tenant_package
  await prisma.sysTenantPackage.createMany({
    data: [
      {
        packageId: 1,
        packageName: '全量套餐',
        menuIds: BOOTSTRAP_FULL_PACKAGE_MENU_IDS,
        menuCheckStrictly: true,
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: new Date('2025-12-23 18:33:08.141308'),
        remark: '全量套餐（种子第二步会按 sys_menu 再对齐 menuIds，避免漏菜单）',
      },
    ],
    skipDuplicates: true,
  });

  // sys_tenant
  await prisma.sysTenant.createMany({
    data: [
      {
        id: 1,
        tenantId: '000000',
        contactUserName: 'admin',
        contactPhone: '15888888888',
        companyName: '湖南科技有限公司',
        licenseNumber: null,
        address: null,
        intro: '系统默认总平台租户（湖南科技有限公司），不可删除',
        domain: null,
        packageId: 1,
        expireTime: null,
        accountCount: -1,
        storageQuota: 10240,
        storageUsed: 0,
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: new Date('2025-12-23 18:33:08.1474'),
        remark: '超级管理员租户',
        regionCode: null,
        isDirect: true,
      },
    ],
    skipDuplicates: true,
  });

  // sys_client
  await prisma.sysClient.createMany({
    data: [
      {
        id: 1,
        clientId: 'e5cd7e4891bf95d1d19206ce24a7b32e',
        clientKey: 'pc',
        clientSecret: 'pc123',
        grantTypeList: 'password,social',
        deviceType: 'pc',
        activeTimeout: 1800,
        timeout: 86400,
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: new Date('2025-12-23 18:33:08.150524'),
      },
      {
        id: 2,
        clientId: '428a8310a3c9c5eb0a7c4c9d4b3d0c37',
        clientKey: 'app',
        clientSecret: 'app123',
        grantTypeList: 'password,social',
        deviceType: 'app',
        activeTimeout: 1800,
        timeout: 86400,
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: new Date('2025-12-23 18:33:08.150524'),
      },
      {
        id: 3,
        clientId: 'b3f5a7c9d1e2f40816293a5b7c9d1e2f',
        clientKey: 'h5',
        clientSecret: 'h5123',
        grantTypeList: 'password,social',
        deviceType: 'h5',
        activeTimeout: 1800,
        timeout: 86400,
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: new Date('2025-12-23 18:33:08.150524'),
      },
    ],
    skipDuplicates: true,
  });

  const { dataRemoved, typeRemoved } = await wipeSuperTenantPlatformDict(prisma);
  if (dataRemoved > 0 || typeRemoved > 0) {
    console.log(`已清空租户 000000 平台字典（${typeRemoved} 个类型 / ${dataRemoved} 条字典项），重新写入种子...`);
  }

  // sys_dict_type
  await prisma.sysDictType.createMany({
    data: [
      {
        dictId: 1,
        tenantId: '000000',
        dictName: '用户性别',
        dictType: 'sys_user_sex',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '用户性别列表',
        delFlag: 'NORMAL',
      },
      {
        dictId: 2,
        tenantId: '000000',
        dictName: '菜单状态',
        dictType: 'sys_show_hide',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '菜单状态列表',
        delFlag: 'NORMAL',
      },
      {
        dictId: 3,
        tenantId: '000000',
        dictName: '系统开关',
        dictType: 'sys_normal_disable',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '系统开关列表',
        delFlag: 'NORMAL',
      },
      {
        dictId: 4,
        tenantId: '000000',
        dictName: '任务状态',
        dictType: 'sys_job_status',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '任务状态列表',
        delFlag: 'NORMAL',
      },
      {
        dictId: 5,
        tenantId: '000000',
        dictName: '任务分组',
        dictType: 'sys_job_group',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '任务分组列表',
        delFlag: 'NORMAL',
      },
      {
        dictId: 6,
        tenantId: '000000',
        dictName: '系统是否',
        dictType: 'sys_yes_no',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '系统是否列表',
        delFlag: 'NORMAL',
      },
      {
        dictId: 7,
        tenantId: '000000',
        dictName: '通知类型',
        dictType: 'sys_notice_type',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '通知类型列表',
        delFlag: 'NORMAL',
      },
      {
        dictId: 8,
        tenantId: '000000',
        dictName: '通知状态',
        dictType: 'sys_notice_status',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '通知状态列表',
        delFlag: 'NORMAL',
      },
      {
        dictId: 9,
        tenantId: '000000',
        dictName: '操作类型',
        dictType: 'sys_oper_type',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '操作类型列表',
        delFlag: 'NORMAL',
      },
      {
        dictId: 10,
        tenantId: '000000',
        dictName: '系统状态',
        dictType: 'sys_common_status',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '登录状态列表',
        delFlag: 'NORMAL',
      },
      {
        dictId: 11,
        tenantId: '000000',
        dictName: '授权类型',
        dictType: 'sys_grant_type',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: 'OAuth 客户端授权方式',
        delFlag: 'NORMAL',
      },
      {
        dictId: 12,
        tenantId: '000000',
        dictName: '设备类型',
        dictType: 'sys_device_type',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '客户端设备类型（含 H5）',
        delFlag: 'NORMAL',
      },
      {
        dictId: 13,
        tenantId: '000000',
        dictName: '营销场景类型',
        dictType: 'marketing_scene_type',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '营销场景类型（首页、商品详情、活动专区等）',
        delFlag: 'NORMAL',
      },
      {
        dictId: 14,
        tenantId: '000000',
        dictName: '营销模块类型',
        dictType: 'marketing_module_type',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '营销模块类型（横幅、商品列表、倒计时等）',
        delFlag: 'NORMAL',
      },
      {
        dictId: 15,
        tenantId: '000000',
        dictName: '门店订单状态',
        dictType: 'store_order_status',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与 Prisma OrderStatus 一致',
        delFlag: 'NORMAL',
      },
      {
        dictId: 16,
        tenantId: '000000',
        dictName: '门店订单类型',
        dictType: 'store_order_type',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与 Prisma OrderType 一致',
        delFlag: 'NORMAL',
      },
      {
        dictId: 17,
        tenantId: '000000',
        dictName: '门店商品类型',
        dictType: 'store_product_type',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与 Prisma ProductType 一致',
        delFlag: 'NORMAL',
      },
      {
        dictId: 18,
        tenantId: '000000',
        dictName: '门店商品上架状态',
        dictType: 'store_product_status',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与 Prisma PublishStatus 一致',
        delFlag: 'NORMAL',
      },
      {
        dictId: 19,
        tenantId: '000000',
        dictName: 'PMS 上架状态',
        dictType: 'pms_publish_status',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与 Prisma PublishStatus 一致',
        delFlag: 'NORMAL',
      },
      {
        dictId: 20,
        tenantId: '000000',
        dictName: '优惠券类型',
        dictType: 'marketing_coupon_type',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与 Prisma CouponType 一致',
        delFlag: 'NORMAL',
      },
      {
        dictId: 21,
        tenantId: '000000',
        dictName: '优惠券模板状态',
        dictType: 'marketing_coupon_status',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与 Prisma CouponStatus 一致',
        delFlag: 'NORMAL',
      },
      {
        dictId: 22,
        tenantId: '000000',
        dictName: '会员升级申请状态',
        dictType: 'member_upgrade_apply_status',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与 ums_upgrade_apply.status 一致',
        delFlag: 'NORMAL',
      },
      {
        dictId: 23,
        tenantId: '000000',
        dictName: '会员升级申请类型',
        dictType: 'member_upgrade_apply_type',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与 ums_upgrade_apply.apply_type 一致',
        delFlag: 'NORMAL',
      },
      {
        dictId: 24,
        tenantId: '000000',
        dictName: '门店佣金状态',
        dictType: 'store_commission_status',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与 Prisma CommissionStatus 一致',
        delFlag: 'NORMAL',
      },
      {
        dictId: 25,
        tenantId: '000000',
        dictName: '会员等级',
        dictType: 'member_level',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与 MemberLevel 数值一致（0/1/2）',
        delFlag: 'NORMAL',
      },
      {
        dictId: 26,
        tenantId: '000000',
        dictName: '门店商品审核状态',
        dictType: 'store_product_audit_status',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与 Prisma StoreProductAuditStatus 一致',
        delFlag: 'NORMAL',
      },
    ],
    skipDuplicates: true,
  });

  // sys_dict_data
  await prisma.sysDictData.createMany({
    data: [
      {
        dictCode: 1,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '男',
        dictValue: '0',
        dictType: 'sys_user_sex',
        cssClass: '',
        listClass: '',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '性别男',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 2,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '女',
        dictValue: '1',
        dictType: 'sys_user_sex',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '性别女',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 3,
        tenantId: '000000',
        dictSort: 3,
        dictLabel: '未知',
        dictValue: '2',
        dictType: 'sys_user_sex',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '性别未知',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 4,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '显示',
        dictValue: '0',
        dictType: 'sys_show_hide',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '显示菜单',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 5,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '隐藏',
        dictValue: '1',
        dictType: 'sys_show_hide',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '隐藏菜单',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 6,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '正常',
        dictValue: '0',
        dictType: 'sys_normal_disable',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '正常状态',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 7,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '停用',
        dictValue: '1',
        dictType: 'sys_normal_disable',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '停用状态',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 8,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '正常',
        dictValue: '0',
        dictType: 'sys_job_status',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '正常状态',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 9,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '暂停',
        dictValue: '1',
        dictType: 'sys_job_status',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '停用状态',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 10,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '默认',
        dictValue: 'DEFAULT',
        dictType: 'sys_job_group',
        cssClass: '',
        listClass: '',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '默认分组',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 11,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '系统',
        dictValue: 'SYSTEM',
        dictType: 'sys_job_group',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '系统分组',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 41,
        tenantId: '000000',
        dictSort: 3,
        dictLabel: '财务',
        dictValue: 'FINANCE',
        dictType: 'sys_job_group',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '财务任务分组',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 42,
        tenantId: '000000',
        dictSort: 4,
        dictLabel: '营销',
        dictValue: 'MARKETING',
        dictType: 'sys_job_group',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '营销任务分组',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 43,
        tenantId: '000000',
        dictSort: 5,
        dictLabel: '商城',
        dictValue: 'STORE',
        dictType: 'sys_job_group',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '商城任务分组',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 12,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '是',
        dictValue: 'Y',
        dictType: 'sys_yes_no',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '系统默认是',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 13,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '否',
        dictValue: 'N',
        dictType: 'sys_yes_no',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '系统默认否',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 14,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '通知',
        dictValue: '1',
        dictType: 'sys_notice_type',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '通知',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 15,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '公告',
        dictValue: '2',
        dictType: 'sys_notice_type',
        cssClass: '',
        listClass: 'success',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '公告',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 16,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '正常',
        dictValue: '0',
        dictType: 'sys_notice_status',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '正常状态',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 17,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '关闭',
        dictValue: '1',
        dictType: 'sys_notice_status',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '关闭状态',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 18,
        tenantId: '000000',
        dictSort: 99,
        dictLabel: '其他',
        dictValue: '0',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'info',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '其他操作',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 19,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '新增',
        dictValue: '1',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'info',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '新增操作',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 20,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '修改',
        dictValue: '2',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'info',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '修改操作',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 21,
        tenantId: '000000',
        dictSort: 3,
        dictLabel: '删除',
        dictValue: '3',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '删除操作',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 22,
        tenantId: '000000',
        dictSort: 4,
        dictLabel: '授权',
        dictValue: '4',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '授权操作',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 23,
        tenantId: '000000',
        dictSort: 5,
        dictLabel: '导出',
        dictValue: '5',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '导出操作',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 24,
        tenantId: '000000',
        dictSort: 6,
        dictLabel: '导入',
        dictValue: '6',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '导入操作',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 25,
        tenantId: '000000',
        dictSort: 7,
        dictLabel: '强退',
        dictValue: '7',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '强退操作',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 26,
        tenantId: '000000',
        dictSort: 8,
        dictLabel: '生成代码',
        dictValue: '8',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '生成操作',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 27,
        tenantId: '000000',
        dictSort: 9,
        dictLabel: '清空数据',
        dictValue: '9',
        dictType: 'sys_oper_type',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '清空操作',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 28,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '成功',
        dictValue: '0',
        dictType: 'sys_common_status',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '正常状态',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 29,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '失败',
        dictValue: '1',
        dictType: 'sys_common_status',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '停用状态',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 30,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '密码认证',
        dictValue: 'password',
        dictType: 'sys_grant_type',
        cssClass: '',
        listClass: '',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 31,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '短信认证',
        dictValue: 'sms',
        dictType: 'sys_grant_type',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 32,
        tenantId: '000000',
        dictSort: 3,
        dictLabel: '邮件认证',
        dictValue: 'email',
        dictType: 'sys_grant_type',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 33,
        tenantId: '000000',
        dictSort: 4,
        dictLabel: '小程序认证',
        dictValue: 'miniapp',
        dictType: 'sys_grant_type',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 34,
        tenantId: '000000',
        dictSort: 5,
        dictLabel: '三方登录认证',
        dictValue: 'social',
        dictType: 'sys_grant_type',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 35,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: 'PC',
        dictValue: 'pc',
        dictType: 'sys_device_type',
        cssClass: '',
        listClass: '',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 36,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '安卓',
        dictValue: 'android',
        dictType: 'sys_device_type',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 37,
        tenantId: '000000',
        dictSort: 3,
        dictLabel: 'iOS',
        dictValue: 'ios',
        dictType: 'sys_device_type',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 38,
        tenantId: '000000',
        dictSort: 4,
        dictLabel: '小程序',
        dictValue: 'miniapp',
        dictType: 'sys_device_type',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 39,
        tenantId: '000000',
        dictSort: 5,
        dictLabel: 'H5',
        dictValue: 'h5',
        dictType: 'sys_device_type',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '微信内网页等 H5 场景',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 40,
        tenantId: '000000',
        dictSort: 6,
        dictLabel: 'App',
        dictValue: 'app',
        dictType: 'sys_device_type',
        cssClass: '',
        listClass: '',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与种子 sys_client app 一致',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 13007,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '首页',
        dictValue: 'HOMEPAGE',
        dictType: 'marketing_scene_type',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 13008,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '商品详情',
        dictValue: 'PRODUCT_DETAIL',
        dictType: 'marketing_scene_type',
        cssClass: '',
        listClass: 'info',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 13009,
        tenantId: '000000',
        dictSort: 3,
        dictLabel: '活动专区',
        dictValue: 'ACTIVITY_ZONE',
        dictType: 'marketing_scene_type',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 44,
        tenantId: '000000',
        dictSort: 4,
        dictLabel: '搜索结果',
        dictValue: 'SEARCH_RESULT',
        dictType: 'marketing_scene_type',
        cssClass: '',
        listClass: 'default',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 13010,
        tenantId: '000000',
        dictSort: 5,
        dictLabel: '秒杀专区',
        dictValue: 'FLASH_ZONE',
        dictType: 'marketing_scene_type',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与湖南演示种子场景类型对齐',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 13011,
        tenantId: '000000',
        dictSort: 6,
        dictLabel: '新人专区',
        dictValue: 'NEWCOMER',
        dictType: 'marketing_scene_type',
        cssClass: '',
        listClass: 'info',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与湖南演示种子场景类型对齐',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 13012,
        tenantId: '000000',
        dictSort: 7,
        dictLabel: '课程/服务专区',
        dictValue: 'COURSE',
        dictType: 'marketing_scene_type',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与湖南演示种子场景类型对齐',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 13013,
        tenantId: '000000',
        dictSort: 8,
        dictLabel: '拼课推荐',
        dictValue: 'COURSE_GROUP_RECOMMEND',
        dictType: 'marketing_scene_type',
        cssClass: '',
        listClass: 'success',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与后台场景定义表单选项对齐',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 13014,
        tenantId: '000000',
        dictSort: 9,
        dictLabel: '分类场景',
        dictValue: 'CATEGORY',
        dictType: 'marketing_scene_type',
        cssClass: '',
        listClass: 'default',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与后台场景定义表单选项对齐',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 13015,
        tenantId: '000000',
        dictSort: 10,
        dictLabel: '严选专区',
        dictValue: 'FEATURED',
        dictType: 'marketing_scene_type',
        cssClass: '',
        listClass: 'success',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '与后台场景定义表单选项对齐',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 45,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '横幅',
        dictValue: 'BANNER',
        dictType: 'marketing_module_type',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 46,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '商品列表',
        dictValue: 'PRODUCT_LIST',
        dictType: 'marketing_module_type',
        cssClass: '',
        listClass: 'info',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 47,
        tenantId: '000000',
        dictSort: 3,
        dictLabel: '秒杀倒计时',
        dictValue: 'FLASH_SALE',
        dictType: 'marketing_module_type',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 48,
        tenantId: '000000',
        dictSort: 4,
        dictLabel: '推荐商品',
        dictValue: 'RECOMMENDATION',
        dictType: 'marketing_module_type',
        cssClass: '',
        listClass: 'success',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 49,
        tenantId: '000000',
        dictSort: 5,
        dictLabel: '优惠券入口',
        dictValue: 'COUPON_ENTRY',
        dictType: 'marketing_module_type',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 50,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '待支付',
        dictValue: 'PENDING_PAY',
        dictType: 'store_order_status',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 51,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '已支付',
        dictValue: 'PAID',
        dictType: 'store_order_status',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 52,
        tenantId: '000000',
        dictSort: 3,
        dictLabel: '已发货',
        dictValue: 'SHIPPED',
        dictType: 'store_order_status',
        cssClass: '',
        listClass: 'info',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 53,
        tenantId: '000000',
        dictSort: 4,
        dictLabel: '已完成',
        dictValue: 'COMPLETED',
        dictType: 'store_order_status',
        cssClass: '',
        listClass: 'success',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 54,
        tenantId: '000000',
        dictSort: 5,
        dictLabel: '已取消',
        dictValue: 'CANCELLED',
        dictType: 'store_order_status',
        cssClass: '',
        listClass: 'default',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 55,
        tenantId: '000000',
        dictSort: 6,
        dictLabel: '已退款',
        dictValue: 'REFUNDED',
        dictType: 'store_order_status',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 56,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '实物订单',
        dictValue: 'PRODUCT',
        dictType: 'store_order_type',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 57,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '服务订单',
        dictValue: 'SERVICE',
        dictType: 'store_order_type',
        cssClass: '',
        listClass: 'info',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 58,
        tenantId: '000000',
        dictSort: 3,
        dictLabel: '混合订单',
        dictValue: 'MIXED',
        dictType: 'store_order_type',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 59,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '实物商品',
        dictValue: 'REAL',
        dictType: 'store_product_type',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 60,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '服务商品',
        dictValue: 'SERVICE',
        dictType: 'store_product_type',
        cssClass: '',
        listClass: 'info',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 61,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '下架',
        dictValue: 'OFF_SHELF',
        dictType: 'store_product_status',
        cssClass: '',
        listClass: 'default',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 62,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '上架',
        dictValue: 'ON_SHELF',
        dictType: 'store_product_status',
        cssClass: '',
        listClass: 'success',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 63,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '下架',
        dictValue: 'OFF_SHELF',
        dictType: 'pms_publish_status',
        cssClass: '',
        listClass: 'default',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 64,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '上架',
        dictValue: 'ON_SHELF',
        dictType: 'pms_publish_status',
        cssClass: '',
        listClass: 'success',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 65,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '满减券',
        dictValue: 'DISCOUNT',
        dictType: 'marketing_coupon_type',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 66,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '折扣券',
        dictValue: 'PERCENTAGE',
        dictType: 'marketing_coupon_type',
        cssClass: '',
        listClass: 'info',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 67,
        tenantId: '000000',
        dictSort: 3,
        dictLabel: '兑换券',
        dictValue: 'EXCHANGE',
        dictType: 'marketing_coupon_type',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 68,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '启用',
        dictValue: 'ACTIVE',
        dictType: 'marketing_coupon_status',
        cssClass: '',
        listClass: 'success',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 69,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '停用',
        dictValue: 'INACTIVE',
        dictType: 'marketing_coupon_status',
        cssClass: '',
        listClass: 'default',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 70,
        tenantId: '000000',
        dictSort: 3,
        dictLabel: '已过期',
        dictValue: 'EXPIRED',
        dictType: 'marketing_coupon_status',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 71,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '待审核',
        dictValue: 'PENDING',
        dictType: 'member_upgrade_apply_status',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 72,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '已通过',
        dictValue: 'APPROVED',
        dictType: 'member_upgrade_apply_status',
        cssClass: '',
        listClass: 'success',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 73,
        tenantId: '000000',
        dictSort: 3,
        dictLabel: '已驳回',
        dictValue: 'REJECTED',
        dictType: 'member_upgrade_apply_status',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 74,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '商品购买',
        dictValue: 'PRODUCT_PURCHASE',
        dictType: 'member_upgrade_apply_type',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 75,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '推荐码',
        dictValue: 'REFERRAL_CODE',
        dictType: 'member_upgrade_apply_type',
        cssClass: '',
        listClass: 'info',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 76,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '冻结中',
        dictValue: 'FROZEN',
        dictType: 'store_commission_status',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 77,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '已结算',
        dictValue: 'SETTLED',
        dictType: 'store_commission_status',
        cssClass: '',
        listClass: 'success',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 78,
        tenantId: '000000',
        dictSort: 3,
        dictLabel: '已取消',
        dictValue: 'CANCELLED',
        dictType: 'store_commission_status',
        cssClass: '',
        listClass: 'default',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 79,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '普通会员',
        dictValue: '0',
        dictType: 'member_level',
        cssClass: '',
        listClass: 'default',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 80,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: 'C1团长',
        dictValue: '1',
        dictType: 'member_level',
        cssClass: '',
        listClass: 'primary',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 81,
        tenantId: '000000',
        dictSort: 3,
        dictLabel: 'C2股东',
        dictValue: '2',
        dictType: 'member_level',
        cssClass: '',
        listClass: 'success',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 82,
        tenantId: '000000',
        dictSort: 1,
        dictLabel: '草稿',
        dictValue: 'DRAFT',
        dictType: 'store_product_audit_status',
        cssClass: '',
        listClass: 'default',
        isDefault: 'Y',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 83,
        tenantId: '000000',
        dictSort: 2,
        dictLabel: '待审核',
        dictValue: 'PENDING',
        dictType: 'store_product_audit_status',
        cssClass: '',
        listClass: 'warning',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 84,
        tenantId: '000000',
        dictSort: 3,
        dictLabel: '已通过',
        dictValue: 'APPROVED',
        dictType: 'store_product_audit_status',
        cssClass: '',
        listClass: 'success',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        dictCode: 85,
        tenantId: '000000',
        dictSort: 4,
        dictLabel: '已驳回',
        dictValue: 'REJECTED',
        dictType: 'store_product_audit_status',
        cssClass: '',
        listClass: 'danger',
        isDefault: 'N',
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
    ],
    skipDuplicates: true,
  });

  // sys_config
  await prisma.sysConfig.createMany({
    data: [
      {
        configId: 1,
        tenantId: '000000',
        configName: '主框架页-默认皮肤样式名称',
        configKey: 'sys.index.skinName',
        configValue: 'skin-blue',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '蓝色 skin-blue、绿色 skin-green、紫色 skin-purple、红色 skin-red、黄色 skin-yellow',
        status: 'NORMAL',
        delFlag: 'NORMAL',
      },
      {
        configId: 2,
        tenantId: '000000',
        configName: '用户管理-账号初始密码',
        configKey: 'sys.user.initPassword',
        configValue: '123456',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '初始化密码 123456',
        status: 'NORMAL',
        delFlag: 'NORMAL',
      },
      {
        configId: 3,
        tenantId: '000000',
        configName: '主框架页-侧边栏主题',
        configKey: 'sys.index.sideTheme',
        configValue: 'theme-dark',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '深色主题theme-dark，浅色主题theme-light',
        status: 'NORMAL',
        delFlag: 'NORMAL',
      },
      {
        configId: 4,
        tenantId: '000000',
        configName: '账号自助-验证码开关',
        configKey: 'sys.account.captchaEnabled',
        configValue: 'false',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '是否开启验证码功能（true开启，false关闭）',
        status: 'NORMAL',
        delFlag: 'NORMAL',
      },
      {
        configId: 5,
        tenantId: '000000',
        configName: '账号自助-是否开启用户注册功能',
        configKey: 'sys.account.registerUser',
        configValue: 'false',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '是否开启注册用户功能（true开启，false关闭）',
        status: 'NORMAL',
        delFlag: 'NORMAL',
      },
      {
        configId: 6,
        tenantId: '000000',
        configName: '用户登录-黑名单列表',
        configKey: 'sys.login.blackIPList',
        configValue: '',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '设置登录IP黑名单限制，多个匹配项以;分隔，支持匹配（*通配、网段）',
        status: 'NORMAL',
        delFlag: 'NORMAL',
      },
      {
        configId: 7,
        tenantId: '000000',
        configName: '营销模块-平台费率',
        configKey: 'marketing.fee_rate',
        configValue: '0.01',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '营销实例成功后结算到门店钱包的平台费率，默认 1%',
        status: 'NORMAL',
        delFlag: 'NORMAL',
      },
      {
        configId: 8,
        tenantId: '000000',
        configName: 'OSS-文件管理列表是否加载预览资源',
        configKey: 'sys.oss.previewListResource',
        configValue: 'false',
        configType: 'N',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '管理端 OSS 列表是否请求预览资源（true 开启，false 关闭）',
        status: 'NORMAL',
        delFlag: 'NORMAL',
      },
      {
        configId: 9,
        tenantId: '000000',
        configName: 'C端营销场景接口总开关',
        configKey: 'marketing.client.scene.enabled',
        configValue: 'Y',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2026-04-15 10:00:00'),
        updateBy: '',
        updateTime: null,
        remark: 'Y 开启；N 关闭。可按租户覆盖。',
        status: 'NORMAL',
        delFlag: 'NORMAL',
      },
      {
        configId: 10,
        tenantId: '000000',
        configName: 'C端营销场景接口放量百分比',
        configKey: 'marketing.client.scene.rolloutPercent',
        configValue: '100',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2026-04-15 10:00:00'),
        updateBy: '',
        updateTime: null,
        remark: '0～100：按 memberId+tenantId 稳定哈希放量；100 全量。可按租户覆盖。',
        status: 'NORMAL',
        delFlag: 'NORMAL',
      },
      {
        configId: 11,
        tenantId: '000000',
        configName: 'C端营销聚合列表接口总开关',
        configKey: 'marketing.client.aggregate.enabled',
        configValue: 'Y',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2026-04-15 12:00:00'),
        updateBy: '',
        updateTime: null,
        remark: 'Y 开启；N 关闭。可按租户覆盖；连续 7 个 UTC 日零调用后由定时任务自动置 N。',
        status: 'NORMAL',
        delFlag: 'NORMAL',
      },
    ],
    skipDuplicates: true,
  });

  // sys_system_config
  await prisma.sysSystemConfig.createMany({
    data: [
      {
        configName: '营销模块-平台费率',
        configKey: 'marketing.fee_rate',
        configValue: '0.01',
        configType: 'Y',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '营销实例成功后结算到门店钱包的平台费率，默认 1%',
        status: 'NORMAL',
        delFlag: 'NORMAL',
      },
    ],
    skipDuplicates: true,
  });

  // sys_dept
  await prisma.sysDept.createMany({
    data: [
      {
        deptId: 100,
        tenantId: '000000',
        parentId: 0,
        ancestors: '0',
        deptName: '湖南科技有限公司',
        orderNum: 0,
        leader: '管理员',
        phone: '15888888888',
        email: 'demo@nestadmin.com',
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: null,
      },
      {
        deptId: 101,
        tenantId: '000000',
        parentId: 100,
        ancestors: '0,100',
        deptName: '深圳总公司',
        orderNum: 1,
        leader: 'nest-admin-soybean',
        phone: '15888888888',
        email: 'demo@nestadmin.com',
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: null,
      },
      {
        deptId: 102,
        tenantId: '000000',
        parentId: 100,
        ancestors: '0,100',
        deptName: '长沙分公司',
        orderNum: 2,
        leader: 'nest-admin-soybean',
        phone: '15888888888',
        email: 'demo@nestadmin.com',
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: null,
      },
      {
        deptId: 103,
        tenantId: '000000',
        parentId: 101,
        ancestors: '0,100,101',
        deptName: '研发部门',
        orderNum: 1,
        leader: 'nest-admin-soybean',
        phone: '15888888888',
        email: 'demo@nestadmin.com',
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: null,
      },
      {
        deptId: 104,
        tenantId: '000000',
        parentId: 101,
        ancestors: '0,100,101',
        deptName: '市场部门',
        orderNum: 2,
        leader: 'nest-admin-soybean',
        phone: '15888888888',
        email: 'demo@nestadmin.com',
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: null,
      },
      {
        deptId: 105,
        tenantId: '000000',
        parentId: 101,
        ancestors: '0,100,101',
        deptName: '测试部门',
        orderNum: 3,
        leader: 'nest-admin-soybean',
        phone: '15888888888',
        email: 'demo@nestadmin.com',
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: null,
      },
      {
        deptId: 106,
        tenantId: '000000',
        parentId: 101,
        ancestors: '0,100,101',
        deptName: '财务部门',
        orderNum: 4,
        leader: 'nest-admin-soybean',
        phone: '15888888888',
        email: 'demo@nestadmin.com',
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: null,
      },
      {
        deptId: 107,
        tenantId: '000000',
        parentId: 101,
        ancestors: '0,100,101',
        deptName: '运维部门',
        orderNum: 5,
        leader: 'nest-admin-soybean',
        phone: '15888888888',
        email: 'demo@nestadmin.com',
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: null,
      },
      {
        deptId: 108,
        tenantId: '000000',
        parentId: 102,
        ancestors: '0,100,102',
        deptName: '市场部门',
        orderNum: 1,
        leader: 'nest-admin-soybean',
        phone: '15888888888',
        email: 'demo@nestadmin.com',
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: null,
      },
      {
        deptId: 109,
        tenantId: '000000',
        parentId: 102,
        ancestors: '0,100,102',
        deptName: '财务部门',
        orderNum: 2,
        leader: 'nest-admin-soybean',
        phone: '15888888888',
        email: 'demo@nestadmin.com',
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: null,
      },
    ],
    skipDuplicates: true,
  });

  // sys_post
  await prisma.sysPost.createMany({
    data: [
      {
        postId: 1,
        tenantId: '000000',
        deptId: null,
        postCode: 'ceo',
        postCategory: null,
        postName: '董事长',
        postSort: 1,
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        postId: 2,
        tenantId: '000000',
        deptId: null,
        postCode: 'se',
        postCategory: null,
        postName: '项目经理',
        postSort: 2,
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        postId: 3,
        tenantId: '000000',
        deptId: null,
        postCode: 'hr',
        postCategory: null,
        postName: '人力资源',
        postSort: 3,
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
      {
        postId: 4,
        tenantId: '000000',
        deptId: null,
        postCode: 'user',
        postCategory: null,
        postName: '普通员工',
        postSort: 4,
        status: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '',
        delFlag: 'NORMAL',
      },
    ],
    skipDuplicates: true,
  });

  // sys_role
  await prisma.sysRole.createMany({
    data: [
      {
        roleId: 1,
        tenantId: '000000',
        roleName: '超级管理员',
        roleKey: 'admin',
        roleSort: 1,
        dataScope: '1',
        menuCheckStrictly: false,
        deptCheckStrictly: false,
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '超级管理员',
      },
      {
        roleId: 2,
        tenantId: '000000',
        roleName: '普通角色',
        roleKey: 'common',
        roleSort: 2,
        dataScope: '2',
        menuCheckStrictly: false,
        deptCheckStrictly: false,
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '普通角色',
      },
      {
        roleId: 3,
        tenantId: '000000',
        roleName: '演示角色',
        roleKey: 'demo',
        roleSort: 10,
        dataScope: '5',
        menuCheckStrictly: false,
        deptCheckStrictly: false,
        status: 'NORMAL',
        delFlag: 'NORMAL',
        createBy: 'admin',
        createTime: new Date('2025-02-28 08:52:10'),
        updateBy: '',
        updateTime: null,
        remark: '演示账户角色，仅拥有查看权限',
      },
    ],
    skipDuplicates: true,
  });

  await seedSysMenuAndRoleMenu(prisma);

  // sys_user_post
  await prisma.sysUserPost.createMany({
    data: [
      {
        userId: 1,
        postId: 1,
      },
      {
        userId: 2,
        postId: 2,
      },
      {
        userId: 3,
        postId: 1,
      },
    ],
    skipDuplicates: true,
  });

  // sys_user_role
  await prisma.sysUserRole.createMany({
    data: [
      {
        userId: 1,
        roleId: 1,
      },
      {
        userId: 2,
        roleId: 2,
      },
      {
        userId: 3,
        roleId: 3,
      },
    ],
    skipDuplicates: true,
  });
}
