import type { DictGovernanceRegistryItem } from './types';

export const DICT_GOVERNANCE_REGISTRY: DictGovernanceRegistryItem[] = [
  {
    domain: '系统管理',
    enumName: 'UserSexEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/admin/system/user',
    dictType: 'sys_user_sex',
    consumerSurfaces: ['admin-web'],
    migrationPriority: 'high',
  },
  {
    domain: '系统管理',
    enumName: 'ShowHideEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/admin/system/common',
    dictType: 'sys_show_hide',
    consumerSurfaces: ['admin-web'],
    migrationPriority: 'high',
  },
  {
    domain: '系统管理',
    enumName: 'NormalDisableEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/admin/system/common',
    dictType: 'sys_normal_disable',
    consumerSurfaces: ['admin-web'],
    migrationPriority: 'high',
  },
  {
    domain: '系统管理',
    enumName: 'JobStatusEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/admin/system/job',
    dictType: 'sys_job_status',
    consumerSurfaces: ['admin-web'],
    migrationPriority: 'high',
  },
  {
    domain: '系统管理',
    enumName: 'JobGroupEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/admin/system/job',
    dictType: 'sys_job_group',
    consumerSurfaces: ['admin-web'],
    migrationPriority: 'medium',
  },
  {
    domain: '系统管理',
    enumName: 'YesNoEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/admin/system/common',
    dictType: 'sys_yes_no',
    consumerSurfaces: ['admin-web', 'miniapp-client'],
    migrationPriority: 'medium',
  },
  {
    domain: '系统管理',
    enumName: 'NoticeTypeEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/admin/system/notice',
    dictType: 'sys_notice_type',
    consumerSurfaces: ['admin-web'],
    migrationPriority: 'high',
  },
  {
    domain: '系统管理',
    enumName: 'NoticeStatusEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/admin/system/notice',
    dictType: 'sys_notice_status',
    consumerSurfaces: ['admin-web'],
    migrationPriority: 'high',
  },
  {
    domain: '系统管理',
    enumName: 'OperateTypeEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/admin/system/log',
    dictType: 'sys_oper_type',
    consumerSurfaces: ['admin-web', 'export'],
    migrationPriority: 'medium',
  },
  {
    domain: '系统管理',
    enumName: 'CommonStatusEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/admin/system/common',
    dictType: 'sys_common_status',
    consumerSurfaces: ['admin-web'],
    migrationPriority: 'high',
  },
  {
    domain: '系统管理',
    enumName: 'GrantTypeEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/admin/system/oauth',
    dictType: 'sys_grant_type',
    consumerSurfaces: ['admin-web'],
    migrationPriority: 'low',
  },
  {
    domain: '系统管理',
    enumName: 'DeviceTypeEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/admin/system/device',
    dictType: 'sys_device_type',
    consumerSurfaces: ['admin-web', 'miniapp-client'],
    migrationPriority: 'low',
  },
  {
    domain: '订单',
    enumName: 'StoreOrderStatusEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/store/order',
    dictType: 'store_order_status',
    consumerSurfaces: ['admin-web', 'miniapp-client', 'export'],
    migrationPriority: 'high',
  },
  {
    domain: '订单',
    enumName: 'StoreOrderTypeEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/store/order',
    dictType: 'store_order_type',
    consumerSurfaces: ['admin-web', 'miniapp-client', 'export'],
    migrationPriority: 'high',
  },
  {
    domain: '商品',
    enumName: 'StoreProductTypeEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/store/product',
    dictType: 'store_product_type',
    consumerSurfaces: ['admin-web', 'miniapp-client'],
    migrationPriority: 'high',
  },
  {
    domain: '商品',
    enumName: 'StoreProductStatusEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/store/product',
    dictType: 'store_product_status',
    consumerSurfaces: ['admin-web', 'miniapp-client'],
    migrationPriority: 'high',
  },
  {
    domain: '商品',
    enumName: 'StoreProductAuditStatusEnum',
    sourceType: 'prisma',
    sourcePath: 'apps/backend/prisma/schema.prisma',
    dictType: 'store_product_audit_status',
    consumerSurfaces: ['admin-web', 'miniapp-client'],
    migrationPriority: 'high',
  },
  {
    domain: '商品',
    enumName: 'PmsPublishStatusEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/pms/product',
    dictType: 'pms_publish_status',
    consumerSurfaces: ['admin-web', 'miniapp-client', 'export'],
    migrationPriority: 'high',
  },
  {
    domain: '营销',
    enumName: 'MarketingCouponTypeEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/marketing/coupon',
    dictType: 'marketing_coupon_type',
    consumerSurfaces: ['admin-web', 'miniapp-client'],
    migrationPriority: 'high',
  },
  {
    domain: '营销',
    enumName: 'MarketingCouponStatusEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/marketing/coupon',
    dictType: 'marketing_coupon_status',
    consumerSurfaces: ['admin-web', 'miniapp-client'],
    migrationPriority: 'high',
  },
  {
    domain: '会员',
    enumName: 'MemberUpgradeApplyStatusEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/member/upgrade-apply',
    dictType: 'member_upgrade_apply_status',
    consumerSurfaces: ['admin-web', 'miniapp-client'],
    migrationPriority: 'high',
  },
  {
    domain: '会员',
    enumName: 'MemberUpgradeApplyTypeEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/member/upgrade-apply',
    dictType: 'member_upgrade_apply_type',
    consumerSurfaces: ['admin-web', 'miniapp-client'],
    migrationPriority: 'high',
  },
  {
    domain: '财务',
    enumName: 'CommissionStatus',
    sourceType: 'prisma',
    sourcePath: 'apps/backend/prisma/schema.prisma',
    dictType: 'store_commission_status',
    consumerSurfaces: ['admin-web'],
    migrationPriority: 'high',
  },
  {
    domain: '会员',
    enumName: 'MemberLevel',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/member',
    dictType: 'member_level',
    consumerSurfaces: ['admin-web', 'miniapp-client'],
    migrationPriority: 'high',
  },
  {
    domain: '营销',
    enumName: 'MarketingSceneTypeEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/marketing/scene',
    dictType: 'marketing_scene_type',
    consumerSurfaces: ['admin-web', 'miniapp-client'],
    migrationPriority: 'high',
  },
  {
    domain: '营销',
    enumName: 'MarketingModuleTypeEnum',
    sourceType: 'ts-enum',
    sourcePath: 'apps/backend/src/module/marketing/scene',
    dictType: 'marketing_module_type',
    consumerSurfaces: ['admin-web', 'miniapp-client'],
    migrationPriority: 'high',
  },
];
