import { MarketingEventType } from './marketing-event.types';

export type MarketingEventCategory = 'ORDER' | 'COUPON' | 'POINTS' | 'PLAY' | 'CONFIG';

export type MarketingEventUsableScope = 'POINTS' | 'COUPON' | 'TASK' | 'TOUCHPOINT' | 'RISK' | 'CACHE' | 'STAT' | 'AUDIT';

export type MarketingEventStatus = 'ACTIVE' | 'DRAFT' | 'DEPRECATED';

export type MarketingEventPrivacyLevel = 'LOW' | 'MEMBER' | 'ASSET';

export const MARKETING_EVENT_CATEGORIES = ['ORDER', 'COUPON', 'POINTS', 'PLAY', 'CONFIG'] as const;

export const MARKETING_EVENT_USABLE_SCOPES = [
  'POINTS',
  'COUPON',
  'TASK',
  'TOUCHPOINT',
  'RISK',
  'CACHE',
  'STAT',
  'AUDIT',
] as const;

export const MARKETING_EVENT_STATUSES = ['ACTIVE', 'DRAFT', 'DEPRECATED'] as const;

export const MARKETING_EVENT_PRIVACY_LEVELS = ['LOW', 'MEMBER', 'ASSET'] as const;

export interface MarketingEventCatalogItem {
  eventType: MarketingEventType;
  category: MarketingEventCategory;
  displayName: string;
  sourceModule: string;
  triggerTiming: string;
  idempotencyKey: string;
  orderingKey: string;
  tenantScoped: boolean;
  ruleTriggerable: boolean;
  replayable: boolean;
  usableScopes: readonly MarketingEventUsableScope[];
  consumers: readonly string[];
  privacyLevel: MarketingEventPrivacyLevel;
  payloadSchemaVersion: number;
  status: MarketingEventStatus;
}

/**
 * 营销事件目录是技术白名单：它定义事件事实和可用范围，不代表运营可以动态新增事件。
 * 资产、支付、退款、库存和排课等强一致动作仍由原业务服务直调完成，事件只承接衍生规则、触点、统计和审计。
 */
export const MARKETING_EVENT_CATALOG = {
  [MarketingEventType.INSTANCE_CREATED]: {
    eventType: MarketingEventType.INSTANCE_CREATED,
    category: 'PLAY',
    displayName: '玩法实例创建',
    sourceModule: 'marketing/instance',
    triggerTiming: '玩法实例创建成功后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event'],
    privacyLevel: 'MEMBER',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.INSTANCE_PAID]: {
    eventType: MarketingEventType.INSTANCE_PAID,
    category: 'PLAY',
    displayName: '玩法实例支付成功',
    sourceModule: 'marketing/instance',
    triggerTiming: '玩法实例支付状态确认后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'TOUCHPOINT', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event', 'touchpoint'],
    privacyLevel: 'ASSET',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.INSTANCE_SUCCESS]: {
    eventType: MarketingEventType.INSTANCE_SUCCESS,
    category: 'PLAY',
    displayName: '玩法实例成功',
    sourceModule: 'marketing/instance',
    triggerTiming: '玩法状态机确认成功后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['POINTS', 'COUPON', 'TASK', 'TOUCHPOINT', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event', 'touchpoint'],
    privacyLevel: 'ASSET',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.INSTANCE_FAILED]: {
    eventType: MarketingEventType.INSTANCE_FAILED,
    category: 'PLAY',
    displayName: '玩法实例失败',
    sourceModule: 'marketing/instance',
    triggerTiming: '玩法状态机确认失败后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'TOUCHPOINT', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event', 'touchpoint'],
    privacyLevel: 'MEMBER',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.INSTANCE_TIMEOUT]: {
    eventType: MarketingEventType.INSTANCE_TIMEOUT,
    category: 'PLAY',
    displayName: '玩法实例超时',
    sourceModule: 'marketing/instance',
    triggerTiming: '玩法超时任务或状态机确认超时后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'TOUCHPOINT', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event', 'touchpoint'],
    privacyLevel: 'MEMBER',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.INSTANCE_REFUNDED]: {
    eventType: MarketingEventType.INSTANCE_REFUNDED,
    category: 'PLAY',
    displayName: '玩法实例退款完成',
    sourceModule: 'marketing/instance',
    triggerTiming: '退款和玩法状态回滚完成后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'TOUCHPOINT', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event', 'touchpoint'],
    privacyLevel: 'ASSET',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.COUPON_CLAIMED]: {
    eventType: MarketingEventType.COUPON_CLAIMED,
    category: 'COUPON',
    displayName: '优惠券领取或发放成功',
    sourceModule: 'marketing/coupon',
    triggerTiming: '用户券创建并完成库存扣减后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'memberId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event'],
    privacyLevel: 'ASSET',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.COUPON_USED]: {
    eventType: MarketingEventType.COUPON_USED,
    category: 'COUPON',
    displayName: '优惠券核销成功',
    sourceModule: 'marketing/coupon',
    triggerTiming: '订单支付链路核销用户券成功后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'memberId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event'],
    privacyLevel: 'ASSET',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.COUPON_EXPIRED]: {
    eventType: MarketingEventType.COUPON_EXPIRED,
    category: 'COUPON',
    displayName: '优惠券过期',
    sourceModule: 'marketing/coupon/scheduler',
    triggerTiming: '过期任务将用户券标记过期后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'memberId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event'],
    privacyLevel: 'ASSET',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.POINTS_EARNED]: {
    eventType: MarketingEventType.POINTS_EARNED,
    category: 'POINTS',
    displayName: '积分入账成功',
    sourceModule: 'marketing/points',
    triggerTiming: '积分账户和流水写入成功后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'memberId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event'],
    privacyLevel: 'ASSET',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.POINTS_USED]: {
    eventType: MarketingEventType.POINTS_USED,
    category: 'POINTS',
    displayName: '积分扣减成功',
    sourceModule: 'marketing/points',
    triggerTiming: '积分账户和流水扣减成功后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'memberId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event'],
    privacyLevel: 'ASSET',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.POINTS_EXPIRED]: {
    eventType: MarketingEventType.POINTS_EXPIRED,
    category: 'POINTS',
    displayName: '积分过期',
    sourceModule: 'marketing/points/scheduler',
    triggerTiming: '积分过期任务处理成功后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'memberId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event'],
    privacyLevel: 'ASSET',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.INTEGRATION_ORDER_DISCOUNT_CALCULATED]: {
    eventType: MarketingEventType.INTEGRATION_ORDER_DISCOUNT_CALCULATED,
    category: 'ORDER',
    displayName: '订单优惠计算完成',
    sourceModule: 'marketing/integration',
    triggerTiming: '订单优惠试算完成后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: false,
    replayable: true,
    usableScopes: ['RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event'],
    privacyLevel: 'ASSET',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.INTEGRATION_ORDER_CREATED]: {
    eventType: MarketingEventType.INTEGRATION_ORDER_CREATED,
    category: 'ORDER',
    displayName: '订单营销创建处理完成',
    sourceModule: 'marketing/integration',
    triggerTiming: '订单创建链路锁券和冻结积分完成后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event'],
    privacyLevel: 'ASSET',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.INTEGRATION_ORDER_PAID]: {
    eventType: MarketingEventType.INTEGRATION_ORDER_PAID,
    category: 'ORDER',
    displayName: '订单营销支付处理完成',
    sourceModule: 'marketing/integration',
    triggerTiming: '订单支付链路核销券、扣积分和发放消费积分后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['POINTS', 'COUPON', 'TASK', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event'],
    privacyLevel: 'ASSET',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.INTEGRATION_ORDER_CANCELLED]: {
    eventType: MarketingEventType.INTEGRATION_ORDER_CANCELLED,
    category: 'ORDER',
    displayName: '订单营销取消回滚完成',
    sourceModule: 'marketing/integration',
    triggerTiming: '订单取消链路退券和解冻积分完成后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event'],
    privacyLevel: 'ASSET',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.INTEGRATION_ORDER_REFUNDED]: {
    eventType: MarketingEventType.INTEGRATION_ORDER_REFUNDED,
    category: 'ORDER',
    displayName: '订单营销退款回滚完成',
    sourceModule: 'marketing/integration',
    triggerTiming: '订单退款链路退券、补积分和扣回奖励完成后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event'],
    privacyLevel: 'ASSET',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.GROUP_FULL]: {
    eventType: MarketingEventType.GROUP_FULL,
    category: 'PLAY',
    displayName: '拼团满员',
    sourceModule: 'marketing/play',
    triggerTiming: '拼团人数达到规则要求后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'TOUCHPOINT', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event', 'touchpoint'],
    privacyLevel: 'MEMBER',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.GROUP_FAILED]: {
    eventType: MarketingEventType.GROUP_FAILED,
    category: 'PLAY',
    displayName: '拼团失败',
    sourceModule: 'marketing/play',
    triggerTiming: '拼团超时或失败状态确认后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'TOUCHPOINT', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event', 'touchpoint'],
    privacyLevel: 'MEMBER',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.FLASH_SALE_SOLD_OUT]: {
    eventType: MarketingEventType.FLASH_SALE_SOLD_OUT,
    category: 'PLAY',
    displayName: '秒杀售罄',
    sourceModule: 'marketing/play',
    triggerTiming: '秒杀库存确认售罄后',
    idempotencyKey: 'tenantId + configId + eventType',
    orderingKey: 'configId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: false,
    usableScopes: ['TOUCHPOINT', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event', 'touchpoint'],
    privacyLevel: 'LOW',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.COURSE_OPEN]: {
    eventType: MarketingEventType.COURSE_OPEN,
    category: 'PLAY',
    displayName: '课程开班',
    sourceModule: 'marketing/play',
    triggerTiming: '开班条件确认后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'TOUCHPOINT', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event', 'touchpoint'],
    privacyLevel: 'MEMBER',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.COURSE_GROUP_TEAM_CREATED]: {
    eventType: MarketingEventType.COURSE_GROUP_TEAM_CREATED,
    category: 'PLAY',
    displayName: '拼课开团',
    sourceModule: 'marketing/course-group',
    triggerTiming: '团长开团成功后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'TOUCHPOINT', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event', 'touchpoint'],
    privacyLevel: 'MEMBER',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.COURSE_GROUP_MEMBER_JOINED]: {
    eventType: MarketingEventType.COURSE_GROUP_MEMBER_JOINED,
    category: 'PLAY',
    displayName: '拼课真实成员参团',
    sourceModule: 'marketing/course-group',
    triggerTiming: '真实用户支付参团并写入成员投影后',
    idempotencyKey: 'tenantId + instanceId + memberId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'TOUCHPOINT', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event', 'touchpoint'],
    privacyLevel: 'MEMBER',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.COURSE_GROUP_VIRTUAL_FILLED]: {
    eventType: MarketingEventType.COURSE_GROUP_VIRTUAL_FILLED,
    category: 'PLAY',
    displayName: '拼课虚拟补位',
    sourceModule: 'marketing/course-group',
    triggerTiming: '虚拟补位事实 append 到团队 audit 后',
    idempotencyKey: 'tenantId + instanceId + virtualMemberId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event'],
    privacyLevel: 'MEMBER',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.COURSE_GROUP_TEAM_FORMED]: {
    eventType: MarketingEventType.COURSE_GROUP_TEAM_FORMED,
    category: 'PLAY',
    displayName: '拼课成团',
    sourceModule: 'marketing/course-group',
    triggerTiming: '团队投影达到成团条件后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'TOUCHPOINT', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event', 'touchpoint'],
    privacyLevel: 'MEMBER',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.COURSE_GROUP_TEAM_FAILED]: {
    eventType: MarketingEventType.COURSE_GROUP_TEAM_FAILED,
    category: 'PLAY',
    displayName: '拼课失败',
    sourceModule: 'marketing/course-group',
    triggerTiming: '招募失败、超时或关闭团队后',
    idempotencyKey: 'tenantId + instanceId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'TOUCHPOINT', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event', 'touchpoint'],
    privacyLevel: 'MEMBER',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.COURSE_GROUP_SCHEDULE_BOUND]: {
    eventType: MarketingEventType.COURSE_GROUP_SCHEDULE_BOUND,
    category: 'PLAY',
    displayName: '拼课排课绑定',
    sourceModule: 'marketing/course-group',
    triggerTiming: '团队绑定或生成课表后',
    idempotencyKey: 'tenantId + instanceId + scheduleId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TOUCHPOINT', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event', 'touchpoint'],
    privacyLevel: 'MEMBER',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.COURSE_GROUP_CLASS_STARTED]: {
    eventType: MarketingEventType.COURSE_GROUP_CLASS_STARTED,
    category: 'PLAY',
    displayName: '拼课开课',
    sourceModule: 'marketing/course-group',
    triggerTiming: '门店确认上课后',
    idempotencyKey: 'tenantId + instanceId + scheduleId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TOUCHPOINT', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event', 'touchpoint'],
    privacyLevel: 'MEMBER',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.COURSE_GROUP_ATTENDANCE_CONFIRMED]: {
    eventType: MarketingEventType.COURSE_GROUP_ATTENDANCE_CONFIRMED,
    category: 'PLAY',
    displayName: '拼课考勤确认',
    sourceModule: 'marketing/course-group',
    triggerTiming: '真实学员考勤确认后',
    idempotencyKey: 'tenantId + instanceId + attendanceId + memberId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['POINTS', 'TASK', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event'],
    privacyLevel: 'MEMBER',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.COURSE_GROUP_CLASS_FINISHED]: {
    eventType: MarketingEventType.COURSE_GROUP_CLASS_FINISHED,
    category: 'PLAY',
    displayName: '拼课结课',
    sourceModule: 'marketing/course-group',
    triggerTiming: '课程结课后',
    idempotencyKey: 'tenantId + instanceId + scheduleId + eventType',
    orderingKey: 'instanceId',
    tenantScoped: true,
    ruleTriggerable: true,
    replayable: true,
    usableScopes: ['TASK', 'TOUCHPOINT', 'RISK', 'STAT', 'AUDIT'],
    consumers: ['event-stats', 'recent-event', 'touchpoint'],
    privacyLevel: 'MEMBER',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.ACTIVITY_OFF_SHELF]: {
    eventType: MarketingEventType.ACTIVITY_OFF_SHELF,
    category: 'CONFIG',
    displayName: '活动手动下架',
    sourceModule: 'marketing/activity',
    triggerTiming: '活动配置下架后',
    idempotencyKey: 'tenantId + configId + productId + eventType',
    orderingKey: 'configId',
    tenantScoped: true,
    ruleTriggerable: false,
    replayable: false,
    usableScopes: ['CACHE', 'STAT', 'AUDIT'],
    consumers: ['resolution-cache'],
    privacyLevel: 'LOW',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.ACTIVITY_STOCK_DEPLETED]: {
    eventType: MarketingEventType.ACTIVITY_STOCK_DEPLETED,
    category: 'CONFIG',
    displayName: '活动库存耗尽',
    sourceModule: 'marketing/activity',
    triggerTiming: '活动库存归零后',
    idempotencyKey: 'tenantId + configId + productId + eventType',
    orderingKey: 'configId',
    tenantScoped: true,
    ruleTriggerable: false,
    replayable: false,
    usableScopes: ['CACHE', 'STAT', 'AUDIT'],
    consumers: ['resolution-cache'],
    privacyLevel: 'LOW',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.CONFIG_STATUS_CHANGED]: {
    eventType: MarketingEventType.CONFIG_STATUS_CHANGED,
    category: 'CONFIG',
    displayName: '门店玩法配置状态变更',
    sourceModule: 'marketing/config',
    triggerTiming: 'StorePlayConfig 上下架状态更新后',
    idempotencyKey: 'tenantId + configId + productId + eventType',
    orderingKey: 'configId',
    tenantScoped: true,
    ruleTriggerable: false,
    replayable: false,
    usableScopes: ['CACHE', 'STAT', 'AUDIT'],
    consumers: ['resolution-cache'],
    privacyLevel: 'LOW',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.SCENE_RELEASE_PUBLISHED]: {
    eventType: MarketingEventType.SCENE_RELEASE_PUBLISHED,
    category: 'CONFIG',
    displayName: '场景发布成功',
    sourceModule: 'marketing/scene',
    triggerTiming: '场景发布快照创建成功后',
    idempotencyKey: 'tenantId + sceneCode + releaseNo + eventType',
    orderingKey: 'sceneCode',
    tenantScoped: true,
    ruleTriggerable: false,
    replayable: false,
    usableScopes: ['CACHE', 'STAT', 'AUDIT'],
    consumers: ['resolution-cache'],
    privacyLevel: 'LOW',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.POLICY_CONFIG_CHANGED]: {
    eventType: MarketingEventType.POLICY_CONFIG_CHANGED,
    category: 'CONFIG',
    displayName: '策略配置变更',
    sourceModule: 'marketing/policy',
    triggerTiming: '营销策略保存后',
    idempotencyKey: 'tenantId + policyCode + policyType + eventType',
    orderingKey: 'policyCode',
    tenantScoped: true,
    ruleTriggerable: false,
    replayable: false,
    usableScopes: ['CACHE', 'STAT', 'AUDIT'],
    consumers: ['resolution-cache'],
    privacyLevel: 'LOW',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
  [MarketingEventType.PRIORITY_RULE_CHANGED]: {
    eventType: MarketingEventType.PRIORITY_RULE_CHANGED,
    category: 'CONFIG',
    displayName: '活动优先级规则变更',
    sourceModule: 'marketing/resolution',
    triggerTiming: '优先级规则新增、更新、删除或初始化后',
    idempotencyKey: 'tenantId + action + activityType + eventType',
    orderingKey: 'activityType',
    tenantScoped: true,
    ruleTriggerable: false,
    replayable: false,
    usableScopes: ['CACHE', 'STAT', 'AUDIT'],
    consumers: ['resolution-cache'],
    privacyLevel: 'LOW',
    payloadSchemaVersion: 1,
    status: 'ACTIVE',
  },
} as const satisfies Record<MarketingEventType, MarketingEventCatalogItem>;

export const MARKETING_EVENT_CATALOG_LIST: MarketingEventCatalogItem[] = Object.values(MARKETING_EVENT_CATALOG);

export function isKnownMarketingEventType(value: unknown): value is MarketingEventType {
  return typeof value === 'string' && Object.prototype.hasOwnProperty.call(MARKETING_EVENT_CATALOG, value);
}

export function getMarketingEventCatalogItem(type: MarketingEventType): MarketingEventCatalogItem | null {
  return MARKETING_EVENT_CATALOG[type] ?? null;
}

export function hasMarketingEventUsableScope(type: MarketingEventType, scope: MarketingEventUsableScope): boolean {
  const item: MarketingEventCatalogItem | undefined = MARKETING_EVENT_CATALOG[type];
  return item?.usableScopes.includes(scope) ?? false;
}

export function getMarketingEventTypesByUsableScope(scope: MarketingEventUsableScope): MarketingEventType[] {
  return MARKETING_EVENT_CATALOG_LIST.filter(item => item.usableScopes.includes(scope)).map(item => item.eventType);
}
