import { access, readFile, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { setupElegantRouter } from '../vite/plugins/router';

const cwd = process.cwd();
const generatedFiles = [
  'src/typings/elegant-router.d.ts',
  'src/router/elegant/imports.ts',
  'src/router/elegant/routes.ts',
  'src/router/elegant/transform.ts',
].map((filePath) => path.join(cwd, filePath));
const routesFile = path.join(cwd, 'src/router/elegant/routes.ts');
const transformFile = path.join(cwd, 'src/router/elegant/transform.ts');
const routesExportMarker = 'export const generatedRoutes';
const routesSeed = `/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { ElegantConstRoute } from '@elegant-router/vue';

export const generatedRoutes: ElegantConstRoute[] = [];
`;

await writeFile(routesFile, routesSeed);
setupElegantRouter();

function delay(ms: number) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

async function isGeneratedFileReady(filePath: string) {
  try {
    await access(filePath);
    if (filePath === routesFile) {
      const content = await readFile(filePath, 'utf8');

      return content.includes(routesExportMarker) && content.includes('component:');
    }

    const fileStats = await stat(filePath);

    return fileStats.size > 0;
  } catch {
    return false;
  }
}

async function waitForGeneratedFile(filePath: string, attempt = 0): Promise<void> {
  const maxAttempts = 50;

  if (await isGeneratedFileReady(filePath)) {
    return;
  }

  if (attempt >= maxAttempts) {
    throw new Error(`elegant-router did not generate ${path.relative(cwd, filePath)}`);
  }

  // The elegant-router plugin generates files asynchronously on startup.
  await delay(100);
  await waitForGeneratedFile(filePath, attempt + 1);
}

async function waitForGeneratedFiles() {
  await Promise.all(generatedFiles.map((filePath) => waitForGeneratedFile(filePath)));
}

function patchGeneratedRoutesContent(content: string) {
  return content
    .replace(
      "import type { GeneratedRoute } from '@elegant-router/types';",
      "import type { ElegantConstRoute } from '@elegant-router/vue';",
    )
    .replace(
      'export const generatedRoutes: GeneratedRoute[] = [',
      'export const generatedRoutes: ElegantConstRoute[] = [',
    );
}

function patchGeneratedTransformContent(content: string) {
  return content
    .replace(
      'function getSingleLevelRouteComponent(component: string) {\n    const [layout, view] = component.split(FIRST_LEVEL_ROUTE_COMPONENT_SPLIT);\n\n    return {\n      layout: getLayoutName(layout),\n      view: getViewName(view)\n    };\n  }',
      `function getSingleLevelRouteComponent(component: string) {
    const [layout, view] = component.split(FIRST_LEVEL_ROUTE_COMPONENT_SPLIT);

    if (!layout || !view) {
      throw new Error(\`Invalid single level route component: "\${component}"\`);
    }

    return {
      layout: getLayoutName(layout),
      view: getViewName(view)
    };
  }`,
    )
    .replace(
      'const vueRoute = { name, path, ...rest } as RouteRecordRaw;',
      'const vueRoute = { name, path, ...rest } as unknown as RouteRecordRaw;',
    )
    .replace("title: route.meta?.title || ''", "title: typeof route.meta?.title === 'string' ? route.meta.title : ''")
    .replace('} as RouteRecordRaw', '} as unknown as RouteRecordRaw');
}

async function patchGeneratedFile(filePath: string, patchContent: (content: string) => string) {
  const content = await readFile(filePath, 'utf8');
  const patched = patchContent(content);

  if (patched !== content) {
    await writeFile(filePath, patched);
  }
}

await waitForGeneratedFiles();
await patchGeneratedFile(routesFile, patchGeneratedRoutesContent);
await patchGeneratedFile(transformFile, patchGeneratedTransformContent);
