/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue';

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../components/layout/AppHeader.vue')['default']
    AppTabBar: typeof import('./../components/layout/AppTabBar.vue')['default']
    ProductCard: typeof import('./../components/product/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AppHeader: (typeof import('./../components/layout/AppHeader.vue'))['default'];
  const AppTabBar: (typeof import('./../components/layout/AppTabBar.vue'))['default'];
  const ProductCard: (typeof import('./../components/product/ProductCard.vue'))['default'];
  const RouterLink: (typeof import('vue-router'))['RouterLink'];
  const RouterView: (typeof import('vue-router'))['RouterView'];
}
