import { computed, nextTick, ref, shallowRef } from 'vue';
import type { RouteMeta, RouteRecordRaw } from 'vue-router';
import { defineStore } from 'pinia';
import { useBoolean } from '@sa/hooks';
import type { CustomRoute, ElegantConstRoute, LastLevelRouteKey, RouteKey, RouteMap } from '@elegant-router/types';
import { router } from '@/router';
import { fetchGetRoutes } from '@/service/api';
import { humpToLine, isNotNull } from '@/utils/common';
import { SetupStoreId } from '@/enum';
import { MARKETING_ROUTE_NAME, createDynamicRoutes, createStaticRoutes, getAuthVueRoutes } from '@/router/routes';
import { ROOT_ROUTE } from '@/router/routes/builtin';
import { getRouteName, getRoutePath } from '@/router/elegant/transform';
import { normalizeStoreOperationsRoutes } from '@/router/routes/store-ops';
import { useAuthStore } from '../auth';
import { useTabStore } from '../tab';
import {
  filterAuthRoutesByRoles,
  getBreadcrumbsByRoute,
  getCacheRouteNames,
  getGlobalMenusByAuthRoutes,
  getSelectedMenuKeyPathByKey,
  isRouteExistByRouteName,
  sortRoutesByOrder,
  transformMenuToSearchMenus,
  updateLocaleOfGlobalMenus,
} from './shared';

const defaultIcon = import.meta.env.VITE_MENU_ICON;
const retiredAuthRouteNames = new Set(['system_message']);
const retiredAuthRoutePaths = new Set(['/system/message']);

type BackendRouteMeta = RouteMeta & {
  title: string;
  link?: string | null;
  noCache?: boolean | null;
  icon?: string | null;
};

type BackendElegantRoute = Omit<ElegantConstRoute, 'children' | 'meta'> & {
  children?: BackendElegantRoute[];
  hidden?: boolean;
  meta?: BackendRouteMeta;
  query?: string;
};

function ensureBackendRouteMeta(route: BackendElegantRoute) {
  route.meta ??= { title: route.name };
  route.meta.title = typeof route.meta.title === 'string' ? route.meta.title : route.name;

  return route.meta;
}

/**
 * 动态路由下营销菜单子树来自 `customRoutes`，不会经过 `parseRouter`；若 `meta.icon` 缺失，
 * `getGlobalMenuByBaseRoute` 会套用 `VITE_MENU_ICON`。与后端菜单 icon 留空时的侧栏表现对齐为不展示图标。
 */
function applyMarketingSubtreeNoMenuIcon(routes: ElegantConstRoute[]) {
  for (const r of routes) {
    if (!r.meta) r.meta = { title: r.name };
    delete r.meta.icon;
    delete r.meta.localIcon;
    r.meta.noMenuIcon = true;
    if (r.children?.length) applyMarketingSubtreeNoMenuIcon(r.children);
  }
}

function isRetiredAuthRoute(route: ElegantConstRoute) {
  const routeName = String(route.name ?? '');
  const routePath = String(route.path ?? '').replace(/\/+$/, '');
  const component = String(route.component ?? '').toLowerCase();

  return (
    retiredAuthRouteNames.has(routeName) || retiredAuthRoutePaths.has(routePath) || component.includes('system/message')
  );
}

/**
 * 历史库或旧后端缓存可能还带 system_message；公告已合并消息投递入口，
 * 因此前端在注册路由和生成侧栏前做兜底屏蔽，避免旧菜单数据继续暴露。
 */
function filterRetiredAuthRoutes(routes: ElegantConstRoute[]): ElegantConstRoute[] {
  return routes.flatMap((route) => {
    if (isRetiredAuthRoute(route)) {
      return [];
    }

    const nextRoute: ElegantConstRoute = { ...route };
    if (route.children?.length) {
      nextRoute.children = filterRetiredAuthRoutes(route.children);
    }

    if (!nextRoute.component && nextRoute.children?.length === 0) {
      return [];
    }

    return [nextRoute];
  });
}

export const useRouteStore = defineStore(SetupStoreId.Route, () => {
  const authStore = useAuthStore();
  const tabStore = useTabStore();
  const { bool: isInitConstantRoute, setBool: setIsInitConstantRoute } = useBoolean();
  const { bool: isInitAuthRoute, setBool: setIsInitAuthRoute } = useBoolean();

  /**
   * Auth route mode
   *
   * It recommends to use static mode in the development environment, and use dynamic mode in the production
   * environment, if use static mode in development environment, the auth routes will be auto generated by plugin
   * "@elegant-router/vue"
   */
  const authRouteMode = ref(import.meta.env.VITE_AUTH_ROUTE_MODE);

  /** Home route key */
  const routeHome = ref(import.meta.env.VITE_ROUTE_HOME || 'home');

  /** constant routes */
  const constantRoutes = shallowRef<ElegantConstRoute[]>([]);

  function addConstantRoutes(routes: ElegantConstRoute[]) {
    const constantRoutesMap = new Map<string, ElegantConstRoute>([]);

    routes.forEach((route) => {
      constantRoutesMap.set(route.name, route);
    });

    constantRoutes.value = Array.from(constantRoutesMap.values());
  }

  /** auth routes */
  const authRoutes = shallowRef<ElegantConstRoute[]>([]);

  function addAuthRoutes(routes: ElegantConstRoute[]) {
    const authRoutesMap = new Map<string, ElegantConstRoute>([]);

    routes.forEach((route) => {
      if (authRouteMode.value === 'dynamic') {
        if (route.path === '/' && route.children?.length) {
          const child = route.children[0] as BackendElegantRoute;
          child.hidden = (route as BackendElegantRoute).hidden;
          parseRouter(child);
          child.name = Math.random().toString(36).slice(2, 12);
          Object.assign(route, child);
          delete route.children;
          authRoutesMap.set(route.name, route);
          return;
        }
        parseRouter(route);
      }
      authRoutesMap.set(route.name, route);
    });

    const dynamicRoutes = createDynamicRoutes();

    dynamicRoutes.authRoutes.forEach((route) => {
      const parent = authRoutesMap.get(route.name);
      if (parent && route.children) {
        if (authRouteMode.value === 'dynamic' && route.name === MARKETING_ROUTE_NAME) {
          parent.children = route.children;
          return;
        }

        parent.children?.push(...route.children);
        return;
      }

      if (authRouteMode.value === 'dynamic' && route.name === MARKETING_ROUTE_NAME) {
        return;
      }

      authRoutesMap.set(route.name, route);
    });

    authRoutes.value = normalizeStoreOperationsRoutes(filterRetiredAuthRoutes(Array.from(authRoutesMap.values())));
    const marketingRoot = authRoutes.value.find((r) => r.name === MARKETING_ROUTE_NAME);
    if (marketingRoot) {
      applyMarketingSubtreeNoMenuIcon([marketingRoot]);
    }
  }

  // eslint-disable-next-line complexity
  function parseRouter(route: ElegantConstRoute, parent?: ElegantConstRoute) {
    const backendRoute = route as BackendElegantRoute;
    const backendParent = parent as BackendElegantRoute | undefined;
    const meta = ensureBackendRouteMeta(backendRoute);

    if (meta.title.startsWith('route.') || meta.title.startsWith('menu.')) {
      meta.i18nKey = meta.title as App.I18n.I18nKey;
    }
    const isLayout = backendRoute.component === 'Layout';
    const isFramePage = backendRoute.component === 'FrameView';
    const isParentLayout = backendRoute.component === 'ParentView';
    // 外链菜单 URL 存在 path；旧数据可能未写 meta.link，FrameView + http(s) path 兜底识别
    const pathAsUrl = backendRoute.path?.replace(/^\//, '') ?? '';
    const pathLooksExternal = /^https?:\/\//i.test(pathAsUrl);
    if (isFramePage && pathLooksExternal && !isNotNull(meta.link)) {
      meta.link = pathAsUrl;
    }
    const isExternalLink = isNotNull(meta.link);

    backendRoute.path = backendRoute.path.startsWith('/') ? backendRoute.path : `/${backendRoute.path}`;
    backendRoute.path = backendParent ? backendParent.path + backendRoute.path : backendRoute.path;

    const routeName = backendRoute
      .component!.replace(/^\//, '') // Remove leading slash
      .replace(/\/index$/, '')
      .replace(/\//g, '_')
      .replace(/([A-Z])/g, '-$1')
      .toLowerCase();

    backendRoute.name = routeName;

    if (isLayout || isFramePage || isParentLayout) {
      const name = humpToLine(backendRoute.path.substring(1).replace('/', '_'));
      backendRoute.name = backendParent ? `${backendParent.name}_${name}` : name;
    } else {
      // 叶子路由 name 必须与 elegant-router 的 view key 一致（由 component 路径推导的 routeName），
      // 供 imports.ts 与 getRoutePath 对齐。再拼 parent.name 会得到如
      // store_distribution_store_distribution_distribution，与 store_distribution_distribution 不一致，
      // KeepAlive / Tab 切换时易出现异常空白。
      backendRoute.name = routeName;
    }

    if (typeof meta.icon === 'string' && meta.icon.startsWith('local-icon-')) {
      meta.localIcon = meta.icon.replace('local-icon-', 'menu-');
      delete meta.icon;
    } else if (meta.icon === '') {
      // 空串表示显式不要图标；空串对 isNotEmpty 为假，不能走下一分支否则会套上全局默认图标
      delete meta.icon;
      meta.noMenuIcon = true;
    } else if (!isNotNull(meta.icon)) {
      meta.icon = defaultIcon;
    }

    meta.hideInMenu = backendRoute.hidden;
    if (meta.hideInMenu && backendParent && !meta.activeMenu) {
      meta.activeMenu = backendParent.name as RouteKey;
    }
    // 是否需要keepAlive
    meta.keepAlive = !meta.noCache;

    if (isFramePage) {
      if (isExternalLink) {
        meta.href = String(meta.link);
        const random = Math.random().toString(36).slice(2, 12);
        backendRoute.path = `/${random}`;
        backendRoute.name = random;
        backendRoute.component = 'layout.base$view.iframe-page';
      } else {
        try {
          backendRoute.props = {
            url: backendRoute.query ? JSON.parse(backendRoute.query)?.url : undefined,
          };
        } catch {}
      }
      backendRoute.component = backendParent && !isExternalLink ? 'view.iframe-page' : 'layout.base$view.iframe-page';
    } else if (!isLayout && !isParentLayout) {
      // Use the original routeName (view key) to map to views/imports.ts
      backendRoute.component = backendParent ? `view.${routeName}` : `layout.base$view.${routeName}`;
    } else {
      backendRoute.component = isParentLayout ? undefined : 'layout.base';
    }

    delete meta.link;
    delete meta.noCache;
    delete backendRoute.query;
    delete backendRoute.hidden;

    backendRoute.children?.forEach((child) => parseRouter(child, backendRoute));
  }

  const removeRouteFns: (() => void)[] = [];

  /** Global menus */
  const menus = ref<App.Global.Menu[]>([]);
  const searchMenus = computed(() => transformMenuToSearchMenus(menus.value));

  /** Get global menus */
  function getGlobalMenus(routes: ElegantConstRoute[]) {
    menus.value = getGlobalMenusByAuthRoutes(routes);
  }

  /** Update global menus by locale */
  function updateGlobalMenusByLocale() {
    menus.value = updateLocaleOfGlobalMenus(menus.value);
  }

  /** Cache routes */
  const cacheRoutes = ref<RouteKey[]>([]);

  /**
   * Exclude cache routes
   *
   * for reset route cache
   */
  const excludeCacheRoutes = ref<RouteKey[]>([]);

  /**
   * Get cache routes
   *
   * @param routes Vue routes
   */
  function getCacheRoutes(routes: RouteRecordRaw[]) {
    cacheRoutes.value = getCacheRouteNames(routes);
  }

  /**
   * Reset route cache
   *
   * @default router.currentRoute.value.name current route name
   * @param routeKey
   */
  async function resetRouteCache(routeKey?: RouteKey) {
    const routeName = routeKey || (router.currentRoute.value.name as RouteKey);

    excludeCacheRoutes.value.push(routeName);

    await nextTick();

    excludeCacheRoutes.value = [];
  }

  /** Global breadcrumbs */
  const breadcrumbs = computed(() => getBreadcrumbsByRoute(router.currentRoute.value, menus.value));

  /** Reset store */
  async function resetStore() {
    const routeStore = useRouteStore();

    routeStore.$reset();

    resetVueRoutes();

    // after reset store, need to re-init constant route
    await initConstantRoute();
  }

  /** Reset vue routes */
  function resetVueRoutes() {
    removeRouteFns.forEach((fn) => fn());
    removeRouteFns.length = 0;
  }

  /** init constant route */
  async function initConstantRoute() {
    if (isInitConstantRoute.value) return;

    const staticRoute = createStaticRoutes();

    if (authRouteMode.value === 'static') {
      addConstantRoutes(staticRoute.constantRoutes);
    } else {
      addConstantRoutes(staticRoute.constantRoutes);
    }

    handleConstantAndAuthRoutes();

    setIsInitConstantRoute(true);

    tabStore.initHomeTab();
  }

  /**
   * 同一时刻可能由 setupRouter 预热与 beforeEach 守卫并发触发 initAuthRoute；
   * 用 singleton promise 去重，保证 getInfo / getRouters 不会被重复发起。
   */
  let initAuthRoutePromise: Promise<void> | null = null;

  /** Init auth route */
  function initAuthRoute(): Promise<void> {
    if (initAuthRoutePromise) return initAuthRoutePromise;

    initAuthRoutePromise = (async () => {
      try {
        const needFetchUserInfo = !authStore.userInfo.user?.userId;

        if (authRouteMode.value === 'dynamic') {
          // dynamic 模式：getInfo 与 getRouters 互不依赖（fetchGetRoutes 仅需 token），并行减少首屏等待
          await Promise.all([needFetchUserInfo ? authStore.initUserInfo() : Promise.resolve(), initDynamicAuthRoute()]);
        } else {
          // static 模式：initStaticAuthRoute 需要 userInfo.roles 做过滤，仍需串行
          if (needFetchUserInfo) {
            await authStore.initUserInfo();
          }
          initStaticAuthRoute();
        }

        tabStore.initHomeTab();
      } catch {
        // if init auth route failed, reset store
        authStore.resetStore();
      } finally {
        initAuthRoutePromise = null;
      }
    })();

    return initAuthRoutePromise;
  }

  /** Init static auth route */
  function initStaticAuthRoute() {
    const { authRoutes: staticAuthRoutes } = createStaticRoutes();

    if (authStore.isStaticSuper) {
      addAuthRoutes(staticAuthRoutes);
    } else {
      const filteredAuthRoutes = filterAuthRoutesByRoles(staticAuthRoutes, authStore.userInfo.roles);

      addAuthRoutes(filteredAuthRoutes);
    }

    handleConstantAndAuthRoutes();

    setIsInitAuthRoute(true);
  }

  /** Init dynamic auth route */
  async function initDynamicAuthRoute() {
    try {
      const { data } = await fetchGetRoutes();

      if (!data) {
        authStore.resetStore();
        return;
      }

      addAuthRoutes(data);

      handleConstantAndAuthRoutes();

      handleUpdateRootRouteRedirect(routeHome.value);

      setIsInitAuthRoute(true);
    } catch {
      // if fetch user routes failed, reset store
      authStore.resetStore();
    }
  }

  /** handle constant and auth routes */
  function handleConstantAndAuthRoutes() {
    const allRoutes = [...constantRoutes.value, ...authRoutes.value];

    const sortRoutes = sortRoutesByOrder(allRoutes);

    const vueRoutes = getAuthVueRoutes(sortRoutes);

    resetVueRoutes();

    addRoutesToVueRouter(vueRoutes);

    getGlobalMenus(sortRoutes);

    getCacheRoutes(vueRoutes);
  }

  /**
   * Add routes to vue router
   *
   * @param routes Vue routes
   */
  function addRoutesToVueRouter(routes: RouteRecordRaw[]) {
    routes.forEach((route) => {
      const removeFn = router.addRoute(route);
      addRemoveRouteFn(removeFn);
    });
  }

  /**
   * Add remove route fn
   *
   * @param fn
   */
  function addRemoveRouteFn(fn: () => void) {
    removeRouteFns.push(fn);
  }

  /**
   * Update root route redirect when auth route mode is dynamic
   *
   * @param redirectKey Redirect route key
   */
  function handleUpdateRootRouteRedirect(redirectKey: LastLevelRouteKey) {
    const redirect = getRoutePath(redirectKey);

    if (redirect) {
      const rootRoute: CustomRoute = { ...ROOT_ROUTE, redirect };

      router.removeRoute(rootRoute.name);

      const [rootVueRoute] = getAuthVueRoutes([rootRoute]);

      router.addRoute(rootVueRoute);
    }
  }

  /**
   * Get is auth route exist
   *
   * @param routePath Route path
   */
  async function getIsAuthRouteExist(routePath: RouteMap[RouteKey]) {
    const routeName = getRouteName(routePath);

    if (!routeName) {
      return false;
    }

    const { authRoutes: staticAuthRoutes } = createStaticRoutes();
    return isRouteExistByRouteName(routeName, staticAuthRoutes);
  }

  /**
   * Get selected menu key path
   *
   * @param selectedKey Selected menu key
   */
  function getSelectedMenuKeyPath(selectedKey: string) {
    return getSelectedMenuKeyPathByKey(selectedKey, menus.value);
  }

  async function onRouteSwitchWhenLoggedIn() {
    // await authStore.initUserInfo();
  }

  async function onRouteSwitchWhenNotLoggedIn() {
    // some global init logic if it does not need to be logged in
  }

  return {
    resetStore,
    routeHome,
    menus,
    searchMenus,
    updateGlobalMenusByLocale,
    cacheRoutes,
    excludeCacheRoutes,
    resetRouteCache,
    breadcrumbs,
    initConstantRoute,
    isInitConstantRoute,
    initAuthRoute,
    isInitAuthRoute,
    setIsInitAuthRoute,
    getIsAuthRouteExist,
    getSelectedMenuKeyPath,
    onRouteSwitchWhenLoggedIn,
    onRouteSwitchWhenNotLoggedIn,
  };
});
