export const SHARE_UNAVAILABLE_CODE = {
  INVALID: 'SHARE_TOKEN_INVALID',
  EXPIRED: 'SHARE_EXPIRED',
  CLICK_LIMIT_REACHED: 'SHARE_CLICK_LIMIT_REACHED',
  TOKEN_DISABLED: 'SHARE_TOKEN_DISABLED',
} as const;

export type ShareUnavailableCode = (typeof SHARE_UNAVAILABLE_CODE)[keyof typeof SHARE_UNAVAILABLE_CODE];

export const SHARE_UNAVAILABLE_MESSAGE: Record<ShareUnavailableCode, string> = {
  [SHARE_UNAVAILABLE_CODE.INVALID]: '分销链接不存在或无效',
  [SHARE_UNAVAILABLE_CODE.EXPIRED]: '分销链接已过期',
  [SHARE_UNAVAILABLE_CODE.CLICK_LIMIT_REACHED]: '分销链接点击次数已达上限',
  [SHARE_UNAVAILABLE_CODE.TOKEN_DISABLED]: '分销链接已禁用',
};
