import type { CartItem } from '@/store/cart';

/**
 * 开发环境购物车列表数据（10 条），与 {@link CartItem} 一致。
 * 由 `cart.vue` 在 `import.meta.env.DEV` 下注入；生产构建不会执行注入逻辑。
 */
export const MOCK_CART_ITEMS: CartItem[] = [
  {
    id: 'mock-cart-001',
    skuId: 'mock-sku-001',
    productId: 'mock-prod-001',
    productName: '有机全脂鲜牛奶 950ml',
    productImg: '/static/images/placeholder.png',
    specData: { 规格: '950ml', 保质期: '7天' },
    addPrice: 18.8,
    currentPrice: 16.8,
    priceChanged: false,
    quantity: 2,
    stockStatus: 'normal',
    checked: true,
    activityType: 'MEMBER_PRICE',
    activityNameSnapshot: '会员价',
    displayPriceSnapshot: 18.8,
  },
  {
    id: 'mock-cart-002',
    skuId: 'mock-sku-002',
    productId: 'mock-prod-002',
    productName: '全麦吐司面包 切片装',
    productImg: '/static/images/placeholder.png',
    specData: { 规格: '500g/袋' },
    addPrice: 12.5,
    currentPrice: 12.5,
    priceChanged: false,
    quantity: 1,
    stockStatus: 'normal',
    checked: true,
  },
  {
    id: 'mock-cart-003',
    skuId: 'mock-sku-003',
    productId: 'mock-prod-003',
    productName: '新鲜赣南脐橙 约1kg',
    productImg: '/static/images/fresh-navel-oranges.jpg',
    specData: { 品类: '鲜橙', 规格: '约1kg' },
    addPrice: 22.8,
    currentPrice: 18.8,
    priceChanged: false,
    quantity: 1,
    stockStatus: 'normal',
    checked: true,
    activityType: 'FLASH_SALE',
    activityNameSnapshot: '限时秒杀',
    displayPriceSnapshot: 22.8,
  },
  {
    id: 'mock-cart-004',
    skuId: 'mock-sku-004',
    productId: 'mock-prod-004',
    productName: '心相印 山野绽绿 4层柔厚面巾纸 M码 90抽',
    productImg: '/static/images/xinxiangyin-shanye-tissue-m90.jpg',
    specData: { 规格: 'M码 90抽', 特点: '100%原生木浆 · 无香' },
    addPrice: 29.9,
    currentPrice: 26.9,
    priceChanged: false,
    quantity: 3,
    stockStatus: 'normal',
    checked: false,
    activityType: 'COURSE_GROUP',
    activityNameSnapshot: '2人成团',
  },
  {
    id: 'mock-cart-005',
    skuId: 'mock-sku-005',
    productId: 'mock-prod-005',
    productName: '象小家 浴室清洁剂 500g',
    productImg: '/static/images/bathroom-cleaner-500g.jpg',
    specData: { 净含量: '500g', 功效: '99.9%抑菌' },
    addPrice: 24.9,
    currentPrice: 19.9,
    priceChanged: false,
    quantity: 2,
    stockStatus: 'insufficient',
    checked: true,
  },
  {
    id: 'mock-cart-006',
    skuId: 'mock-sku-006',
    productId: 'mock-prod-006',
    productName: '免手洗平板拖把 家用',
    productImg: '/static/images/flat-mop-white.jpg',
    specData: { 类型: '自挤水平板拖把' },
    addPrice: 79.0,
    currentPrice: 69.0,
    priceChanged: false,
    quantity: 1,
    stockStatus: 'soldOut',
    checked: false,
  },
  {
    id: 'mock-cart-007',
    skuId: 'mock-sku-007',
    productId: 'mock-prod-007',
    productName: 'TPE 瑜伽垫 加厚防滑',
    productImg: '/static/images/placeholder.png',
    specData: { 颜色: '薄荷绿', 尺寸: '183×61cm' },
    addPrice: 79.0,
    currentPrice: 69.0,
    priceChanged: true,
    quantity: 1,
    stockStatus: 'normal',
    checked: true,
    activityType: 'NEWCOMER',
    activityNameSnapshot: '新人专享',
  },
  {
    id: 'mock-cart-008',
    skuId: 'mock-sku-008',
    productId: 'mock-prod-008',
    productName: '真无线蓝牙耳机 降噪款',
    productImg: '/static/images/placeholder.png',
    specData: null,
    addPrice: 199.0,
    currentPrice: 199.0,
    priceChanged: false,
    quantity: 1,
    stockStatus: 'normal',
    checked: true,
  },
  {
    id: 'mock-cart-009',
    skuId: 'mock-sku-009',
    productId: 'mock-prod-009',
    productName: '幼儿认知绘本套装（全12册）',
    productImg: '/static/images/placeholder.png',
    specData: { 年龄段: '2-4岁' },
    addPrice: 128.0,
    currentPrice: 99.0,
    priceChanged: false,
    quantity: 1,
    stockStatus: 'normal',
    checked: true,
    activityType: 'COURSE_GROUP',
    activityNameSnapshot: '拼课价',
  },
  {
    id: 'mock-cart-010',
    skuId: 'mock-sku-010',
    productId: 'mock-prod-010',
    productName: '不锈钢保温杯 480ml',
    productImg: '/static/images/placeholder.png',
    specData: { 颜色: '磨砂黑' },
    addPrice: 89.0,
    currentPrice: 79.0,
    priceChanged: false,
    quantity: 2,
    stockStatus: 'normal',
    checked: true,
    activityContextKey: 'act-mock-member-001',
    activityType: 'MEMBER_PRICE',
    activityNameSnapshot: '会员日',
    displayPriceSnapshot: 89.0,
  },
];
