import { PrismaClient } from '@prisma/client';

export async function seedDefaultModules(prisma: PrismaClient) {
  await prisma.mktSceneModule.createMany({
    data: [
      {
        tenantId: '000000',
        sceneCode: 'HOME_FEATURED',
        moduleCode: 'HOME_BANNER',
        moduleName: '首页横幅',
        moduleType: 'BANNER',
        displayOrder: 1,
        limitSize: 5,
        sourcePolicyCode: 'DEFAULT_SOURCE',
        resolverPolicyCode: 'DEFAULT_RESOLVER',
        cardTemplateCode: 'BANNER_CARD',
        status: 'ACTIVE',
      },
      {
        tenantId: '000000',
        sceneCode: 'HOME_FEATURED',
        moduleCode: 'HOME_PRODUCT_LIST',
        moduleName: '首页商品列表',
        moduleType: 'PRODUCT_LIST',
        displayOrder: 2,
        limitSize: 20,
        sourcePolicyCode: 'DEFAULT_SOURCE',
        resolverPolicyCode: 'DEFAULT_RESOLVER',
        cardTemplateCode: 'PRODUCT_CARD',
        status: 'ACTIVE',
      },
      {
        tenantId: '000000',
        sceneCode: 'HOME_BEST_PICKS',
        moduleCode: 'BEST_PICKS_PRODUCTS',
        moduleName: '精品推荐商品',
        moduleType: 'PRODUCT_LIST',
        displayOrder: 1,
        limitSize: 20,
        sourcePolicyCode: 'DEFAULT_SOURCE',
        resolverPolicyCode: 'DEFAULT_RESOLVER',
        sortPolicyCode: 'SORT_RECOMMEND_WEIGHT',
        audiencePolicyCode: 'DEFAULT_AUDIENCE_ALL',
        cardTemplateCode: 'PRODUCT_CARD',
        status: 'ACTIVE',
        uiConfig: { featuredCount: 3 },
      },
      {
        tenantId: '000000',
        sceneCode: 'HOME_GUESS_LIKES',
        moduleCode: 'GUESS_LIKES_PRODUCTS',
        moduleName: '猜你喜欢商品',
        moduleType: 'PRODUCT_LIST',
        displayOrder: 1,
        limitSize: 20,
        sourcePolicyCode: 'DEFAULT_SOURCE',
        resolverPolicyCode: 'DEFAULT_RESOLVER',
        sortPolicyCode: 'SORT_TIME_ASC',
        audiencePolicyCode: 'DEFAULT_AUDIENCE_ALL',
        cardTemplateCode: 'PRODUCT_CARD',
        status: 'ACTIVE',
        uiConfig: { featuredCount: 2 },
      },
      {
        tenantId: '000000',
        sceneCode: 'HOME_MEMBER_ZONE',
        moduleCode: 'MEMBER_ZONE_PRODUCTS',
        moduleName: '会员专区商品',
        moduleType: 'PRODUCT_LIST',
        displayOrder: 1,
        limitSize: 20,
        sourcePolicyCode: 'DEFAULT_SOURCE',
        resolverPolicyCode: 'DEFAULT_RESOLVER',
        sortPolicyCode: 'SORT_RECOMMEND_WEIGHT',
        audiencePolicyCode: 'MEMBER_AUDIENCE',
        cardTemplateCode: 'PRODUCT_CARD',
        status: 'ACTIVE',
        uiConfig: { featuredCount: 3 },
      },
    ],
    skipDuplicates: true,
  });
  console.log('  ✓ 默认营销场景模块已创建');
}
