import assert from 'node:assert/strict';
import test from 'node:test';

import {
  collectOpenApiSurface,
  extractServiceApiImports,
  parseElegantViewImports,
  parseRouteEntries,
  renderAdminRoutePageApiMap,
  renderOpenApiSurfaceMap,
} from './generate-project-maps.mjs';

test('collectOpenApiSurface extracts operations and schema refs', () => {
  const rows = collectOpenApiSurface({
    paths: {
      '/admin/users': {
        get: {
          tags: ['user'],
          operationId: 'listUsers',
          summary: 'List users',
          responses: {
            200: {
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/UserListVo' },
                },
              },
            },
          },
        },
      },
    },
  });

  assert.deepEqual(rows, [
    {
      method: 'GET',
      path: '/admin/users',
      tags: 'user',
      operationId: 'listUsers',
      summary: 'List users',
      schemas: 'UserListVo',
    },
  ]);
});

test('parseElegantViewImports maps route keys to view files', () => {
  const map = parseElegantViewImports(
    '  system_user: () => import("@/views/system/user/index.vue"),\n  "store_order-list": () => import("@/views/store/order/list/index.vue"),',
  );

  assert.equal(map.get('system_user'), 'system/user/index.vue');
  assert.equal(map.get('store_order-list'), 'store/order/list/index.vue');
});

test('parseRouteEntries extracts routed view components', () => {
  const routes = parseRouteEntries(`
    {
      name: 'system_user',
      path: '/system/user',
      component: 'view.system_user',
    },
    {
      name: 'login',
      path: '/login',
      component: 'layout.blank$view.login',
    },
  `);

  assert.deepEqual(routes, [
    { name: 'system_user', path: '/system/user', viewKey: 'system_user' },
    { name: 'login', path: '/login', viewKey: 'login' },
  ]);
});

test('extractServiceApiImports finds static and dynamic service api imports', () => {
  const imports = extractServiceApiImports(`
    import { fetchUsers } from '@/service/api/system/user';
    const api = import('@/service/api/store/order.ts');
  `);

  assert.deepEqual(imports, ['store/order', 'system/user']);
});

test('rendered maps include generated notice and totals', () => {
  const date = new Date('2026-05-07T00:00:00.000Z');
  assert.match(renderOpenApiSurfaceMap([], { generatedAt: date }), /Total operations: 0/);
  assert.match(
    renderAdminRoutePageApiMap([{ routePath: '/x', name: 'x', viewPath: 'x/index.vue', apiImports: [] }], {
      generatedAt: date,
    }),
    /Generated by `pnpm harness:maps`/,
  );
});
