import type {
  HunanDistributorApplicationBlueprint,
  HunanMemberBlueprint,
  HunanReferralCodeBlueprint,
  HunanUpgradeApplicationBlueprint,
} from './types';
import {
  HUNAN_FULL_DEFAULT_AVATARS,
  HUNAN_FULL_MEMBER_PASSWORD_HASH,
  hunanFullMobile,
} from './shared';

function avatar(index: number): string {
  return HUNAN_FULL_DEFAULT_AVATARS[index % HUNAN_FULL_DEFAULT_AVATARS.length];
}

function member(
  memberId: string,
  sequence: number,
  nickname: string,
  extras: Partial<HunanMemberBlueprint> = {},
): HunanMemberBlueprint {
  return {
    memberId,
    mobile: hunanFullMobile(sequence),
    nickname,
    avatar: avatar(sequence),
    status: 'NORMAL',
    levelId: 0,
    parentId: null,
    indirectParentId: null,
    referralCode: null,
    walletStatus: 'NORMAL',
    walletBalance: 0,
    walletFrozen: 0,
    walletIncome: 0,
    pointsAvailable: 0,
    tags: [],
    ...extras,
  };
}

const l2Members: HunanMemberBlueprint[] = [
  member('hf-member-l2-01', 1, '星城团长周岚', {
    levelId: 2,
    walletBalance: 1260,
    walletIncome: 4180,
    pointsAvailable: 860,
    referralCode: 'T000-HF21',
    tags: ['l2', '核心推荐人'],
  }),
  member('hf-member-l2-02', 2, '湘江团长宋冉', {
    levelId: 2,
    walletBalance: 980,
    walletIncome: 3320,
    pointsAvailable: 720,
    referralCode: 'T000-HF22',
    tags: ['l2', '课程推荐'],
  }),
  member('hf-member-l2-03', 3, '岳麓团长许夏', {
    levelId: 2,
    walletBalance: 1530,
    walletIncome: 5012,
    pointsAvailable: 900,
    referralCode: 'T000-HF23',
    tags: ['l2', '零售推荐'],
  }),
  member('hf-member-l2-04', 4, '橘子洲团长孟禾', {
    levelId: 2,
    walletBalance: 760,
    walletIncome: 2870,
    pointsAvailable: 640,
    referralCode: 'T000-HF24',
    tags: ['l2', '场景投放推荐'],
  }),
];

const l1Members: HunanMemberBlueprint[] = [
  member('hf-member-l1-01', 5, '门店合伙人秦北', {
    levelId: 1,
    parentId: 'hf-member-l2-01',
    walletBalance: 520,
    walletIncome: 1680,
    pointsAvailable: 420,
    tags: ['l1', '零售分销'],
  }),
  member('hf-member-l1-02', 6, '门店合伙人林湾', {
    levelId: 1,
    parentId: 'hf-member-l2-01',
    walletBalance: 460,
    walletIncome: 1420,
    pointsAvailable: 380,
    tags: ['l1', '新人推荐'],
  }),
  member('hf-member-l1-03', 7, '课程顾问陆清', {
    levelId: 1,
    parentId: 'hf-member-l2-02',
    walletBalance: 330,
    walletIncome: 920,
    pointsAvailable: 280,
    tags: ['l1', '课程推荐'],
  }),
  member('hf-member-l1-04', 8, '课程顾问安澄', {
    levelId: 1,
    parentId: 'hf-member-l2-02',
    walletBalance: 410,
    walletIncome: 1080,
    pointsAvailable: 310,
    tags: ['l1', '课程分佣'],
  }),
  member('hf-member-l1-05', 9, '社区团长余白', {
    levelId: 1,
    parentId: 'hf-member-l2-03',
    walletBalance: 620,
    walletIncome: 1790,
    pointsAvailable: 500,
    tags: ['l1', '即时零售'],
  }),
  member('hf-member-l1-06', 10, '社区团长顾苒', {
    levelId: 1,
    parentId: 'hf-member-l2-03',
    walletBalance: 580,
    walletIncome: 1510,
    pointsAvailable: 470,
    tags: ['l1', '礼盒团购'],
  }),
  member('hf-member-l1-07', 11, '活动达人周木', {
    levelId: 1,
    parentId: 'hf-member-l2-04',
    walletBalance: 250,
    walletIncome: 660,
    pointsAvailable: 260,
    tags: ['l1', '活动分享'],
  }),
  member('hf-member-l1-08', 12, '活动达人宋野', {
    levelId: 1,
    parentId: 'hf-member-l2-04',
    walletBalance: 210,
    walletIncome: 590,
    pointsAvailable: 240,
    tags: ['l1', '秒杀拉新'],
  }),
];

const regularMembers: HunanMemberBlueprint[] = Array.from({ length: 18 }, (_, index) => {
  const sequence = index + 13;
  const parentIndex = index % l1Members.length;
  const parent = l1Members[parentIndex];
  return member(`hf-member-regular-${String(index + 1).padStart(2, '0')}`, sequence, `普通会员${index + 1}`, {
    parentId: parent.memberId,
    indirectParentId: parent.parentId,
    walletBalance: 20 + index * 3,
    walletIncome: 0,
    pointsAvailable: 60 + index * 15,
    tags: ['normal', index % 2 === 0 ? '零售用户' : '课程用户'],
  });
});

const pendingApplicants: HunanMemberBlueprint[] = Array.from({ length: 4 }, (_, index) =>
  member(`hf-pending-${String(index + 1).padStart(2, '0')}`, index + 31, `待审核分销${index + 1}`, {
    parentId: l1Members[index].memberId,
    indirectParentId: l1Members[index].parentId,
    walletBalance: 12 + index * 4,
    pointsAvailable: 120 + index * 40,
    tags: ['applicant', 'pending'],
  }),
);

const rejectedApplicants: HunanMemberBlueprint[] = Array.from({ length: 3 }, (_, index) =>
  member(`hf-rejected-${String(index + 1).padStart(2, '0')}`, index + 35, `已驳回分销${index + 1}`, {
    parentId: l1Members[index + 2].memberId,
    indirectParentId: l1Members[index + 2].parentId,
    walletBalance: 8,
    pointsAvailable: 90 + index * 20,
    tags: ['applicant', 'rejected'],
  }),
);

const specialMembers: HunanMemberBlueprint[] = [
  member('hf-freeze-01', 38, '钱包冻结会员1', {
    parentId: 'hf-member-l1-05',
    indirectParentId: 'hf-member-l2-03',
    walletStatus: 'FROZEN',
    walletBalance: 42,
    walletFrozen: 120,
    pointsAvailable: 200,
    tags: ['special', 'wallet-frozen'],
  }),
  member('hf-freeze-02', 39, '钱包冻结会员2', {
    parentId: 'hf-member-l1-07',
    indirectParentId: 'hf-member-l2-04',
    walletStatus: 'FROZEN',
    walletBalance: 18,
    walletFrozen: 80,
    pointsAvailable: 140,
    tags: ['special', 'wallet-frozen'],
  }),
  member('hf-disabled-01', 40, '停用会员1', {
    status: 'DISABLED',
    walletStatus: 'DISABLED',
    walletBalance: 0,
    pointsAvailable: 60,
    tags: ['special', 'disabled'],
  }),
  member('hf-disabled-02', 41, '停用会员2', {
    status: 'DISABLED',
    walletStatus: 'DISABLED',
    walletBalance: 0,
    pointsAvailable: 30,
    tags: ['special', 'disabled'],
  }),
];

const blacklistMembers: HunanMemberBlueprint[] = [
  member('hf-black-01', 42, '黑名单样本1', {
    parentId: 'hf-member-l1-08',
    indirectParentId: 'hf-member-l2-04',
    walletBalance: 12,
    pointsAvailable: 50,
    tags: ['blacklist'],
  }),
  member('hf-black-02', 43, '黑名单样本2', {
    parentId: 'hf-member-l1-02',
    indirectParentId: 'hf-member-l2-01',
    walletBalance: 16,
    pointsAvailable: 55,
    tags: ['blacklist'],
  }),
];

export const HUNAN_FULL_MEMBERS: HunanMemberBlueprint[] = [
  ...l2Members,
  ...l1Members,
  ...regularMembers,
  ...pendingApplicants,
  ...rejectedApplicants,
  ...specialMembers,
  ...blacklistMembers,
];

export const HUNAN_FULL_REFERRAL_CODES: HunanReferralCodeBlueprint[] = l2Members.map((memberBlueprint, index) => ({
  memberId: memberBlueprint.memberId,
  code: memberBlueprint.referralCode!,
  qrCodeUrl: `https://nest-admin.oss-cn-beijing.aliyuncs.com/2026/04/17/referral-${index + 1}.png`,
  usageCount: 3 + index * 2,
  isActive: true,
}));

export const HUNAN_FULL_DIST_APPLICATIONS: HunanDistributorApplicationBlueprint[] = [
  ...pendingApplicants.map((memberBlueprint, index) => ({
    memberId: memberBlueprint.memberId,
    status: 'PENDING' as const,
    applyReason: '希望成为社区分销员，已完成基础消费并提交资料',
    evidenceOrderId: ['hf-order-034', 'hf-order-035', 'hf-order-036', 'hf-order-037'][index] ?? null,
    evidenceOrderSn: ['HF-ORDER-034', 'HF-ORDER-035', 'HF-ORDER-036', 'HF-ORDER-037'][index] ?? null,
    evidenceScenarioType: (['product-normal', 'product-flash-sale', 'service-normal', 'product-normal'] as const)[index] ?? null,
    sourceSceneCode: (['HF_SCENE_HOME', 'HF_SCENE_FLASH', 'HF_SCENE_COURSE', 'HF_SCENE_HOME'] as const)[index] ?? null,
    sourceModuleCode: (['HF_HOME_GOODS', 'HF_FLASH_TODAY', 'HF_COURSE_RECOMMEND', 'HF_HOME_GOODS'] as const)[index] ?? null,
    linkedActivityType: (['APPLICATION_EVIDENCE', 'FLASH_SALE', 'SERVICE_THRESHOLD', 'MANUAL_REVIEW'] as const)[index] ?? null,
  })),
  ...rejectedApplicants.map((memberBlueprint, index) => ({
    memberId: memberBlueprint.memberId,
    status: 'REJECTED' as const,
    applyReason: '尝试申请分销权限',
    evidenceOrderId: ['hf-order-038', 'hf-order-039', 'hf-order-043'][index] ?? null,
    evidenceOrderSn: ['HF-ORDER-038', 'HF-ORDER-039', 'HF-ORDER-043'][index] ?? null,
    evidenceScenarioType: (['product-normal', 'service-course-group', 'refund-full'] as const)[index] ?? null,
    sourceSceneCode: (['HF_SCENE_HOME', 'HF_SCENE_COURSE', 'HF_SCENE_HOME'] as const)[index] ?? null,
    sourceModuleCode: (['HF_HOME_GOODS', 'HF_COURSE_GROUP', 'HF_HOME_GOODS'] as const)[index] ?? null,
    linkedActivityType: (['RISK_CONTROL', 'COURSE_GROUP', 'AFTER_SALES'] as const)[index] ?? null,
    reviewerId: 'hf_dist_reviewer',
    reviewRemark: index === 0 ? '命中风控拒绝样本' : '资料不完整',
    autoReviewed: false,
  })),
  {
    memberId: 'hf-member-regular-01',
    status: 'APPROVED',
    applyReason: '历史活跃用户，已达自动审核门槛',
    evidenceOrderId: 'hf-order-001',
    evidenceOrderSn: 'HF-ORDER-001',
    evidenceScenarioType: 'product-normal',
    sourceSceneCode: 'HF_SCENE_HOME',
    sourceModuleCode: 'HF_HOME_GOODS',
    linkedActivityType: 'APPLICATION_EVIDENCE',
    reviewerId: 'hf_dist_reviewer',
    reviewRemark: '转化为一级分销员样本',
    autoReviewed: true,
  },
  {
    memberId: 'hf-member-regular-02',
    status: 'REVIEWING',
    applyReason: '等待人工复核的分销申请样本',
    evidenceOrderId: 'hf-order-002',
    evidenceOrderSn: 'HF-ORDER-002',
    evidenceScenarioType: 'product-flash-sale',
    sourceSceneCode: 'HF_SCENE_FLASH',
    sourceModuleCode: 'HF_FLASH_TODAY',
    linkedActivityType: 'FLASH_SALE',
    reviewerId: 'hf_dist_reviewer',
    reviewRemark: '补充线下门店资质中',
    autoReviewed: false,
  },
  {
    memberId: 'hf-member-regular-05',
    status: 'CANCELLED',
    applyReason: '因个人原因撤回分销申请',
    evidenceOrderId: 'hf-order-006',
    evidenceOrderSn: 'HF-ORDER-006',
    evidenceScenarioType: 'product-exchange',
    sourceSceneCode: 'HF_SCENE_NEWCOMER',
    sourceModuleCode: 'HF_NEWCOMER_COUPON',
    linkedActivityType: 'COUPON_EXCHANGE',
    reviewerId: 'hf_dist_reviewer',
    reviewRemark: '用户主动撤销',
    autoReviewed: false,
  },
  {
    memberId: 'hf-member-regular-07',
    status: 'APPROVED',
    applyReason: '场景触达成交稳定，申请成为分销员',
    evidenceOrderId: 'hf-order-026',
    evidenceOrderSn: 'HF-ORDER-026',
    evidenceScenarioType: 'product-normal',
    sourceSceneCode: 'HF_SCENE_NEWCOMER',
    sourceModuleCode: 'HF_NEWCOMER_COUPON',
    linkedActivityType: 'FIRST_ORDER',
    reviewerId: 'hf_dist_reviewer',
    reviewRemark: '补齐身份证与门店凭证后通过',
    autoReviewed: false,
  },
  {
    memberId: 'hf-member-regular-08',
    status: 'PENDING',
    applyReason: '连续参与拼课，申请成为课程分销员',
    evidenceOrderId: 'hf-order-018',
    evidenceOrderSn: 'HF-ORDER-018',
    evidenceScenarioType: 'service-course-group',
    sourceSceneCode: 'HF_SCENE_COURSE',
    sourceModuleCode: 'HF_COURSE_GROUP',
    linkedActivityType: 'COURSE_GROUP',
  },
  {
    memberId: 'hf-black-01',
    status: 'REJECTED',
    applyReason: '黑名单用户申请分销',
    evidenceOrderId: 'hf-order-040',
    evidenceOrderSn: 'HF-ORDER-040',
    evidenceScenarioType: 'product-normal',
    sourceSceneCode: 'HF_SCENE_HOME',
    sourceModuleCode: 'HF_HOME_INSTANT',
    linkedActivityType: 'RISK_CONTROL',
    reviewerId: 'hf_dist_reviewer',
    reviewRemark: '命中风控黑名单，拒绝通过',
    autoReviewed: true,
  },
  {
    memberId: 'hf-member-regular-09',
    status: 'REVIEWING',
    applyReason: '新人专享混合单成交后，提交分销申请等待人工复核',
    evidenceOrderId: 'hf-order-044',
    evidenceOrderSn: 'HF-ORDER-044',
    evidenceScenarioType: 'mixed-marketing',
    sourceSceneCode: 'HF_SCENE_NEWCOMER',
    sourceModuleCode: 'HF_NEWCOMER_PRICE',
    linkedActivityType: 'NEWCOMER_EXCLUSIVE',
    reviewerId: 'hf_dist_reviewer',
    reviewRemark: '核验临时分享链路与服务商品混合成交',
    autoReviewed: false,
  },
  {
    memberId: 'hf-member-regular-10',
    status: 'APPROVED',
    applyReason: '满减大单成交稳定，触发人工兜底后转一级分销员',
    evidenceOrderId: 'hf-order-045',
    evidenceOrderSn: 'HF-ORDER-045',
    evidenceScenarioType: 'product-full-reduction',
    sourceSceneCode: 'HF_SCENE_HOME',
    sourceModuleCode: 'HF_HOME_GOODS',
    linkedActivityType: 'FULL_REDUCTION',
    reviewerId: 'hf_dist_reviewer',
    reviewRemark: '原价佣金保护策略核验通过',
    autoReviewed: false,
  },
  {
    memberId: 'hf-member-regular-14',
    status: 'PENDING',
    applyReason: '拼课订单处于冻结期，先保留课程分销申请',
    evidenceOrderId: 'hf-order-046',
    evidenceOrderSn: 'HF-ORDER-046',
    evidenceScenarioType: 'service-course-group',
    sourceSceneCode: 'HF_SCENE_COURSE',
    sourceModuleCode: 'HF_COURSE_GROUP',
    linkedActivityType: 'COURSE_GROUP',
  },
  {
    memberId: 'hf-freeze-01',
    status: 'CANCELLED',
    applyReason: '售后部分退款后，用户主动撤回分销申请',
    evidenceOrderId: 'hf-order-047',
    evidenceOrderSn: 'HF-ORDER-047',
    evidenceScenarioType: 'refund-partial',
    sourceSceneCode: 'HF_SCENE_HOME',
    sourceModuleCode: 'HF_HOME_GOODS',
    linkedActivityType: 'AFTER_SALES',
    reviewerId: 'hf_dist_reviewer',
    reviewRemark: '售后差异佣金已核验，申请撤回',
    autoReviewed: false,
  },
  {
    memberId: 'hf-member-regular-15',
    status: 'APPROVED',
    applyReason: '绑定上级链路稳定，延迟结算订单满足分销准入',
    evidenceOrderId: 'hf-order-049',
    evidenceOrderSn: 'HF-ORDER-049',
    evidenceScenarioType: 'product-normal',
    sourceSceneCode: 'HF_SCENE_HOME',
    sourceModuleCode: 'HF_HOME_GOODS',
    linkedActivityType: 'POINTS_DEDUCT',
    reviewerId: 'hf_dist_reviewer',
    reviewRemark: '绑定关系与延期结算策略校验通过',
    autoReviewed: false,
  },
  {
    memberId: 'hf-black-02',
    status: 'REJECTED',
    applyReason: '黑名单用户再次尝试申请分销',
    evidenceOrderId: 'hf-order-050',
    evidenceOrderSn: 'HF-ORDER-050',
    evidenceScenarioType: 'product-normal',
    sourceSceneCode: 'HF_SCENE_HOME',
    sourceModuleCode: 'HF_HOME_INSTANT',
    linkedActivityType: 'RISK_CONTROL',
    reviewerId: 'hf_dist_reviewer',
    reviewRemark: '命中黑名单阻断规则，拒绝分销申请',
    autoReviewed: true,
  },
];

export const HUNAN_FULL_UPGRADE_APPLICATIONS: HunanUpgradeApplicationBlueprint[] = [
  {
    memberId: 'hf-member-l1-03',
    fromLevel: 1,
    toLevel: 2,
    applyType: 'PRODUCT_PURCHASE',
    orderId: 'hf-order-025',
    orderSn: 'HF-ORDER-025',
    evidenceScenarioType: 'service-normal',
    status: 'APPROVED',
    sourceSceneCode: 'HF_SCENE_COURSE',
    sourceModuleCode: 'HF_COURSE_RECOMMEND',
    linkedActivityType: 'COURSE_GROUP',
    reviewBy: 'hf_dist_reviewer',
    reviewRemark: '升级课程合伙人成功',
  },
  {
    memberId: 'hf-member-regular-03',
    fromLevel: 0,
    toLevel: 1,
    applyType: 'REFERRAL_CODE',
    status: 'PENDING',
    referralCode: 'T000-HF24',
    referrerId: 'hf-member-l2-04',
    sourceSceneCode: 'HF_SCENE_NEWCOMER',
    sourceModuleCode: 'HF_NEWCOMER_PRICE',
    linkedActivityType: 'NEWCOMER_EXCLUSIVE',
  },
  {
    memberId: 'hf-rejected-01',
    fromLevel: 0,
    toLevel: 1,
    applyType: 'REFERRAL_CODE',
    status: 'REJECTED',
    referralCode: 'T000-HF21',
    referrerId: 'hf-member-l2-01',
    sourceSceneCode: 'HF_SCENE_HOME',
    sourceModuleCode: 'HF_HOME_GOODS',
    linkedActivityType: 'FULL_REDUCTION',
    reviewBy: 'hf_dist_reviewer',
    reviewRemark: '推荐关系不满足审核条件',
  },
  {
    memberId: 'hf-member-l1-07',
    fromLevel: 1,
    toLevel: 2,
    applyType: 'PRODUCT_PURCHASE',
    orderId: 'hf-order-009',
    orderSn: 'HF-ORDER-009',
    evidenceScenarioType: 'member-upgrade',
    status: 'APPROVED',
    sourceSceneCode: 'HF_SCENE_HOME',
    sourceModuleCode: 'HF_HOME_INSTANT',
    linkedActivityType: 'MEMBER_UPGRADE',
    reviewBy: 'hf_dist_reviewer',
    reviewRemark: '会员升级商品购买成功',
  },
  {
    memberId: 'hf-member-regular-07',
    fromLevel: 0,
    toLevel: 1,
    applyType: 'PRODUCT_PURCHASE',
    orderId: 'hf-order-041',
    orderSn: 'HF-ORDER-041',
    evidenceScenarioType: 'member-upgrade',
    status: 'APPROVED',
    sourceSceneCode: 'HF_SCENE_HOME',
    sourceModuleCode: 'HF_HOME_GOODS',
    linkedActivityType: 'FIRST_ORDER',
    reviewBy: 'hf_dist_reviewer',
    reviewRemark: '首单与分享转化达标，升级一级分销员',
  },
  {
    memberId: 'hf-member-regular-16',
    fromLevel: 0,
    toLevel: 1,
    applyType: 'PRODUCT_PURCHASE',
    orderId: 'hf-order-048',
    orderSn: 'HF-ORDER-048',
    evidenceScenarioType: 'member-upgrade',
    status: 'APPROVED',
    sourceSceneCode: 'HF_SCENE_HOME',
    sourceModuleCode: 'HF_HOME_GOODS',
    linkedActivityType: 'MEMBER_UPGRADE',
    reviewBy: 'hf_dist_reviewer',
    reviewRemark: '升级权益包核验通过，升级一级分销员',
  },
  {
    memberId: 'hf-member-l1-08',
    fromLevel: 1,
    toLevel: 2,
    applyType: 'PRODUCT_PURCHASE',
    orderId: 'hf-order-051',
    orderSn: 'HF-ORDER-051',
    evidenceScenarioType: 'service-normal',
    status: 'PENDING',
    sourceSceneCode: 'HF_SCENE_COURSE',
    sourceModuleCode: 'HF_COURSE_RECOMMEND',
    linkedActivityType: 'SERVICE_THRESHOLD',
  },
  {
    memberId: 'hf-black-02',
    fromLevel: 0,
    toLevel: 1,
    applyType: 'PRODUCT_PURCHASE',
    orderId: 'hf-order-050',
    orderSn: 'HF-ORDER-050',
    evidenceScenarioType: 'product-normal',
    status: 'REJECTED',
    sourceSceneCode: 'HF_SCENE_HOME',
    sourceModuleCode: 'HF_HOME_INSTANT',
    linkedActivityType: 'RISK_CONTROL',
    reviewBy: 'hf_dist_reviewer',
    reviewRemark: '命中黑名单风控，升级申请驳回',
  },
];

export const HUNAN_FULL_BLACKLIST_MEMBER_IDS = ['hf-black-01', 'hf-black-02'];

export const HUNAN_FULL_MEMBER_PASSWORD = HUNAN_FULL_MEMBER_PASSWORD_HASH;
