import type {
  HunanActivityBlueprint,
  HunanActivityTouchpointBlueprint,
  HunanCouponTemplateBlueprint,
  HunanPolicyBlueprint,
  HunanSceneBlueprint,
  HunanSceneModuleBlueprint,
  HunanStorePlayConfigBlueprint,
} from './types';

export const HUNAN_FULL_MARKETING_BLUEPRINT: {
  pointsRule: {
    orderPointsEnabled: boolean;
    orderPointsRatio: number;
    orderPointsBase: number;
    signinPointsEnabled: boolean;
    signinPointsAmount: number;
    pointsValidityEnabled: boolean;
    pointsValidityDays: number | null;
    pointsRedemptionEnabled: boolean;
    pointsRedemptionRatio: number;
    pointsRedemptionBase: number;
    maxPointsPerOrder: number;
    maxDiscountPercentOrder: number;
    systemEnabled: boolean;
  };
  distReviewConfig: {
    enableAutoReview: boolean;
    minRegisterDays: number;
    minOrderCount: number;
    minOrderAmount: number;
    requireRealName: boolean;
    requirePhone: boolean;
  };
  couponTemplates: HunanCouponTemplateBlueprint[];
  activities: HunanActivityBlueprint[];
  activityTouchpoints: HunanActivityTouchpointBlueprint[];
  storePlayConfigs: HunanStorePlayConfigBlueprint[];
  policies: HunanPolicyBlueprint[];
  scenes: HunanSceneBlueprint[];
  sceneModules: HunanSceneModuleBlueprint[];
  activityPriorityRules: Array<{
    activityType: string;
    priority: number;
    aggregateEnabled: boolean;
    zoneEnabled: boolean;
    manualLockEnabled: boolean;
  }>;
} = {
  pointsRule: {
    orderPointsEnabled: true,
    orderPointsRatio: 1,
    orderPointsBase: 1,
    signinPointsEnabled: true,
    signinPointsAmount: 12,
    pointsValidityEnabled: false,
    pointsValidityDays: null,
    pointsRedemptionEnabled: true,
    pointsRedemptionRatio: 100,
    pointsRedemptionBase: 1,
    maxPointsPerOrder: 8000,
    maxDiscountPercentOrder: 40,
    systemEnabled: true,
  },
  distReviewConfig: {
    enableAutoReview: false,
    minRegisterDays: 7,
    minOrderCount: 2,
    minOrderAmount: 199,
    requireRealName: false,
    requirePhone: true,
  },
  couponTemplates: [
    {
      code: 'HF-CPN-NEW-20',
      name: '新人满100减20',
      description: '新人专区基础券',
      type: 'DISCOUNT',
      discountAmount: 20,
      minOrderAmount: 100,
      validityType: 'FIXED',
      applicableProducts: [],
      applicableCategories: [101, 103, 41, 43],
      memberLevels: [],
      totalStock: 2000,
      limitPerUser: 1,
    },
    {
      code: 'HF-CPN-NEW-40',
      name: '新人满200减40',
      description: '新人高客单商品券',
      type: 'DISCOUNT',
      discountAmount: 40,
      minOrderAmount: 200,
      validityType: 'FIXED',
      applicableProducts: [],
      applicableCategories: [104, 42],
      memberLevels: [],
      totalStock: 1000,
      limitPerUser: 1,
    },
    {
      code: 'HF-CPN-ALL-90',
      name: '全场9折券',
      description: '普通折扣券',
      type: 'PERCENTAGE',
      discountPercent: 90,
      maxDiscountAmount: 50,
      minOrderAmount: 0,
      validityType: 'RELATIVE',
      validDays: 15,
      applicableProducts: [],
      applicableCategories: [],
      memberLevels: [],
      totalStock: 1500,
      limitPerUser: 2,
    },
    {
      code: 'HF-CPN-COURSE-120',
      name: '课程满999减120',
      description: '课程服务券',
      type: 'DISCOUNT',
      discountAmount: 120,
      minOrderAmount: 999,
      validityType: 'FIXED',
      applicableProducts: ['hf-service-art-001', 'hf-service-basketball-001', 'hf-service-english-001'],
      applicableCategories: [201, 202, 203],
      memberLevels: [],
      totalStock: 600,
      limitPerUser: 1,
    },
    {
      code: 'HF-CPN-FLASH-10',
      name: '秒杀叠加券10元',
      description: '秒杀专区叠加券',
      type: 'DISCOUNT',
      discountAmount: 10,
      minOrderAmount: 39,
      validityType: 'RELATIVE',
      validDays: 7,
      applicableProducts: ['hf-instant-coconut-water-001', 'hf-instant-fruit-platter-001'],
      applicableCategories: [],
      memberLevels: [],
      totalStock: 1200,
      limitPerUser: 1,
    },
    {
      code: 'HF-CPN-MEMBER-95',
      name: '会员95折券',
      description: '会员等级定向券',
      type: 'PERCENTAGE',
      discountPercent: 95,
      maxDiscountAmount: 80,
      minOrderAmount: 89,
      validityType: 'RELATIVE',
      validDays: 20,
      applicableProducts: [],
      applicableCategories: [],
      memberLevels: [1, 2],
      totalStock: 800,
      limitPerUser: 2,
    },
    {
      code: 'HF-CPN-EXCHANGE-OAT',
      name: '燕麦兑换券',
      description: '兑换燕麦谷物杯',
      type: 'EXCHANGE',
      minOrderAmount: 0,
      validityType: 'RELATIVE',
      validDays: 30,
      applicableProducts: [],
      applicableCategories: [],
      memberLevels: [],
      exchangeProductId: 'hf-retail-oatmeal-001',
      exchangeSkuId: 'hf-retail-oatmeal-001-sku-3',
      totalStock: 300,
      limitPerUser: 1,
    },
    {
      code: 'HF-CPN-EXCHANGE-GRANOLA',
      name: '谷物兑换券',
      description: '兑换谷物燕麦片',
      type: 'EXCHANGE',
      minOrderAmount: 0,
      validityType: 'RELATIVE',
      validDays: 30,
      applicableProducts: [],
      applicableCategories: [],
      memberLevels: [],
      exchangeProductId: 'hf-instant-granola-001',
      exchangeSkuId: 'hf-instant-granola-001-sku-3',
      totalStock: 300,
      limitPerUser: 1,
    },
    {
      code: 'HF-CPN-TEAM-30',
      name: '团购满199减30',
      description: '拼团专区加购券',
      type: 'DISCOUNT',
      discountAmount: 30,
      minOrderAmount: 199,
      validityType: 'FIXED',
      applicableProducts: ['hf-retail-nuts-gift-001', 'hf-instant-fruit-platter-001'],
      applicableCategories: [],
      memberLevels: [],
      totalStock: 500,
      limitPerUser: 1,
    },
    {
      code: 'HF-CPN-SERVICE-EXPR',
      name: '服务预约体验券',
      description: '服务订单体验券',
      type: 'DISCOUNT',
      discountAmount: 60,
      minOrderAmount: 399,
      validityType: 'FIXED',
      applicableProducts: ['hf-service-swimming-001', 'hf-service-spoken-001'],
      applicableCategories: [],
      memberLevels: [],
      totalStock: 500,
      limitPerUser: 1,
    },
  ],
  activities: [
    {
      type: 'NEWCOMER_EXCLUSIVE',
      name: '新人专享首单礼',
      description: '新人价与新人券联动活动',
      triggerCondition: {
        memberTags: ['newcomer'],
        ownerUserId: 'hf_marketing_ops',
        referralRule: {
          referralCodeRequired: false,
          source: 'NEWCOMER_SHARE_HOME',
          bindOnFirstVisit: true,
        },
      },
      rules: {
        newcomerProductIds: ['hf-retail-cleaner-001', 'hf-instant-coconut-water-001'],
        failurePolicy: 'REFUND',
        commissionEnabled: true,
        commissionRate: 0.03,
        leaderMode: 'QUALIFIED_ONLY',
        allowQualifiedUserOpen: true,
        allowStaffProxyOpen: false,
        lastPublishTime: '2026-04-10T09:30:00+08:00',
        sceneBindings: [
          {
            sceneCode: 'HF_SCENE_NEWCOMER',
            sceneName: '新人专区',
            moduleCode: 'HF_NEWCOMER_PRICE',
            moduleName: '新人专享价',
            channelScope: ['miniapp'],
            pageRoute: '/pages/marketing/newcomer',
            placement: '新人专区首屏商品位',
          },
          {
            sceneCode: 'HF_SCENE_HOME',
            sceneName: '湖南首页推荐',
            moduleCode: 'HF_HOME_GOODS',
            moduleName: '首页零售推荐',
            channelScope: ['miniapp', 'admin-preview'],
            pageRoute: '/pages/index/index',
            placement: '首页新人可见商品位',
          },
        ],
        activityItems: [
          {
            id: 'newcomer-cleaner-500ml',
            itemType: 'PRODUCT',
            itemCode: 'hf-retail-cleaner-001',
            itemName: '净润多效厨房清洁剂',
            enabled: true,
            sort: 1,
            config: {
              productId: 'hf-retail-cleaner-001',
              skuId: 'hf-retail-cleaner-001-sku-1',
              productName: '净润多效厨房清洁剂',
              skuName: '500ml / 青柠',
              originPrice: 23.9,
              activityPrice: 19.9,
              displayTag: '新人价',
            },
            ext: { stockLimit: 180, limitPerUser: 1 },
          },
          {
            id: 'newcomer-coconut-6',
            itemType: 'PRODUCT',
            itemCode: 'hf-instant-coconut-water-001',
            itemName: '100%椰子水组合装',
            enabled: true,
            sort: 2,
            config: {
              productId: 'hf-instant-coconut-water-001',
              skuId: 'hf-instant-coconut-water-001-sku-1',
              productName: '100%椰子水组合装',
              skuName: '350ml*6瓶 / 原味',
              originPrice: 39.9,
              activityPrice: 29.9,
              displayTag: '首单特价',
            },
            ext: { stockLimit: 130, limitPerUser: 1 },
          },
        ],
        distributionGrowth: {
          activityVersionId: 'NEWCOMER_EXCLUSIVE_202604',
          shareChannel: 'MINIAPP',
          shareLandingPage: '/pages/marketing/newcomer',
          referralCodeEnabled: true,
          attributionWindowMinutes: 4320,
          commissionBudgetTotal: 1200000,
          commissionBudgetAlertThreshold: 70,
          commissionBudgetFuseThreshold: 90,
          upgradeRule: {
            trigger: 'FIRST_ORDER_PAID',
            targetLevels: [1],
            autoApprove: true,
          },
          teamThresholdRule: {
            minReferralOrders: 2,
            minPaidAmount: 19900,
            settlementWindowDays: 30,
          },
        },
      },
      rewards: {
        couponCodes: ['HF-CPN-NEW-20', 'HF-CPN-NEW-40'],
        commissionBudgetSnapshot: {
          budgetTotal: 1200000,
          budgetFrozen: 180000,
          budgetConsumed: 320000,
          budgetReleased: 700000,
          budgetByLevel: { L1: 260000, L2: 60000 },
          budgetByChannel: { MINIAPP: 270000, H5: 50000 },
          budgetByActivityVersion: { NEWCOMER_EXCLUSIVE_202604: 320000 },
          budgetAlertThreshold: 70,
          budgetFuseThreshold: 90,
        },
      },
      isEnabled: true,
      priority: 100,
      startOffsetDays: -7,
      endOffsetDays: 20,
    },
    {
      type: 'FIRST_ORDER',
      name: '首单加赠积分',
      description: '首单额外赠送积分',
      triggerCondition: {
        orderCountBefore: 0,
        ownerUserId: 'hf_marketing_ops',
      },
      rules: {
        minAmount: 49,
        failurePolicy: 'REFUND',
        commissionEnabled: false,
        commissionRate: 0,
        leaderMode: 'QUALIFIED_ONLY',
        allowQualifiedUserOpen: true,
        allowStaffProxyOpen: false,
        lastPublishTime: '2026-04-14T09:30:00+08:00',
        sceneBindings: [
          {
            sceneCode: 'HF_SCENE_HOME',
            sceneName: '湖南首页推荐',
            moduleCode: 'HF_HOME_INSTANT',
            moduleName: '首页即时零售',
            channelScope: ['miniapp', 'admin-preview'],
            pageRoute: '/pages/index/index',
            placement: '首页新客首单提醒位',
          },
        ],
        activityItems: [
          {
            id: 'first-order-coconut-12',
            itemType: 'PRODUCT',
            itemCode: 'hf-instant-coconut-water-001',
            itemName: '100%椰子水组合装',
            enabled: true,
            sort: 1,
            config: {
              productId: 'hf-instant-coconut-water-001',
              skuId: 'hf-instant-coconut-water-001-sku-2',
              productName: '100%椰子水组合装',
              skuName: '350ml*12瓶 / 原味',
              originPrice: 72,
              activityPrice: 68,
              displayTag: '首单积分',
            },
            ext: { minAmount: 49, extraPoints: 120 },
          },
        ],
      },
      rewards: {
        extraPoints: 120,
        pointsTaskCode: 'FIRST_ORDER_POINTS_TASK',
      },
      isEnabled: true,
      priority: 90,
      startOffsetDays: -3,
      endOffsetDays: 30,
    },
    {
      type: 'FULL_REDUCTION',
      name: '周末满减狂欢',
      description: '全场满减活动',
      triggerCondition: {
        weekday: ['SAT', 'SUN'],
        ownerUserId: 'hf_product_ops',
      },
      rules: {
        tiers: [
          { full: 99, reduce: 15 },
          { full: 199, reduce: 40 },
        ],
        failurePolicy: 'REFUND',
        commissionEnabled: false,
        commissionRate: 0,
        leaderMode: 'QUALIFIED_ONLY',
        allowQualifiedUserOpen: true,
        allowStaffProxyOpen: false,
        lastPublishTime: '2026-04-15T09:30:00+08:00',
        sceneBindings: [
          {
            sceneCode: 'HF_SCENE_HOME',
            sceneName: '湖南首页推荐',
            moduleCode: 'HF_HOME_GOODS',
            moduleName: '首页零售推荐',
            channelScope: ['miniapp', 'admin-preview'],
            pageRoute: '/pages/index/index',
            placement: '首页周末满减活动位',
          },
          {
            sceneCode: 'HF_SCENE_FLASH',
            sceneName: '秒杀专区',
            moduleCode: 'HF_FLASH_BUNDLE',
            moduleName: '秒杀加购推荐',
            channelScope: ['miniapp'],
            pageRoute: '/pages/marketing/flash',
            placement: '秒杀加购推荐位',
          },
        ],
        activityItems: [
          {
            id: 'full-reduction-nuts-24',
            itemType: 'PRODUCT',
            itemCode: 'hf-retail-nuts-gift-001',
            itemName: '每日坚果分享礼盒',
            enabled: true,
            sort: 1,
            config: {
              productId: 'hf-retail-nuts-gift-001',
              skuId: 'hf-retail-nuts-gift-001-sku-2',
              productName: '每日坚果分享礼盒',
              skuName: '24包 / 经典',
              originPrice: 99,
              activityPrice: 92,
              displayTag: '满199减40',
            },
            ext: { fullReductionTier: '199-40' },
          },
          {
            id: 'full-reduction-platter-4',
            itemType: 'PRODUCT',
            itemCode: 'hf-instant-fruit-platter-001',
            itemName: '聚会鲜切果盘',
            enabled: true,
            sort: 2,
            config: {
              productId: 'hf-instant-fruit-platter-001',
              skuId: 'hf-instant-fruit-platter-001-sku-2',
              productName: '聚会鲜切果盘',
              skuName: '四人装',
              originPrice: 58.9,
              activityPrice: 55.9,
              displayTag: '满99减15',
            },
            ext: { fullReductionTier: '99-15' },
          },
        ],
      },
      rewards: { stackable: false },
      isEnabled: true,
      priority: 80,
      startOffsetDays: -2,
      endOffsetDays: 40,
    },
    {
      type: 'MEMBER_DAY',
      name: '会员日专享',
      description: '会员等级定向活动',
      triggerCondition: {
        memberLevels: [1, 2],
        ownerUserId: 'hf_marketing_ops',
      },
      rules: {
        discountPercent: 95,
        failurePolicy: 'REFUND',
        commissionEnabled: false,
        commissionRate: 0,
        leaderMode: 'QUALIFIED_ONLY',
        allowQualifiedUserOpen: true,
        allowStaffProxyOpen: false,
        lastPublishTime: '2026-04-01T09:30:00+08:00',
        sceneBindings: [
          {
            sceneCode: 'HF_SCENE_HOME',
            sceneName: '湖南首页推荐',
            moduleCode: 'HF_HOME_GOODS',
            moduleName: '首页零售推荐',
            channelScope: ['miniapp', 'admin-preview'],
            pageRoute: '/pages/index/index',
            placement: '会员日专享权益位',
          },
        ],
        activityItems: [
          {
            id: 'member-day-nuts-gift',
            itemType: 'PRODUCT',
            itemCode: 'hf-retail-nuts-gift-001',
            itemName: '每日坚果分享礼盒',
            enabled: true,
            sort: 1,
            config: {
              productId: 'hf-retail-nuts-gift-001',
              skuId: 'hf-retail-nuts-gift-001-sku-3',
              productName: '每日坚果分享礼盒',
              skuName: '节礼盒 / 低糖',
              originPrice: 129,
              activityPrice: 118,
              displayTag: '会员95折券',
            },
            ext: { memberLevels: [1, 2] },
          },
        ],
      },
      rewards: { couponCode: 'HF-CPN-MEMBER-95' },
      isEnabled: true,
      priority: 70,
      startOffsetDays: -15,
      endOffsetDays: -1,
    },
    {
      type: 'GROUP_BUY',
      name: '礼盒拼团季',
      description: '礼盒与果盘拼团活动',
      triggerCondition: {
        products: ['hf-retail-nuts-gift-001', 'hf-instant-fruit-platter-001'],
        ownerUserId: 'hf_store_manager',
        referralRule: {
          referralCodeRequired: true,
          source: 'GROUP_BUY_INVITE',
          bindOnShareOpen: true,
        },
      },
      rules: {
        groupSize: 3,
        groupPriceRate: 0.85,
        failurePolicy: 'REFUND',
        commissionEnabled: true,
        commissionRate: 0.08,
        leaderMode: 'QUALIFIED_ONLY',
        allowQualifiedUserOpen: true,
        allowStaffProxyOpen: true,
        lastPublishTime: '2026-04-18T09:30:00+08:00',
        sceneBindings: [
          {
            sceneCode: 'HF_SCENE_HOME',
            sceneName: '湖南首页推荐',
            moduleCode: 'HF_HOME_GOODS',
            moduleName: '首页零售推荐',
            channelScope: ['miniapp', 'admin-preview'],
            pageRoute: '/pages/index/index',
            placement: '首页拼团活动位',
          },
          {
            sceneCode: 'HF_SCENE_FLASH',
            sceneName: '秒杀专区',
            moduleCode: 'HF_FLASH_BUNDLE',
            moduleName: '秒杀加购推荐',
            channelScope: ['miniapp'],
            pageRoute: '/pages/marketing/flash',
            placement: '秒杀加购拼团位',
          },
        ],
        activityItems: [
          {
            id: 'group-buy-nuts-gift',
            itemType: 'PRODUCT',
            itemCode: 'hf-retail-nuts-gift-001',
            itemName: '每日坚果分享礼盒',
            enabled: true,
            sort: 1,
            config: {
              productId: 'hf-retail-nuts-gift-001',
              skuId: 'hf-retail-nuts-gift-001-sku-3',
              productName: '每日坚果分享礼盒',
              skuName: '节礼盒 / 低糖',
              originPrice: 129,
              activityPrice: 109,
              displayTag: '3人成团',
            },
            ext: { groupSize: 3, leaderBonusCoupon: 'HF-CPN-TEAM-30' },
          },
          {
            id: 'group-buy-platter',
            itemType: 'PRODUCT',
            itemCode: 'hf-instant-fruit-platter-001',
            itemName: '聚会鲜切果盘',
            enabled: true,
            sort: 2,
            config: {
              productId: 'hf-instant-fruit-platter-001',
              skuId: 'hf-instant-fruit-platter-001-sku-3',
              productName: '聚会鲜切果盘',
              skuName: '礼赠装',
              originPrice: 79.9,
              activityPrice: 67.9,
              displayTag: '拼团价',
            },
            ext: { groupSize: 3, leaderBonusCoupon: 'HF-CPN-TEAM-30' },
          },
        ],
        distributionGrowth: {
          activityVersionId: 'GROUP_BUY_202604',
          shareChannel: 'H5',
          shareLandingPage: '/pages/course-group/index',
          referralCodeEnabled: true,
          attributionWindowMinutes: 2160,
          commissionBudgetTotal: 1800000,
          commissionBudgetAlertThreshold: 75,
          commissionBudgetFuseThreshold: 92,
          upgradeRule: {
            trigger: 'GROUP_SUCCESS',
            targetLevels: [1, 2],
            minLeaderSuccessCount: 2,
          },
          teamThresholdRule: {
            minGroupCount: 3,
            minPaidAmount: 59900,
            settlementWindowDays: 14,
          },
        },
      },
      rewards: {
        leaderBonusCoupon: 'HF-CPN-TEAM-30',
        commissionBudgetSnapshot: {
          budgetTotal: 1800000,
          budgetFrozen: 260000,
          budgetConsumed: 480000,
          budgetReleased: 1060000,
          budgetByLevel: { L1: 360000, L2: 120000 },
          budgetByChannel: { H5: 310000, MINIAPP: 170000 },
          budgetByActivityVersion: { GROUP_BUY_202604: 480000 },
          budgetAlertThreshold: 75,
          budgetFuseThreshold: 92,
        },
      },
      isEnabled: true,
      priority: 60,
      startOffsetDays: 1,
      endOffsetDays: 35,
    },
    {
      type: 'FLASH_SALE',
      name: '爆款秒杀周',
      description: '秒杀专区演示活动',
      triggerCondition: {
        sceneCode: 'HF_SCENE_FLASH',
        ownerUserId: 'hf_product_ops',
      },
      rules: {
        products: ['hf-instant-coconut-water-001', 'hf-instant-fruit-platter-001'],
        failurePolicy: 'REFUND',
        commissionEnabled: false,
        commissionRate: 0,
        leaderMode: 'QUALIFIED_ONLY',
        allowQualifiedUserOpen: false,
        allowStaffProxyOpen: true,
        lastPublishTime: '2026-04-16T09:30:00+08:00',
        sceneBindings: [
          {
            sceneCode: 'HF_SCENE_FLASH',
            sceneName: '秒杀专区',
            moduleCode: 'HF_FLASH_TODAY',
            moduleName: '今日秒杀',
            channelScope: ['miniapp'],
            pageRoute: '/pages/marketing/flash',
            placement: '秒杀专区主活动位',
          },
          {
            sceneCode: 'HF_SCENE_HOME',
            sceneName: '湖南首页推荐',
            moduleCode: 'HF_HOME_INSTANT',
            moduleName: '首页即时零售',
            channelScope: ['miniapp', 'admin-preview'],
            pageRoute: '/pages/index/index',
            placement: '首页今日即达秒杀位',
          },
        ],
        activityItems: [
          {
            id: 'flash-coconut-6',
            itemType: 'PRODUCT',
            itemCode: 'hf-instant-coconut-water-001',
            itemName: '100%椰子水组合装',
            enabled: true,
            sort: 1,
            config: {
              productId: 'hf-instant-coconut-water-001',
              skuId: 'hf-instant-coconut-water-001-sku-1',
              productName: '100%椰子水组合装',
              skuName: '350ml*6瓶 / 原味',
              originPrice: 39.9,
              activityPrice: 29.9,
              displayTag: '限时秒杀',
            },
            ext: { stockMode: 'STRONG_LOCK', stockLimit: 180, limitPerUser: 2 },
          },
          {
            id: 'flash-platter-2',
            itemType: 'PRODUCT',
            itemCode: 'hf-instant-fruit-platter-001',
            itemName: '聚会鲜切果盘',
            enabled: true,
            sort: 2,
            config: {
              productId: 'hf-instant-fruit-platter-001',
              skuId: 'hf-instant-fruit-platter-001-sku-1',
              productName: '聚会鲜切果盘',
              skuName: '双人装',
              originPrice: 36.9,
              activityPrice: 29.9,
              displayTag: '夜场秒杀',
            },
            ext: { stockMode: 'STRONG_LOCK', stockLimit: 60, limitPerUser: 1 },
          },
        ],
      },
      rewards: { displayBadge: '秒杀' },
      isEnabled: true,
      priority: 95,
      startOffsetDays: -5,
      endOffsetDays: 45,
    },
    {
      type: 'COURSE_GROUP',
      name: '课程拼课月',
      description: '艺术体育课程拼课招募',
      triggerCondition: {
        categories: [201, 202, 203],
        ownerUserId: 'hf_store_manager',
        referralRule: {
          referralCodeRequired: true,
          source: 'COURSE_GROUP_SHARE',
          bindOnShareOpen: true,
        },
      },
      rules: {
        minCount: 2,
        maxCount: 8,
        failurePolicy: 'TRANSFER',
        commissionEnabled: true,
        commissionRate: 0.06,
        leaderMode: 'STAFF_PRIORITY',
        allowQualifiedUserOpen: true,
        allowStaffProxyOpen: true,
        lastPublishTime: '2026-04-22T09:30:00+08:00',
        sceneBindings: [
          {
            sceneCode: 'HF_SCENE_COURSE',
            sceneName: '课程专区',
            moduleCode: 'HF_COURSE_GROUP',
            moduleName: '课程拼课',
            channelScope: ['miniapp', 'admin-preview'],
            pageRoute: '/pages/course-group/index',
            placement: '课程专区热门拼课',
          },
          {
            sceneCode: 'HF_SCENE_COURSE',
            sceneName: '课程专区',
            moduleCode: 'HF_COURSE_RECOMMEND',
            moduleName: '课程推荐',
            channelScope: ['miniapp', 'admin-preview'],
            pageRoute: '/pages/course-group/index',
            placement: '课程推荐联动位',
          },
        ],
        activityItems: [
          {
            id: 'course-group-art-8',
            itemType: 'SERVICE',
            itemCode: 'hf-service-art-001',
            itemName: '少儿创意绘画启蒙',
            enabled: true,
            sort: 1,
            config: {
              productId: 'hf-service-art-001',
              skuId: 'hf-service-art-001-sku-1',
              productName: '少儿创意绘画启蒙',
              skuName: '小班 / 8课时',
              originPrice: 980,
              activityPrice: 799,
              displayTag: '拼课价',
            },
            ext: { minCount: 2, maxCount: 8, classAddress: '长沙市岳麓区体验教室A1' },
          },
          {
            id: 'course-group-basketball-10',
            itemType: 'SERVICE',
            itemCode: 'hf-service-basketball-001',
            itemName: '篮球体能训练营',
            enabled: true,
            sort: 2,
            config: {
              productId: 'hf-service-basketball-001',
              skuId: 'hf-service-basketball-001-sku-1',
              productName: '篮球体能训练营',
              skuName: '周末班 / 10课时',
              originPrice: 1280,
              activityPrice: 1099,
              displayTag: '3人成团',
            },
            ext: { minCount: 3, maxCount: 10, classAddress: '长沙市天心区篮球馆B2' },
          },
        ],
        distributionGrowth: {
          activityVersionId: 'COURSE_GROUP_202604',
          shareChannel: 'MINIAPP',
          shareLandingPage: '/pages/course-group/index',
          referralCodeEnabled: true,
          attributionWindowMinutes: 10080,
          commissionBudgetTotal: 2400000,
          commissionBudgetAlertThreshold: 70,
          commissionBudgetFuseThreshold: 90,
          upgradeRule: {
            trigger: 'COURSE_GROUP_SUCCESS',
            targetLevels: [1, 2],
            minCourseOrders: 1,
          },
          teamThresholdRule: {
            minGroupCount: 2,
            minPaidAmount: 159800,
            settlementWindowDays: 30,
          },
        },
      },
      rewards: {
        leaderDiscount: 100,
        commissionBudgetSnapshot: {
          budgetTotal: 2400000,
          budgetFrozen: 300000,
          budgetConsumed: 620000,
          budgetReleased: 1480000,
          budgetByLevel: { L1: 470000, L2: 150000 },
          budgetByChannel: { MINIAPP: 620000 },
          budgetByActivityVersion: { COURSE_GROUP_202604: 620000 },
          budgetAlertThreshold: 70,
          budgetFuseThreshold: 90,
        },
      },
      isEnabled: true,
      priority: 75,
      startOffsetDays: -10,
      endOffsetDays: 60,
    },
    {
      type: 'MEMBER_UPGRADE',
      name: '会员升级月',
      description: '会员升级活动与升级申请联动',
      triggerCondition: {
        memberLevels: [0, 1],
        ownerUserId: 'hf_dist_reviewer',
        referralRule: {
          referralCodeRequired: true,
          source: 'MEMBER_UPGRADE_REFERRAL',
          bindOnApplication: true,
        },
      },
      rules: {
        targetLevels: [1, 2],
        failurePolicy: 'MANUAL',
        commissionEnabled: true,
        commissionRate: 0.05,
        leaderMode: 'QUALIFIED_ONLY',
        allowQualifiedUserOpen: true,
        allowStaffProxyOpen: true,
        lastPublishTime: '2026-04-08T09:30:00+08:00',
        sceneBindings: [
          {
            sceneCode: 'HF_SCENE_COURSE',
            sceneName: '课程专区',
            moduleCode: 'HF_COURSE_RECOMMEND',
            moduleName: '课程推荐',
            channelScope: ['miniapp', 'admin-preview'],
            pageRoute: '/pages/course-group/index',
            placement: '课程推荐升级权益位',
          },
          {
            sceneCode: 'HF_SCENE_NEWCOMER',
            sceneName: '新人专区',
            moduleCode: 'HF_NEWCOMER_COUPON',
            moduleName: '新人权益卡',
            channelScope: ['miniapp'],
            pageRoute: '/pages/marketing/newcomer',
            placement: '新人权益升级提醒',
          },
        ],
        activityItems: [
          {
            id: 'member-upgrade-scratch',
            itemType: 'SERVICE',
            itemCode: 'hf-service-scratch-001',
            itemName: 'Scratch 创意编程营',
            enabled: true,
            sort: 1,
            config: {
              productId: 'hf-service-scratch-001',
              skuId: 'hf-service-scratch-001-sku-1',
              productName: 'Scratch 创意编程营',
              skuName: '小班 / 12课时',
              originPrice: 1680,
              activityPrice: 399,
              displayTag: '成长会员升级包',
            },
            ext: { targetLevel: 1, autoApprove: true },
          },
          {
            id: 'member-upgrade-math',
            itemType: 'SERVICE',
            itemCode: 'hf-service-math-001',
            itemName: '数学思维突破课',
            enabled: true,
            sort: 2,
            config: {
              productId: 'hf-service-math-001',
              skuId: 'hf-service-math-001-sku-1',
              productName: '数学思维突破课',
              skuName: '小班 / 16课时',
              originPrice: 1880,
              activityPrice: 899,
              displayTag: '合伙人升级包',
            },
            ext: { targetLevel: 2, autoApprove: false },
          },
        ],
        distributionGrowth: {
          activityVersionId: 'MEMBER_UPGRADE_202604',
          shareChannel: 'APP',
          shareLandingPage: '/pages/member/upgrade',
          referralCodeEnabled: true,
          attributionWindowMinutes: 1440,
          commissionBudgetTotal: 1500000,
          commissionBudgetAlertThreshold: 75,
          commissionBudgetFuseThreshold: 95,
          upgradeRule: {
            trigger: 'UPGRADE_APPLICATION_APPROVED',
            targetLevels: [1, 2],
            evidenceTypes: ['PRODUCT_PURCHASE', 'REFERRAL_CODE'],
          },
          teamThresholdRule: {
            minApprovedApplications: 2,
            minReferralOrders: 1,
            settlementWindowDays: 30,
          },
        },
      },
      rewards: {
        couponCode: 'HF-CPN-SERVICE-EXPR',
        commissionBudgetSnapshot: {
          budgetTotal: 1500000,
          budgetFrozen: 120000,
          budgetConsumed: 360000,
          budgetReleased: 1020000,
          budgetByLevel: { L1: 220000, L2: 140000 },
          budgetByChannel: { APP: 360000 },
          budgetByActivityVersion: { MEMBER_UPGRADE_202604: 360000 },
          budgetAlertThreshold: 75,
          budgetFuseThreshold: 95,
        },
      },
      isEnabled: true,
      priority: 65,
      startOffsetDays: -10,
      endOffsetDays: 60,
    },
  ],
  activityTouchpoints: [
    {
      activityType: 'NEWCOMER_EXCLUSIVE',
      kind: 'MESSAGE',
      code: 'NEWCOMER_WELCOME_V1',
      name: '新人首单欢迎通知',
      isEnabled: true,
      config: {
        triggerMoment: 'INSTANCE_SUCCESS',
        channels: ['IN_APP', 'APP_PUSH'],
        templateCode: 'HF_MKT_NEWCOMER_SUCCESS_V1',
        templateVersion: 'v1',
        consentRequired: true,
        quietHours: { start: '22:00', end: '08:00', timezone: 'Asia/Shanghai' },
        frequencyLimit: { perUserPerDay: 1, perActivityPerDay: 4 },
      },
    },
    {
      activityType: 'NEWCOMER_EXCLUSIVE',
      kind: 'SHARE',
      code: 'NEWCOMER_SHARE_HOME',
      name: '新人活动分享卡',
      isEnabled: true,
      config: {
        shareChannels: ['MINIAPP', 'H5'],
        landingPagePath: '/pages/marketing/newcomer',
        attributionWindowMinutes: 4320,
        bindingMode: 'RECOMMEND_CODE',
        frequencyLimit: { perUserPerDay: 5, perActivityPerDay: 100 },
        suppressions: ['BLACKLIST_MEMBER', 'MARKETING_BAN'],
      },
    },
    {
      activityType: 'FIRST_ORDER',
      kind: 'MESSAGE',
      code: 'FIRST_ORDER_POINTS_V1',
      name: '首单积分到账通知',
      isEnabled: true,
      config: {
        triggerMoment: 'INSTANCE_SUCCESS',
        channels: ['IN_APP', 'SMS'],
        templateCode: 'HF_MKT_FIRST_ORDER_POINTS_V1',
        templateVersion: 'v1',
        consentRequired: false,
        quietHours: { start: '23:00', end: '07:00', timezone: 'Asia/Shanghai' },
        frequencyLimit: { perUserPerDay: 1, perActivityPerDay: 3 },
      },
    },
    {
      activityType: 'FULL_REDUCTION',
      kind: 'MESSAGE',
      code: 'FULL_REDUCTION_REMINDER',
      name: '满减活动提醒',
      isEnabled: true,
      config: {
        triggerMoment: 'INSTANCE_CREATED',
        channels: ['IN_APP'],
        templateCode: 'HF_MKT_FULL_REDUCTION_REMINDER_V1',
        templateVersion: 'v1',
        consentRequired: true,
        frequencyLimit: { perUserPerDay: 2, perActivityPerDay: 8 },
      },
    },
    {
      activityType: 'FULL_REDUCTION',
      kind: 'SHARE',
      code: 'FULL_REDUCTION_SHARE',
      name: '满减活动分享卡',
      isEnabled: true,
      config: {
        shareChannels: ['MINIAPP', 'APP'],
        landingPagePath: '/pages/marketing/full-reduction',
        attributionWindowMinutes: 2880,
        bindingMode: 'RELATION',
        frequencyLimit: { perUserPerDay: 8, perActivityPerDay: 200 },
        suppressions: ['RISK_CONTROL_BLOCK'],
      },
    },
    {
      activityType: 'MEMBER_DAY',
      kind: 'MESSAGE',
      code: 'MEMBER_DAY_NOTICE',
      name: '会员日提醒',
      isEnabled: false,
      config: {
        triggerMoment: 'INSTANCE_CREATED',
        channels: ['IN_APP', 'WECHAT_TEMPLATE'],
        templateCode: 'HF_MKT_MEMBER_DAY_NOTICE_V1',
        templateVersion: 'v2',
        consentRequired: true,
        quietHours: { start: '22:30', end: '08:30', timezone: 'Asia/Shanghai' },
        frequencyLimit: { perUserPerDay: 1, perActivityPerDay: 2 },
      },
    },
    {
      activityType: 'GROUP_BUY',
      kind: 'MESSAGE',
      code: 'GROUP_BUY_PROGRESS',
      name: '拼团进度通知',
      isEnabled: true,
      config: {
        triggerMoment: 'INSTANCE_ACTIVE',
        channels: ['IN_APP', 'APP_PUSH'],
        templateCode: 'HF_MKT_GROUP_BUY_PROGRESS_V1',
        templateVersion: 'v1',
        consentRequired: false,
        frequencyLimit: { perUserPerDay: 3, perActivityPerDay: 12 },
      },
    },
    {
      activityType: 'GROUP_BUY',
      kind: 'SHARE',
      code: 'GROUP_BUY_INVITE',
      name: '拼团拉新分享',
      isEnabled: true,
      config: {
        shareChannels: ['MINIAPP', 'H5', 'APP'],
        landingPagePath: '/pages/course-group/index',
        attributionWindowMinutes: 2160,
        bindingMode: 'BOTH',
        frequencyLimit: { perUserPerDay: 10, perActivityPerDay: 300 },
      },
    },
    {
      activityType: 'FLASH_SALE',
      kind: 'MESSAGE',
      code: 'FLASH_SALE_STOCK_ALERT',
      name: '秒杀库存预警',
      isEnabled: true,
      config: {
        triggerMoment: 'INSTANCE_ACTIVE',
        channels: ['IN_APP', 'APP_PUSH', 'SMS'],
        templateCode: 'HF_MKT_FLASH_STOCK_ALERT_V1',
        templateVersion: 'v1',
        consentRequired: true,
        quietHours: { start: '23:00', end: '08:00', timezone: 'Asia/Shanghai' },
        frequencyLimit: { perUserPerDay: 2, perActivityPerDay: 10 },
      },
    },
    {
      activityType: 'FLASH_SALE',
      kind: 'SHARE',
      code: 'FLASH_SALE_SHARE',
      name: '秒杀专区分享',
      isEnabled: true,
      config: {
        shareChannels: ['MINIAPP'],
        landingPagePath: '/pages/marketing/flash',
        attributionWindowMinutes: 720,
        bindingMode: 'RECOMMEND_CODE',
        frequencyLimit: { perUserPerDay: 6, perActivityPerDay: 120 },
      },
    },
    {
      activityType: 'COURSE_GROUP',
      kind: 'MESSAGE',
      code: 'COURSE_GROUP_RECRUIT',
      name: '拼课招募通知',
      isEnabled: true,
      config: {
        triggerMoment: 'INSTANCE_CREATED',
        channels: ['IN_APP', 'WECHAT_TEMPLATE'],
        templateCode: 'HF_MKT_COURSE_GROUP_RECRUIT_V1',
        templateVersion: 'v3',
        consentRequired: true,
        frequencyLimit: { perUserPerDay: 1, perActivityPerDay: 6 },
      },
    },
    {
      activityType: 'COURSE_GROUP',
      kind: 'SHARE',
      code: 'COURSE_GROUP_SHARE',
      name: '拼课落地页分享',
      isEnabled: true,
      config: {
        shareChannels: ['MINIAPP', 'H5'],
        landingPagePath: '/pages/course-group/index',
        attributionWindowMinutes: 10080,
        bindingMode: 'BOTH',
        frequencyLimit: { perUserPerDay: 8, perActivityPerDay: 240 },
        suppressions: ['MEMBER_DISABLED', 'ACTIVITY_OFFLINE'],
      },
    },
    {
      activityType: 'MEMBER_UPGRADE',
      kind: 'MESSAGE',
      code: 'MEMBER_UPGRADE_APPROVED',
      name: '升级审核通过通知',
      isEnabled: true,
      config: {
        triggerMoment: 'INSTANCE_SUCCESS',
        channels: ['IN_APP', 'APP_PUSH'],
        templateCode: 'HF_MKT_MEMBER_UPGRADE_APPROVED_V1',
        templateVersion: 'v1',
        consentRequired: true,
        quietHours: { start: '22:00', end: '08:00', timezone: 'Asia/Shanghai' },
        frequencyLimit: { perUserPerDay: 1, perActivityPerDay: 5 },
      },
    },
    {
      activityType: 'MEMBER_UPGRADE',
      kind: 'SHARE',
      code: 'MEMBER_UPGRADE_REFERRAL',
      name: '升级权益分享',
      isEnabled: false,
      config: {
        shareChannels: ['APP'],
        landingPagePath: '/pages/member/upgrade',
        attributionWindowMinutes: 1440,
        bindingMode: 'RELATION',
        frequencyLimit: { perUserPerDay: 2, perActivityPerDay: 20 },
      },
    },
  ],
  storePlayConfigs: [
    {
      configId: 'hf-config-flash-coconut',
      serviceId: 'hf-instant-coconut-water-001',
      serviceType: 'REAL',
      templateCode: 'FLASH_SALE',
      displayPriority: 100,
      scopeType: 'PRODUCT',
      stockMode: 'STRONG_LOCK',
      status: 'ON_SHELF',
      commissionMode: 'NONE',
      commissionRate: null,
      aggregateEnabled: true,
      zoneEnabled: true,
      rules: {
        name: '椰子水限时秒杀',
        flashPrice: 19.9,
        originalPrice: 27.9,
        totalStock: 180,
        limitPerUser: 2,
        startTime: '2026-05-20T10:00:00+08:00',
        endTime: '2026-06-30T23:00:00+08:00',
        skuPrices: {
          'hf-instant-coconut-water-001-sku-3': { flashPrice: 19.9, originalPrice: 27.9 },
        },
      },
    },
    {
      configId: 'hf-config-flash-fruit',
      serviceId: 'hf-instant-fruit-platter-001',
      serviceType: 'REAL',
      templateCode: 'FLASH_SALE',
      displayPriority: 92,
      scopeType: 'PRODUCT',
      stockMode: 'STRONG_LOCK',
      status: 'ON_SHELF',
      commissionMode: 'FIXED_RATE',
      commissionRate: 0,
      aggregateEnabled: true,
      zoneEnabled: true,
      rules: {
        name: '鲜切果盘夜场秒杀',
        flashPrice: 29.9,
        originalPrice: 34.9,
        totalStock: 60,
        limitPerUser: 1,
        startTime: '2026-05-20T18:00:00+08:00',
        endTime: '2026-06-28T23:00:00+08:00',
        skuPrices: {
          'hf-instant-fruit-platter-001-sku-1': { flashPrice: 29.9, originalPrice: 34.9 },
        },
      },
    },
    {
      configId: 'hf-config-flash-cleaner',
      serviceId: 'hf-retail-cleaner-001',
      serviceType: 'REAL',
      templateCode: 'FLASH_SALE',
      displayPriority: 84,
      scopeType: 'PRODUCT',
      stockMode: 'SOFT_LOCK',
      status: 'ON_SHELF',
      commissionMode: 'INHERIT',
      commissionRate: null,
      aggregateEnabled: true,
      zoneEnabled: false,
      rules: {
        name: '厨房清洁补货秒杀',
        flashPrice: 14.9,
        originalPrice: 18.5,
        totalStock: 120,
        limitPerUser: 3,
        startTime: '2026-05-21T08:00:00+08:00',
        endTime: '2026-06-25T23:00:00+08:00',
        skuPrices: {
          'hf-retail-cleaner-001-sku-3': { flashPrice: 14.9, originalPrice: 18.5 },
          'hf-retail-cleaner-001-sku-1': { flashPrice: 17.9, originalPrice: 21.9 },
        },
      },
    },
    {
      configId: 'hf-config-course-art',
      serviceId: 'hf-service-art-001',
      serviceType: 'SERVICE',
      templateCode: 'COURSE_GROUP_BUY',
      displayPriority: 96,
      scopeType: 'PRODUCT',
      stockMode: 'LAZY_CHECK',
      status: 'ON_SHELF',
      commissionMode: 'INHERIT',
      commissionRate: null,
      aggregateEnabled: true,
      zoneEnabled: true,
      rules: {
        name: '创意绘画拼课',
        minCount: 2,
        maxCount: 8,
        price: 799,
        originalPrice: 980,
        joinDeadline: '2026-06-30T20:00:00+08:00',
        classStartTime: '2026-07-05T10:00:00+08:00',
        classAddress: '长沙市岳麓区体验教室A1',
        totalLessons: 8,
        dayLessons: 1,
        storeParticipating: true,
        storeReady: true,
        // 仅「小班 8 课时」SKU 参与拼课；其他规格走普通商品详情展示
        skuPrices: {
          'hf-service-art-001-sku-1': { price: 799, originalPrice: 980, activityPrice: 799 },
        },
      },
    },
    {
      configId: 'hf-config-course-basketball',
      serviceId: 'hf-service-basketball-001',
      serviceType: 'SERVICE',
      templateCode: 'COURSE_GROUP_BUY',
      displayPriority: 88,
      scopeType: 'PRODUCT',
      stockMode: 'LAZY_CHECK',
      status: 'ON_SHELF',
      commissionMode: 'INHERIT',
      commissionRate: null,
      aggregateEnabled: true,
      zoneEnabled: true,
      rules: {
        name: '篮球周末拼课',
        minCount: 3,
        maxCount: 10,
        price: 1099,
        originalPrice: 1280,
        joinDeadline: '2026-06-28T20:00:00+08:00',
        classStartTime: '2026-07-02T15:00:00+08:00',
        classAddress: '长沙市天心区篮球馆B2',
        totalLessons: 10,
        dayLessons: 2,
        storeParticipating: true,
        storeReady: true,
      },
    },
    {
      configId: 'hf-config-course-basketball-delayed',
      serviceId: 'hf-service-basketball-001',
      serviceType: 'SERVICE',
      templateCode: 'COURSE_GROUP_BUY',
      displayPriority: 76,
      scopeType: 'PRODUCT',
      stockMode: 'LAZY_CHECK',
      status: 'ON_SHELF',
      commissionMode: 'INHERIT',
      commissionRate: null,
      aggregateEnabled: true,
      zoneEnabled: true,
      rules: {
        name: '篮球拼课（延期结算演示）',
        minCount: 3,
        maxCount: 12,
        price: 1099,
        originalPrice: 1280,
        joinDeadline: '2026-07-15T20:00:00+08:00',
        classStartTime: '2026-07-20T15:00:00+08:00',
        classAddress: '长沙市天心区篮球馆B2',
        totalLessons: 12,
        dayLessons: 2,
        settlementTag: 'DELAYED',
        storeParticipating: true,
        storeReady: true,
      },
    },
    {
      configId: 'hf-config-course-spoken',
      serviceId: 'hf-service-spoken-001',
      serviceType: 'SERVICE',
      templateCode: 'COURSE_GROUP_BUY',
      displayPriority: 82,
      scopeType: 'PRODUCT',
      stockMode: 'LAZY_CHECK',
      status: 'OFF_SHELF',
      commissionMode: 'INHERIT',
      commissionRate: null,
      aggregateEnabled: true,
      zoneEnabled: false,
      rules: {
        name: '口才表达拼课',
        minCount: 2,
        maxCount: 6,
        price: 999,
        originalPrice: 1280,
        joinDeadline: '2026-07-10T20:00:00+08:00',
        classStartTime: '2026-07-14T09:30:00+08:00',
        classAddress: '长沙市开福区训练中心C1',
        totalLessons: 8,
        dayLessons: 1,
        storeParticipating: true,
        storeReady: true,
      },
    },
    {
      configId: 'hf-config-upgrade-scratch',
      serviceId: 'hf-service-scratch-001',
      serviceType: 'SERVICE',
      templateCode: 'MEMBER_UPGRADE',
      displayPriority: 70,
      scopeType: 'PRODUCT',
      stockMode: 'SOFT_LOCK',
      status: 'ON_SHELF',
      commissionMode: 'NONE',
      commissionRate: null,
      aggregateEnabled: false,
      zoneEnabled: true,
      rules: {
        name: '成长会员升级包',
        targetLevel: 1,
        price: 399,
        autoApprove: true,
      },
    },
    {
      configId: 'hf-config-upgrade-math',
      serviceId: 'hf-service-math-001',
      serviceType: 'SERVICE',
      templateCode: 'MEMBER_UPGRADE',
      displayPriority: 68,
      scopeType: 'PRODUCT',
      stockMode: 'SOFT_LOCK',
      status: 'ON_SHELF',
      commissionMode: 'NONE',
      commissionRate: null,
      aggregateEnabled: false,
      zoneEnabled: false,
      rules: {
        name: '合伙人升级包',
        targetLevel: 2,
        price: 899,
        autoApprove: false,
      },
    },
  ],
  policies: [
    {
      policyCode: 'HF_SOURCE_HOME_GOODS',
      policyName: '首页零售商品池',
      policyType: 'SOURCE',
      status: 'ACTIVE',
      config: { productIds: ['hf-retail-cleaner-001', 'hf-retail-baby-wipes-001', 'hf-retail-nuts-gift-001'] },
    },
    {
      policyCode: 'HF_SOURCE_HOME_INSTANT',
      policyName: '首页即时商品池',
      policyType: 'SOURCE',
      status: 'ACTIVE',
      config: { productIds: ['hf-instant-blueberry-001', 'hf-instant-coconut-water-001', 'hf-instant-granola-001'] },
    },
    {
      policyCode: 'HF_SOURCE_FLASH',
      policyName: '秒杀商品池',
      policyType: 'SOURCE',
      status: 'ACTIVE',
      config: { configIds: ['hf-config-flash-coconut', 'hf-config-flash-fruit', 'hf-config-flash-cleaner'] },
    },
    {
      policyCode: 'HF_SOURCE_NEWCOMER',
      policyName: '新人商品池',
      policyType: 'SOURCE',
      status: 'ACTIVE',
      config: { newcomerProductIds: ['hf-retail-cleaner-001', 'hf-retail-baby-wipes-001', 'hf-service-swimming-001'] },
    },
    {
      policyCode: 'HF_SOURCE_COURSE',
      policyName: '课程商品池',
      policyType: 'SOURCE',
      status: 'ACTIVE',
      config: {
        productIds: [
          'hf-service-art-001',
          'hf-service-basketball-001',
          'hf-service-english-001',
          'hf-service-scratch-001',
        ],
      },
    },
    {
      policyCode: 'HF_RESOLVER_DEFAULT',
      policyName: '默认裁决策略',
      policyType: 'RESOLVER',
      status: 'ACTIVE',
      config: {
        primaryOfferTypes: ['FLASH_SALE', 'COURSE_GROUP', 'MEMBER_UPGRADE', 'FULL_REDUCTION'],
      },
    },
    {
      policyCode: 'HF_SORT_PRICE_ASC',
      policyName: '价格升序',
      policyType: 'SORT',
      status: 'ACTIVE',
      config: { sortRules: [{ field: 'price', order: 'asc' }] },
    },
    {
      policyCode: 'HF_SORT_PRIORITY',
      policyName: '优先级排序',
      policyType: 'SORT',
      status: 'ACTIVE',
      config: { sortRules: [{ field: 'priority', order: 'desc' }] },
    },
    {
      policyCode: 'HF_AUDIENCE_ALL',
      policyName: '全量用户',
      policyType: 'AUDIENCE',
      status: 'ACTIVE',
      config: { mode: 'ALL' },
    },
    {
      policyCode: 'HF_AUDIENCE_NEWCOMER',
      policyName: '新人用户',
      policyType: 'AUDIENCE',
      status: 'ACTIVE',
      config: { mode: 'MEMBER_TAG', includeTags: ['newcomer'] },
    },
    {
      policyCode: 'HF_CARD_SIMPLE',
      policyName: '简版卡片',
      policyType: 'CARD_TEMPLATE',
      status: 'ACTIVE',
      config: { templateConfig: { cardStyle: 'simple', showPrice: true, showTags: true } },
    },
    {
      policyCode: 'HF_CARD_HERO',
      policyName: '主视觉卡片',
      policyType: 'CARD_TEMPLATE',
      status: 'ACTIVE',
      config: { templateConfig: { cardStyle: 'hero', showPrice: true, showTags: true, showSubtitle: true } },
    },
  ],
  scenes: [
    {
      sceneCode: 'HF_SCENE_HOME',
      sceneName: '湖南首页推荐',
      sceneType: 'HOMEPAGE',
      channelScope: ['miniapp', 'admin-preview'],
      pageRoute: '/pages/index/index',
      defaultCardTemplateCode: 'HF_CARD_HERO',
      defaultResolverPolicyCode: 'HF_RESOLVER_DEFAULT',
      placementConfig: {
        activityTypeFilter: 'FLASH_SALE',
        storeMatchMode: 'CURRENT_STORE',
        sortMode: 'RECOMMEND_WEIGHT',
      },
      status: 'ACTIVE',
    },
    {
      sceneCode: 'HF_SCENE_FLASH',
      sceneName: '秒杀专区',
      sceneType: 'FLASH_ZONE',
      channelScope: ['miniapp'],
      pageRoute: '/pages/marketing/flash',
      defaultCardTemplateCode: 'HF_CARD_SIMPLE',
      defaultResolverPolicyCode: 'HF_RESOLVER_DEFAULT',
      placementConfig: {
        activityTypeFilter: 'FLASH_SALE',
        storeMatchMode: 'CURRENT_STORE',
        sortMode: 'UPDATE_TIME',
      },
      status: 'ACTIVE',
    },
    {
      sceneCode: 'HF_SCENE_NEWCOMER',
      sceneName: '新人专区',
      sceneType: 'NEWCOMER',
      channelScope: ['miniapp'],
      pageRoute: '/pages/marketing/newcomer',
      defaultCardTemplateCode: 'HF_CARD_SIMPLE',
      defaultResolverPolicyCode: 'HF_RESOLVER_DEFAULT',
      placementConfig: {
        activityTypeFilter: 'NEWCOMER_EXCLUSIVE',
        storeMatchMode: 'CURRENT_STORE',
        sortMode: 'RECOMMEND_WEIGHT',
      },
      status: 'ACTIVE',
    },
    {
      sceneCode: 'HF_SCENE_COURSE',
      sceneName: '课程专区',
      sceneType: 'COURSE',
      channelScope: ['miniapp', 'admin-preview'],
      pageRoute: '/pages/course-group/index',
      defaultCardTemplateCode: 'HF_CARD_HERO',
      defaultResolverPolicyCode: 'HF_RESOLVER_DEFAULT',
      placementConfig: {
        activityTypeFilter: 'COURSE_GROUP',
        storeMatchMode: 'ALL_STORES',
        sortMode: 'RECOMMEND_WEIGHT',
      },
      status: 'ACTIVE',
    },
  ],
  sceneModules: [
    {
      sceneCode: 'HF_SCENE_HOME',
      moduleCode: 'HF_HOME_GOODS',
      moduleName: '首页零售推荐',
      moduleType: 'PRODUCT_LIST',
      title: '到店热卖',
      subTitle: '门店热销与新人价商品',
      displayOrder: 10,
      limitSize: 12,
      sourcePolicyCode: 'HF_SOURCE_HOME_GOODS',
      resolverPolicyCode: 'HF_RESOLVER_DEFAULT',
      sortPolicyCode: 'HF_SORT_PRIORITY',
      audiencePolicyCode: 'HF_AUDIENCE_ALL',
      cardTemplateCode: 'HF_CARD_HERO',
      attributionPolicyCode: null,
      status: 'ACTIVE',
      uiConfig: { layout: 'carousel-grid' },
    },
    {
      sceneCode: 'HF_SCENE_HOME',
      moduleCode: 'HF_HOME_INSTANT',
      moduleName: '首页即时零售',
      moduleType: 'PRODUCT_LIST',
      title: '今日即达',
      subTitle: '鲜果饮品快速送达',
      displayOrder: 20,
      limitSize: 12,
      sourcePolicyCode: 'HF_SOURCE_HOME_INSTANT',
      resolverPolicyCode: 'HF_RESOLVER_DEFAULT',
      sortPolicyCode: 'HF_SORT_PRICE_ASC',
      audiencePolicyCode: 'HF_AUDIENCE_ALL',
      cardTemplateCode: 'HF_CARD_SIMPLE',
      attributionPolicyCode: null,
      status: 'ACTIVE',
      uiConfig: { layout: 'grid-2' },
    },
    {
      sceneCode: 'HF_SCENE_FLASH',
      moduleCode: 'HF_FLASH_TODAY',
      moduleName: '今日秒杀',
      moduleType: 'ACTIVITY_LIST',
      title: '今日秒杀',
      subTitle: '限时库存先到先得',
      displayOrder: 10,
      limitSize: 10,
      sourcePolicyCode: 'HF_SOURCE_FLASH',
      resolverPolicyCode: 'HF_RESOLVER_DEFAULT',
      sortPolicyCode: 'HF_SORT_PRIORITY',
      audiencePolicyCode: 'HF_AUDIENCE_ALL',
      cardTemplateCode: 'HF_CARD_SIMPLE',
      attributionPolicyCode: null,
      status: 'ACTIVE',
      uiConfig: { layout: 'list' },
    },
    {
      sceneCode: 'HF_SCENE_FLASH',
      moduleCode: 'HF_FLASH_BUNDLE',
      moduleName: '秒杀加购推荐',
      moduleType: 'PRODUCT_LIST',
      title: '秒杀加购',
      subTitle: '与秒杀单搭配更划算',
      displayOrder: 20,
      limitSize: 8,
      sourcePolicyCode: 'HF_SOURCE_HOME_GOODS',
      resolverPolicyCode: 'HF_RESOLVER_DEFAULT',
      sortPolicyCode: 'HF_SORT_PRICE_ASC',
      audiencePolicyCode: 'HF_AUDIENCE_ALL',
      cardTemplateCode: 'HF_CARD_SIMPLE',
      attributionPolicyCode: null,
      status: 'ACTIVE',
      uiConfig: { layout: 'grid-2' },
    },
    {
      sceneCode: 'HF_SCENE_NEWCOMER',
      moduleCode: 'HF_NEWCOMER_PRICE',
      moduleName: '新人专享价',
      moduleType: 'PRODUCT_LIST',
      title: '新人专享',
      subTitle: '首单福利与新人券联动',
      displayOrder: 10,
      limitSize: 10,
      sourcePolicyCode: 'HF_SOURCE_NEWCOMER',
      resolverPolicyCode: 'HF_RESOLVER_DEFAULT',
      sortPolicyCode: 'HF_SORT_PRIORITY',
      audiencePolicyCode: 'HF_AUDIENCE_NEWCOMER',
      cardTemplateCode: 'HF_CARD_HERO',
      attributionPolicyCode: null,
      status: 'ACTIVE',
      uiConfig: { layout: 'hero-list' },
    },
    {
      sceneCode: 'HF_SCENE_NEWCOMER',
      moduleCode: 'HF_NEWCOMER_COUPON',
      moduleName: '新人权益卡',
      moduleType: 'BENEFIT_BANNER',
      title: '新人权益',
      subTitle: '满减券、课程券、体验券',
      displayOrder: 20,
      limitSize: 4,
      sourcePolicyCode: 'HF_SOURCE_NEWCOMER',
      resolverPolicyCode: 'HF_RESOLVER_DEFAULT',
      sortPolicyCode: 'HF_SORT_PRIORITY',
      audiencePolicyCode: 'HF_AUDIENCE_NEWCOMER',
      cardTemplateCode: 'HF_CARD_SIMPLE',
      attributionPolicyCode: null,
      status: 'ACTIVE',
      uiConfig: { layout: 'coupon-stack' },
    },
    {
      sceneCode: 'HF_SCENE_COURSE',
      moduleCode: 'HF_COURSE_GROUP',
      moduleName: '课程拼课',
      moduleType: 'ACTIVITY_LIST',
      title: '热门拼课',
      subTitle: '艺术体育语言课程限时报名',
      displayOrder: 10,
      limitSize: 10,
      sourcePolicyCode: 'HF_SOURCE_COURSE',
      resolverPolicyCode: 'HF_RESOLVER_DEFAULT',
      sortPolicyCode: 'HF_SORT_PRIORITY',
      audiencePolicyCode: 'HF_AUDIENCE_ALL',
      cardTemplateCode: 'HF_CARD_HERO',
      attributionPolicyCode: null,
      status: 'ACTIVE',
      uiConfig: { layout: 'course-list' },
    },
    {
      sceneCode: 'HF_SCENE_COURSE',
      moduleCode: 'HF_COURSE_RECOMMEND',
      moduleName: '课程推荐',
      moduleType: 'PRODUCT_LIST',
      title: '精品课程',
      subTitle: '多课时包与多班型演示',
      displayOrder: 20,
      limitSize: 12,
      sourcePolicyCode: 'HF_SOURCE_COURSE',
      resolverPolicyCode: 'HF_RESOLVER_DEFAULT',
      sortPolicyCode: 'HF_SORT_PRICE_ASC',
      audiencePolicyCode: 'HF_AUDIENCE_ALL',
      cardTemplateCode: 'HF_CARD_SIMPLE',
      attributionPolicyCode: null,
      status: 'ACTIVE',
      uiConfig: { layout: 'grid-2' },
    },
  ],
  activityPriorityRules: [
    { activityType: 'FLASH_SALE', priority: 100, aggregateEnabled: true, zoneEnabled: true, manualLockEnabled: false },
    { activityType: 'COURSE_GROUP', priority: 90, aggregateEnabled: true, zoneEnabled: true, manualLockEnabled: true },
    {
      activityType: 'FULL_REDUCTION',
      priority: 70,
      aggregateEnabled: true,
      zoneEnabled: false,
      manualLockEnabled: false,
    },
    {
      activityType: 'MEMBER_UPGRADE',
      priority: 60,
      aggregateEnabled: false,
      zoneEnabled: true,
      manualLockEnabled: false,
    },
  ],
};
