import { HUNAN_FULL_PRODUCTS } from './catalog-products';
import type { HunanCommissionScenario, HunanOrderItemScenario, HunanOrderScenario } from './types';

const PRODUCT_MAP = new Map(HUNAN_FULL_PRODUCTS.map(product => [product.productId, product]));

function item(
  productId: string,
  skuId: string,
  quantity: number,
  price: number,
  overrides: Partial<HunanOrderItemScenario> = {},
): HunanOrderItemScenario {
  const product = PRODUCT_MAP.get(productId);
  if (!product) {
    throw new Error(`Missing product blueprint for ${productId}`);
  }
  const sku = product.skus.find(candidate => candidate.skuId === skuId);
  if (!sku) {
    throw new Error(`Missing sku blueprint ${skuId}`);
  }
  return {
    productId,
    skuId,
    productName: product.name,
    productImg: product.mainImage,
    specData: sku.specValues,
    price,
    quantity,
    pointsRatio: sku.pointsRatio,
    earnedPoints: Math.round(price * quantity),
    orderItemOriginalAmount: price * quantity,
    orderItemDiscountAllocated: 0,
    orderItemFinalPaid: price * quantity,
    resolutionSnapshot: {
      productId,
      skuId,
      theme: product.theme,
    },
    ...overrides,
  };
}

function commission(
  beneficiaryId: string,
  level: number,
  amount: number,
  commissionBase: number,
  orderActualPaid: number,
  status: HunanCommissionScenario['status'],
  overrides: Partial<HunanCommissionScenario> = {},
): HunanCommissionScenario {
  return {
    beneficiaryId,
    level,
    amount,
    rateSnapshot: level === 1 ? 0.04 : 0.06,
    commissionBase,
    commissionBaseType: 'ORIGINAL_PRICE',
    orderOriginalPrice: commissionBase,
    orderActualPaid,
    couponDiscount: 0,
    pointsDiscount: 0,
    isCapped: false,
    status,
    commissionRuleSource: 'TENANT_DEFAULT',
    planSettleOffsetDays: 7,
    settleOffsetDays: status === 'SETTLED' ? 10 : null,
    ...overrides,
  };
}

export const HUNAN_FULL_ORDER_SCENARIOS: HunanOrderScenario[] = [
  {
    orderId: 'hf-order-001',
    orderSn: 'HF-ORDER-001',
    scenarioType: 'product-normal',
    memberId: 'hf-member-regular-01',
    referrerId: 'hf-member-l1-01',
    shareUserId: 'hf-member-l1-01',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 82,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 82,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 82,
    receiverName: '陈晓',
    receiverPhone: '13900001111',
    receiverAddress: '长沙市岳麓区麓山南路88号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-001',
    createOffsetDays: -12,
    payOffsetDays: -12,
    items: [
      item('hf-retail-cleaner-001', 'hf-retail-cleaner-001-sku-2', 1, 36.9, {
        attribution: {
          sourceSceneCodeSnapshot: 'HF_SCENE_HOME',
          sourceModuleCodeSnapshot: 'HF_HOME_GOODS',
          sourceChannelSnapshot: 'miniapp',
          sourcePagePathSnapshot: '/pages/index/index',
          shareUserIdSnapshot: 'hf-member-l1-01',
          referrerIdSnapshot: 'hf-member-l1-01',
          cardTemplateCodeSnapshot: 'HF_CARD_HERO',
          resolverPolicyCodeSnapshot: 'HF_RESOLVER_DEFAULT',
          resolverReleaseNoSnapshot: 1,
          audienceSnapshot: { mode: 'ALL' },
          secondaryBenefitsSnapshot: { newcomerPrice: false },
          denyStackReasonsSnapshot: [],
          entryContextSnapshot: { entry: 'home' },
        },
      }),
      item('hf-retail-baby-wipes-001', 'hf-retail-baby-wipes-001-sku-2', 2, 22.55),
    ],
    commissions: [
      commission('hf-member-l1-01', 1, 3.28, 82, 82, 'SETTLED'),
      commission('hf-member-l2-01', 2, 4.92, 82, 82, 'SETTLED'),
    ],
  },
  {
    orderId: 'hf-order-002',
    orderSn: 'HF-ORDER-002',
    scenarioType: 'product-flash-sale',
    memberId: 'hf-member-regular-02',
    referrerId: 'hf-member-l1-07',
    shareUserId: 'hf-member-l1-07',
    orderType: 'PRODUCT',
    status: 'PAID',
    payStatus: 'PAID',
    totalAmount: 29.9,
    freightAmount: 0,
    discountAmount: 10,
    payAmount: 29.9,
    couponDiscount: 10,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 18,
    userCouponCode: 'HF-CPN-FLASH-10',
    receiverName: '李萌',
    receiverPhone: '13900002222',
    receiverAddress: '长沙市开福区四方坪街道8号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-002',
    createOffsetDays: -2,
    payOffsetDays: -2,
    items: [
      item('hf-instant-coconut-water-001', 'hf-instant-coconut-water-001-sku-1', 1, 29.9, {
        activityType: 'FLASH_SALE',
        activityConfigId: 'hf-config-flash-coconut',
        activityNameSnapshot: '椰子水限时秒杀',
        activityPriceSnapshot: 29.9,
        activityStatusSnapshot: 'ACTIVE',
        activityCommissionModeSnapshot: 'NONE',
        activityCommissionRateSnapshot: 0,
        commissionRuleSource: 'FLASH_SALE_NONE',
        commissionPoolSnapshot: 0,
        l1WeightSnapshot: 0,
        l2WeightSnapshot: 0,
        orderItemDiscountAllocated: 10,
        orderItemFinalPaid: 29.9,
        attribution: {
          sourceSceneCodeSnapshot: 'HF_SCENE_FLASH',
          sourceModuleCodeSnapshot: 'HF_FLASH_TODAY',
          sourceChannelSnapshot: 'miniapp',
          sourcePagePathSnapshot: '/pages/marketing/flash',
          shareUserIdSnapshot: 'hf-member-l1-07',
          referrerIdSnapshot: 'hf-member-l1-07',
          cardTemplateCodeSnapshot: 'HF_CARD_SIMPLE',
          resolverPolicyCodeSnapshot: 'HF_RESOLVER_DEFAULT',
          resolverReleaseNoSnapshot: 1,
          audienceSnapshot: { mode: 'ALL' },
          secondaryBenefitsSnapshot: { couponCode: 'HF-CPN-FLASH-10' },
          denyStackReasonsSnapshot: [],
          entryContextSnapshot: { entry: 'flash-zone' },
        },
      }),
    ],
    commissions: [],
    playInstances: [
      {
        playInstanceId: 'hf-play-002',
        configId: 'hf-config-flash-coconut',
        templateCode: 'FLASH_SALE',
        status: 'ACTIVE',
        bindToItemIndex: 0,
        payOffsetDays: -2,
        instanceData: {
          flashPrice: 29.9,
          quantity: 1,
          stockLocked: true,
        },
      },
    ],
  },
  {
    orderId: 'hf-order-003',
    orderSn: 'HF-ORDER-003',
    scenarioType: 'product-full-reduction',
    memberId: 'hf-member-regular-03',
    referrerId: 'hf-member-l1-05',
    shareUserId: 'hf-member-l1-05',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 210,
    freightAmount: 0,
    discountAmount: 40,
    payAmount: 170,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 170,
    receiverName: '唐宁',
    receiverPhone: '13900003333',
    receiverAddress: '长沙市雨花区高桥街道19号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-003',
    createOffsetDays: -9,
    payOffsetDays: -9,
    items: [
      item('hf-retail-nuts-gift-001', 'hf-retail-nuts-gift-001-sku-3', 1, 118, {
        activityType: 'FULL_REDUCTION',
        activityNameSnapshot: '周末满减狂欢',
        activityStatusSnapshot: 'ACTIVE',
        commissionRuleSource: 'TENANT_DEFAULT',
        orderItemDiscountAllocated: 22,
        orderItemFinalPaid: 96,
      }),
      item('hf-instant-blueberry-001', 'hf-instant-blueberry-001-sku-2', 1, 52, {
        activityType: 'FULL_REDUCTION',
        activityNameSnapshot: '周末满减狂欢',
        activityStatusSnapshot: 'ACTIVE',
        orderItemDiscountAllocated: 18,
        orderItemFinalPaid: 34,
      }),
      item('hf-instant-oat-milk-001', 'hf-instant-oat-milk-001-sku-2', 1, 46.9, {
        activityType: 'FULL_REDUCTION',
        activityNameSnapshot: '周末满减狂欢',
        activityStatusSnapshot: 'ACTIVE',
        orderItemDiscountAllocated: 0,
        orderItemFinalPaid: 40,
      }),
    ],
    commissions: [
      commission('hf-member-l1-05', 1, 6.8, 170, 170, 'SETTLED'),
      commission('hf-member-l2-03', 2, 10.2, 170, 170, 'SETTLED'),
    ],
  },
  {
    orderId: 'hf-order-004',
    orderSn: 'HF-ORDER-004',
    scenarioType: 'product-coupon',
    memberId: 'hf-member-regular-04',
    referrerId: 'hf-member-l1-02',
    shareUserId: 'hf-member-l1-02',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 139,
    freightAmount: 0,
    discountAmount: 20,
    payAmount: 119,
    couponDiscount: 20,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 119,
    userCouponCode: 'HF-CPN-NEW-20',
    receiverName: '周航',
    receiverPhone: '13900004444',
    receiverAddress: '长沙市芙蓉区人民东路99号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-004',
    createOffsetDays: -6,
    payOffsetDays: -6,
    items: [
      item('hf-retail-powerbank-001', 'hf-retail-powerbank-001-sku-1', 1, 139, {
        orderItemDiscountAllocated: 20,
        orderItemFinalPaid: 119,
      }),
    ],
    commissions: [],
  },
  {
    orderId: 'hf-order-005',
    orderSn: 'HF-ORDER-005',
    scenarioType: 'product-points',
    memberId: 'hf-member-regular-05',
    referrerId: 'hf-member-l1-06',
    shareUserId: 'hf-member-l1-06',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 92,
    freightAmount: 0,
    discountAmount: 18,
    payAmount: 74,
    couponDiscount: 0,
    pointsUsed: 1800,
    pointsDiscount: 18,
    pointsEarned: 56,
    receiverName: '方芮',
    receiverPhone: '13900005555',
    receiverAddress: '长沙市岳麓区西二环188号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-005',
    createOffsetDays: -5,
    payOffsetDays: -5,
    items: [
      item('hf-retail-nuts-gift-001', 'hf-retail-nuts-gift-001-sku-2', 1, 92, {
        orderItemDiscountAllocated: 18,
        orderItemFinalPaid: 74,
      }),
    ],
    commissions: [
      commission('hf-member-l1-06', 1, 2.96, 74, 74, 'SETTLED', {
        pointsDiscount: 18,
        orderOriginalPrice: 92,
        commissionBase: 74,
      }),
      commission('hf-member-l2-03', 2, 4.44, 74, 74, 'SETTLED', {
        pointsDiscount: 18,
        orderOriginalPrice: 92,
        commissionBase: 74,
      }),
    ],
  },
  {
    orderId: 'hf-order-006',
    orderSn: 'HF-ORDER-006',
    scenarioType: 'product-exchange',
    memberId: 'hf-member-regular-06',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 0.01,
    freightAmount: 0,
    discountAmount: 39.89,
    payAmount: 0.01,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 0,
    userCouponCode: 'HF-CPN-EXCHANGE-OAT',
    receiverName: '彭栀',
    receiverPhone: '13900006666',
    receiverAddress: '长沙市望城区银星路21号',
    payType: 'COUPON_EXCHANGE',
    transactionId: 'hf-pay-006',
    createOffsetDays: -4,
    payOffsetDays: -4,
    items: [
      item('hf-retail-oatmeal-001', 'hf-retail-oatmeal-001-sku-3', 1, 0.01, {
        orderItemOriginalAmount: 39.9,
        orderItemDiscountAllocated: 39.89,
        orderItemFinalPaid: 0.01,
      }),
    ],
    commissions: [],
  },
  {
    orderId: 'hf-order-007',
    orderSn: 'HF-ORDER-007',
    scenarioType: 'service-normal',
    memberId: 'hf-member-regular-07',
    referrerId: 'hf-member-l1-03',
    shareUserId: 'hf-member-l1-03',
    orderType: 'SERVICE',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 1490,
    freightAmount: 0,
    discountAmount: 120,
    payAmount: 1370,
    couponDiscount: 120,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 980,
    userCouponCode: 'HF-CPN-COURSE-120',
    bookingOffsetDays: -3,
    serviceRemark: '周末下午班预约',
    payType: 'WECHAT',
    transactionId: 'hf-pay-007',
    createOffsetDays: -8,
    payOffsetDays: -8,
    items: [
      item('hf-service-english-001', 'hf-service-english-001-sku-1', 1, 1490, {
        orderItemDiscountAllocated: 120,
        orderItemFinalPaid: 1370,
      }),
    ],
    commissions: [
      commission('hf-member-l1-03', 1, 54.8, 1370, 1370, 'SETTLED'),
      commission('hf-member-l2-02', 2, 82.2, 1370, 1370, 'SETTLED'),
    ],
  },
  {
    orderId: 'hf-order-008',
    orderSn: 'HF-ORDER-008',
    scenarioType: 'service-course-group',
    memberId: 'hf-member-regular-08',
    referrerId: 'hf-member-l1-04',
    shareUserId: 'hf-member-l1-04',
    orderType: 'SERVICE',
    status: 'PAID',
    payStatus: 'PAID',
    totalAmount: 799,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 799,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 480,
    bookingOffsetDays: 2,
    serviceRemark: '拼课待成团',
    payType: 'WECHAT',
    transactionId: 'hf-pay-008',
    createOffsetDays: -1,
    payOffsetDays: -1,
    items: [
      item('hf-service-art-001', 'hf-service-art-001-sku-1', 1, 799, {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-art',
        playInstanceId: 'hf-play-008',
        activityNameSnapshot: '创意绘画拼课',
        activityPriceSnapshot: 799,
        activityStatusSnapshot: 'ACTIVE',
        activityCommissionModeSnapshot: 'INHERIT',
        activityCommissionRateSnapshot: 0.1,
        commissionRuleSource: 'TENANT_DEFAULT',
        commissionPoolSnapshot: 79.9,
        l1WeightSnapshot: 0.4,
        l2WeightSnapshot: 0.6,
      }),
    ],
    commissions: [
      commission('hf-member-l1-04', 1, 31.96, 799, 799, 'FROZEN', {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-art',
        playInstanceId: 'hf-play-008',
        activityCommissionRateSnapshot: 0.1,
        commissionPoolSnapshot: 79.9,
      }),
      commission('hf-member-l2-02', 2, 47.94, 799, 799, 'FROZEN', {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-art',
        playInstanceId: 'hf-play-008',
        activityCommissionRateSnapshot: 0.1,
        commissionPoolSnapshot: 79.9,
      }),
    ],
    playInstances: [
      {
        playInstanceId: 'hf-play-008',
        configId: 'hf-config-course-art',
        templateCode: 'COURSE_GROUP_BUY',
        status: 'ACTIVE',
        bindToItemIndex: 0,
        payOffsetDays: -1,
        instanceData: {
          isLeader: true,
          currentCount: 1,
          targetCount: 2,
          groupPrice: 799,
        },
      },
    ],
  },
  {
    orderId: 'hf-order-009',
    orderSn: 'HF-ORDER-009',
    scenarioType: 'member-upgrade',
    memberId: 'hf-member-l1-07',
    orderType: 'SERVICE',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 899,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 899,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 400,
    serviceRemark: '会员升级权益购买',
    payType: 'WECHAT',
    transactionId: 'hf-pay-009',
    createOffsetDays: -11,
    payOffsetDays: -11,
    items: [
      item('hf-service-math-001', 'hf-service-math-001-sku-1', 1, 899, {
        activityType: 'MEMBER_UPGRADE',
        activityConfigId: 'hf-config-upgrade-math',
        activityNameSnapshot: '合伙人升级包',
        activityPriceSnapshot: 899,
        activityStatusSnapshot: 'SUCCESS',
        activityCommissionModeSnapshot: 'NONE',
        activityCommissionRateSnapshot: 0,
        commissionRuleSource: 'ACTIVITY_NONE',
        commissionPoolSnapshot: 0,
      }),
    ],
    commissions: [],
  },
  {
    orderId: 'hf-order-010',
    orderSn: 'HF-ORDER-010',
    scenarioType: 'refund-full',
    memberId: 'hf-member-regular-09',
    referrerId: 'hf-member-l1-01',
    shareUserId: 'hf-member-l1-01',
    orderType: 'PRODUCT',
    status: 'REFUNDED',
    payStatus: 'REFUNDED',
    totalAmount: 46.9,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 46.9,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 0,
    receiverName: '袁知',
    receiverPhone: '13900007777',
    receiverAddress: '长沙市雨花区德思勤广场6号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-010',
    createOffsetDays: -7,
    payOffsetDays: -7,
    remark: '全额退款样本',
    items: [
      item('hf-instant-granola-001', 'hf-instant-granola-001-sku-2', 1, 46.9, {
        orderItemFinalPaid: 46.9,
      }),
    ],
    commissions: [
      commission('hf-member-l1-01', 1, 1.88, 46.9, 46.9, 'CANCELLED', {
        settleOffsetDays: null,
      }),
      commission('hf-member-l2-01', 2, 2.81, 46.9, 46.9, 'CANCELLED', {
        settleOffsetDays: null,
      }),
    ],
  },
  {
    orderId: 'hf-order-011',
    orderSn: 'HF-ORDER-011',
    scenarioType: 'refund-partial',
    memberId: 'hf-member-regular-10',
    referrerId: 'hf-member-l1-06',
    shareUserId: 'hf-member-l1-06',
    orderType: 'PRODUCT',
    status: 'REFUNDED',
    payStatus: 'REFUNDED',
    totalAmount: 138.8,
    freightAmount: 0,
    discountAmount: 20,
    payAmount: 118.8,
    couponDiscount: 20,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 98,
    userCouponCode: 'HF-CPN-ALL-90',
    receiverName: '叶繁',
    receiverPhone: '13900008888',
    receiverAddress: '长沙市天心区南湖路66号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-011',
    createOffsetDays: -10,
    payOffsetDays: -10,
    remark: '部分退款样本',
    items: [
      item('hf-retail-cleaner-001', 'hf-retail-cleaner-001-sku-1', 2, 21.9, {
        orderItemDiscountAllocated: 5,
        orderItemFinalPaid: 38.8,
      }),
      item('hf-retail-baby-shampoo-001', 'hf-retail-baby-shampoo-001-sku-2', 1, 80, {
        commissionRuleSource: 'MANUAL_DISABLED',
        orderItemDiscountAllocated: 15,
        orderItemFinalPaid: 80,
      }),
    ],
    commissions: [
      commission('hf-member-l1-06', 1, 1.55, 38.8, 38.8, 'CANCELLED', {
        itemIndex: 0,
        settleOffsetDays: null,
      }),
      commission('hf-member-l2-03', 2, 2.33, 38.8, 38.8, 'CANCELLED', {
        itemIndex: 0,
        settleOffsetDays: null,
      }),
    ],
  },
  {
    orderId: 'hf-order-012',
    orderSn: 'HF-ORDER-012',
    scenarioType: 'product-normal',
    memberId: 'hf-member-regular-11',
    orderType: 'PRODUCT',
    status: 'PENDING_PAY',
    payStatus: 'UNPAID',
    totalAmount: 55,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 55,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 0,
    receiverName: '姜葵',
    receiverPhone: '13900009999',
    receiverAddress: '长沙市开福区北辰三角洲18号',
    createOffsetDays: 0,
    items: [item('hf-retail-nuts-gift-001', 'hf-retail-nuts-gift-001-sku-1', 1, 55)],
    commissions: [],
  },
  {
    orderId: 'hf-order-013',
    orderSn: 'HF-ORDER-013',
    scenarioType: 'service-normal',
    memberId: 'hf-member-regular-12',
    referrerId: 'hf-member-l1-08',
    shareUserId: 'hf-member-l1-08',
    orderType: 'SERVICE',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 1099,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 1099,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 650,
    bookingOffsetDays: -1,
    serviceRemark: '篮球周末班核销完成',
    payType: 'WECHAT',
    transactionId: 'hf-pay-013',
    createOffsetDays: -3,
    payOffsetDays: -3,
    items: [item('hf-service-basketball-001', 'hf-service-basketball-001-sku-1', 1, 1099)],
    commissions: [
      commission('hf-member-l1-08', 1, 43.96, 1099, 1099, 'FROZEN'),
      commission('hf-member-l2-04', 2, 65.94, 1099, 1099, 'FROZEN'),
    ],
  },
  {
    orderId: 'hf-order-014',
    orderSn: 'HF-ORDER-014',
    scenarioType: 'product-coupon',
    memberId: 'hf-member-regular-13',
    referrerId: 'hf-member-l1-02',
    shareUserId: 'hf-member-l1-02',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 86.8,
    freightAmount: 0,
    discountAmount: 8,
    payAmount: 78.8,
    couponDiscount: 8,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 78,
    userCouponCode: 'HF-CPN-FLASH-10',
    receiverName: '贺汀',
    receiverPhone: '13900010000',
    receiverAddress: '长沙市湘江新区学士街道101号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-014',
    createOffsetDays: -2,
    payOffsetDays: -2,
    items: [
      item('hf-instant-oat-milk-001', 'hf-instant-oat-milk-001-sku-2', 1, 46.9),
      item('hf-instant-craft-beer-001', 'hf-instant-craft-beer-001-sku-1', 1, 39.9),
    ],
    commissions: [
      commission('hf-member-l1-02', 1, 3.15, 78.8, 78.8, 'SETTLED', {
        couponDiscount: 8,
        orderOriginalPrice: 86.8,
      }),
      commission('hf-member-l2-01', 2, 4.73, 78.8, 78.8, 'SETTLED', {
        couponDiscount: 8,
        orderOriginalPrice: 86.8,
      }),
    ],
  },
  {
    orderId: 'hf-order-015',
    orderSn: 'HF-ORDER-015',
    scenarioType: 'product-full-reduction',
    memberId: 'hf-member-regular-14',
    referrerId: 'hf-member-l1-05',
    shareUserId: 'hf-member-l1-05',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 388.8,
    freightAmount: 0,
    discountAmount: 50,
    payAmount: 338.8,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 339,
    receiverName: '邵未',
    receiverPhone: '13900010001',
    receiverAddress: '长沙市岳麓区枫林路156号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-015',
    createOffsetDays: -4,
    payOffsetDays: -4,
    items: [
      item('hf-retail-earbud-001', 'hf-retail-earbud-001-sku-2', 1, 239, {
        activityType: 'FULL_REDUCTION',
        activityNameSnapshot: '周末满减狂欢',
        orderItemDiscountAllocated: 30,
        orderItemFinalPaid: 209,
      }),
      item('hf-retail-powerbank-001', 'hf-retail-powerbank-001-sku-2', 1, 149.8, {
        activityType: 'FULL_REDUCTION',
        activityNameSnapshot: '周末满减狂欢',
        orderItemDiscountAllocated: 20,
        orderItemFinalPaid: 129.8,
      }),
    ],
    commissions: [
      commission('hf-member-l1-05', 1, 18, 338.8, 338.8, 'FROZEN', {
        commissionBaseType: 'ACTUAL_PAID',
        rateSnapshot: 0.12,
        isCapped: true,
        commissionRuleSource: 'RISK_CAP_RULE',
        commissionPoolSnapshot: 45,
      }),
      commission('hf-member-l2-03', 2, 27, 338.8, 338.8, 'FROZEN', {
        commissionBaseType: 'ACTUAL_PAID',
        rateSnapshot: 0.18,
        isCapped: true,
        commissionRuleSource: 'RISK_CAP_RULE',
        commissionPoolSnapshot: 45,
      }),
    ],
  },
  {
    orderId: 'hf-order-016',
    orderSn: 'HF-ORDER-016',
    scenarioType: 'product-coupon',
    memberId: 'hf-member-regular-15',
    referrerId: 'hf-member-l1-02',
    shareUserId: 'hf-member-l1-02',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 268,
    freightAmount: 0,
    discountAmount: 60,
    payAmount: 208,
    couponDiscount: 40,
    pointsUsed: 2000,
    pointsDiscount: 20,
    pointsEarned: 156,
    userCouponCode: 'HF-CPN-NEW-40',
    receiverName: '沈砚',
    receiverPhone: '13900010002',
    receiverAddress: '长沙市开福区月湖街88号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-016',
    createOffsetDays: -3,
    payOffsetDays: -3,
    items: [
      item('hf-retail-mop-001', 'hf-retail-mop-001-sku-3', 1, 168, {
        orderItemDiscountAllocated: 40,
        orderItemFinalPaid: 128,
      }),
      item('hf-instant-fruit-platter-001', 'hf-instant-fruit-platter-001-sku-1', 1, 100, {
        orderItemDiscountAllocated: 20,
        orderItemFinalPaid: 80,
      }),
    ],
    commissions: [
      commission('hf-member-l1-02', 1, 8.32, 208, 208, 'SETTLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'PRODUCT_OVERRIDE_ACTUAL_PAID',
        couponDiscount: 40,
        pointsDiscount: 20,
        orderOriginalPrice: 268,
        isCrossTenant: false,
      }),
      commission('hf-member-l2-01', 2, 12.48, 208, 208, 'SETTLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'PRODUCT_OVERRIDE_ACTUAL_PAID',
        couponDiscount: 40,
        pointsDiscount: 20,
        orderOriginalPrice: 268,
      }),
    ],
  },
  {
    orderId: 'hf-order-017',
    orderSn: 'HF-ORDER-017',
    scenarioType: 'product-points',
    memberId: 'hf-member-regular-16',
    referrerId: 'hf-member-l1-06',
    shareUserId: 'hf-member-l1-06',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 129,
    freightAmount: 0,
    discountAmount: 30,
    payAmount: 99,
    couponDiscount: 0,
    pointsUsed: 3000,
    pointsDiscount: 30,
    pointsEarned: 72,
    receiverName: '吕栖',
    receiverPhone: '13900010003',
    receiverAddress: '长沙市雨花区香樟路32号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-017',
    createOffsetDays: -2,
    payOffsetDays: -2,
    items: [
      item('hf-instant-blueberry-001', 'hf-instant-blueberry-001-sku-3', 1, 59, {
        orderItemDiscountAllocated: 15,
        orderItemFinalPaid: 44,
      }),
      item('hf-retail-oatmeal-001', 'hf-retail-oatmeal-001-sku-2', 1, 70, {
        orderItemDiscountAllocated: 15,
        orderItemFinalPaid: 55,
      }),
    ],
    commissions: [
      commission('hf-member-l1-06', 1, 3.96, 99, 99, 'SETTLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'POINTS_DEDUCT_BASE',
        pointsDiscount: 30,
        orderOriginalPrice: 129,
      }),
      commission('hf-member-l2-03', 2, 5.94, 99, 99, 'SETTLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'POINTS_DEDUCT_BASE',
        pointsDiscount: 30,
        orderOriginalPrice: 129,
      }),
    ],
  },
  {
    orderId: 'hf-order-018',
    orderSn: 'HF-ORDER-018',
    scenarioType: 'service-course-group',
    memberId: 'hf-member-regular-17',
    referrerId: 'hf-member-l1-04',
    shareUserId: 'hf-member-l1-04',
    orderType: 'SERVICE',
    status: 'PAID',
    payStatus: 'PAID',
    totalAmount: 1099,
    freightAmount: 0,
    discountAmount: 100,
    payAmount: 999,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 620,
    bookingOffsetDays: 3,
    serviceRemark: '拼课进行中样本',
    payType: 'WECHAT',
    transactionId: 'hf-pay-018',
    createOffsetDays: -3,
    payOffsetDays: -3,
    items: [
      item('hf-service-basketball-001', 'hf-service-basketball-001-sku-2', 1, 1099, {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-basketball',
        playInstanceId: 'hf-play-018',
        activityNameSnapshot: '篮球周末拼课',
        activityPriceSnapshot: 999,
        activityStatusSnapshot: 'ACTIVE',
        activityCommissionModeSnapshot: 'INHERIT',
        activityCommissionRateSnapshot: 0.15,
        commissionRuleSource: 'ACTIVITY_OVERRIDE',
        commissionPoolSnapshot: 149.85,
        l1WeightSnapshot: 0.4,
        l2WeightSnapshot: 0.6,
        orderItemDiscountAllocated: 100,
        orderItemFinalPaid: 999,
      }),
    ],
    commissions: [
      commission('hf-member-l1-04', 1, 59.94, 999, 999, 'FROZEN', {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-basketball',
        playInstanceId: 'hf-play-018',
        activityCommissionRateSnapshot: 0.15,
        commissionPoolSnapshot: 149.85,
        commissionRuleSource: 'ACTIVITY_OVERRIDE',
      }),
      commission('hf-member-l2-02', 2, 89.91, 999, 999, 'FROZEN', {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-basketball',
        playInstanceId: 'hf-play-018',
        activityCommissionRateSnapshot: 0.15,
        commissionPoolSnapshot: 149.85,
        commissionRuleSource: 'ACTIVITY_OVERRIDE',
      }),
    ],
    playInstances: [
      {
        playInstanceId: 'hf-play-018',
        configId: 'hf-config-course-basketball',
        templateCode: 'COURSE_GROUP_BUY',
        status: 'ACTIVE',
        bindToItemIndex: 0,
        payOffsetDays: -3,
        instanceData: {
          isLeader: false,
          currentCount: 2,
          targetCount: 3,
          groupPrice: 999,
        },
      },
    ],
  },
  {
    orderId: 'hf-order-019',
    orderSn: 'HF-ORDER-019',
    scenarioType: 'service-course-group',
    memberId: 'hf-member-regular-18',
    referrerId: 'hf-member-l1-04',
    shareUserId: 'hf-member-l1-04',
    orderType: 'SERVICE',
    status: 'REFUNDED',
    payStatus: 'REFUNDED',
    totalAmount: 799,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 799,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 0,
    bookingOffsetDays: -2,
    serviceRemark: '拼课超时退款样本',
    payType: 'WECHAT',
    transactionId: 'hf-pay-019',
    createOffsetDays: -6,
    payOffsetDays: -6,
    items: [
      item('hf-service-art-001', 'hf-service-art-001-sku-2', 1, 799, {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-art',
        playInstanceId: 'hf-play-019',
        activityNameSnapshot: '创意绘画拼课',
        activityStatusSnapshot: 'TIMEOUT',
      }),
    ],
    commissions: [
      commission('hf-member-l1-04', 1, 31.96, 799, 799, 'CANCELLED', {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-art',
        playInstanceId: 'hf-play-019',
        commissionRuleSource: 'TIMEOUT_ROLLBACK',
        settleOffsetDays: null,
      }),
      commission('hf-member-l2-02', 2, 47.94, 799, 799, 'CANCELLED', {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-art',
        playInstanceId: 'hf-play-019',
        commissionRuleSource: 'TIMEOUT_ROLLBACK',
        settleOffsetDays: null,
      }),
    ],
    playInstances: [
      {
        playInstanceId: 'hf-play-019',
        configId: 'hf-config-course-art',
        templateCode: 'COURSE_GROUP_BUY',
        status: 'TIMEOUT',
        bindToItemIndex: 0,
        payOffsetDays: -6,
        endOffsetDays: -3,
        instanceData: {
          isLeader: true,
          currentCount: 1,
          targetCount: 2,
          groupPrice: 799,
        },
      },
    ],
  },
  {
    orderId: 'hf-order-020',
    orderSn: 'HF-ORDER-020',
    scenarioType: 'product-flash-sale',
    memberId: 'hf-member-regular-11',
    referrerId: 'hf-member-l1-07',
    shareUserId: 'hf-member-l1-07',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 39.9,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 39.9,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 24,
    receiverName: '宁棠',
    receiverPhone: '13900010004',
    receiverAddress: '长沙市芙蓉区人民中路88号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-020',
    createOffsetDays: -2,
    payOffsetDays: -2,
    items: [
      item('hf-instant-fruit-platter-001', 'hf-instant-fruit-platter-001-sku-2', 1, 39.9, {
        activityType: 'FLASH_SALE',
        activityConfigId: 'hf-config-flash-fruit',
        activityNameSnapshot: '鲜切果盘夜场秒杀',
        activityStatusSnapshot: 'SUCCESS',
        activityCommissionModeSnapshot: 'FIXED_RATE',
        activityCommissionRateSnapshot: 0,
        commissionRuleSource: 'FLASH_FIXED_ZERO',
        commissionPoolSnapshot: 0,
      }),
    ],
    commissions: [],
    playInstances: [
      {
        playInstanceId: 'hf-play-020',
        configId: 'hf-config-flash-fruit',
        templateCode: 'FLASH_SALE',
        status: 'SUCCESS',
        bindToItemIndex: 0,
        payOffsetDays: -2,
        endOffsetDays: -2,
        instanceData: {
          flashPrice: 39.9,
          quantity: 1,
          stockLocked: true,
        },
      },
    ],
  },
  {
    orderId: 'hf-order-021',
    orderSn: 'HF-ORDER-021',
    scenarioType: 'product-normal',
    memberId: 'hf-member-regular-12',
    referrerId: 'hf-member-l1-08',
    shareUserId: 'hf-member-l1-08',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 188.8,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 188.8,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 188,
    receiverName: '祁渡',
    receiverPhone: '13900010005',
    receiverAddress: '长沙市天心区湘府中路120号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-021',
    createOffsetDays: -5,
    payOffsetDays: -5,
    items: [
      item('hf-retail-mop-001', 'hf-retail-mop-001-sku-1', 1, 96),
      item('hf-instant-red-wine-001', 'hf-instant-red-wine-001-sku-1', 1, 92.8),
    ],
    commissions: [
      commission('hf-member-l1-01', 1, 7.55, 188.8, 188.8, 'FROZEN', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'CROSS_TENANT_RULE',
        isCrossTenant: true,
      }),
      commission('hf-member-l2-04', 2, 11.33, 188.8, 188.8, 'FROZEN', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'CROSS_TENANT_RULE',
        isCrossTenant: true,
      }),
    ],
  },
  {
    orderId: 'hf-order-022',
    orderSn: 'HF-ORDER-022',
    scenarioType: 'member-upgrade',
    memberId: 'hf-member-regular-03',
    referrerId: 'hf-member-l1-03',
    shareUserId: 'hf-member-l1-03',
    orderType: 'SERVICE',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 399,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 399,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 120,
    serviceRemark: '升级包购买-零佣金策略',
    payType: 'WECHAT',
    transactionId: 'hf-pay-022',
    createOffsetDays: -4,
    payOffsetDays: -4,
    items: [
      item('hf-service-scratch-001', 'hf-service-scratch-001-sku-1', 1, 399, {
        activityType: 'MEMBER_UPGRADE',
        activityConfigId: 'hf-config-upgrade-scratch',
        activityNameSnapshot: '成长会员升级包',
        activityStatusSnapshot: 'SUCCESS',
        activityCommissionModeSnapshot: 'NONE',
        activityCommissionRateSnapshot: 0,
        commissionRuleSource: 'ACTIVITY_NONE_ZERO',
        commissionPoolSnapshot: 0,
      }),
    ],
    commissions: [
      commission('hf-member-l1-03', 1, 0, 0, 399, 'SETTLED', {
        commissionBaseType: 'ZERO',
        commissionRuleSource: 'ACTIVITY_NONE_ZERO',
        orderOriginalPrice: 399,
        settleOffsetDays: 1,
      }),
      commission('hf-member-l2-02', 2, 0, 0, 399, 'SETTLED', {
        commissionBaseType: 'ZERO',
        commissionRuleSource: 'ACTIVITY_NONE_ZERO',
        orderOriginalPrice: 399,
        settleOffsetDays: 1,
      }),
    ],
  },
  {
    orderId: 'hf-order-023',
    orderSn: 'HF-ORDER-023',
    scenarioType: 'product-normal',
    memberId: 'hf-member-regular-04',
    referrerId: 'hf-member-l1-05',
    shareUserId: 'hf-member-l1-05',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 256,
    freightAmount: 0,
    discountAmount: 20,
    payAmount: 236,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 236,
    receiverName: '鲁今',
    receiverPhone: '13900010006',
    receiverAddress: '长沙市岳麓区望岳街道32号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-023',
    createOffsetDays: -1,
    payOffsetDays: -1,
    items: [
      item('hf-retail-powerbank-001', 'hf-retail-powerbank-001-sku-2', 1, 149.8, {
        orderItemDiscountAllocated: 10,
        orderItemFinalPaid: 139.8,
      }),
      item('hf-retail-baby-shampoo-001', 'hf-retail-baby-shampoo-001-sku-1', 1, 68, {
        commissionRuleSource: 'MANUAL_DISABLED',
        orderItemDiscountAllocated: 10,
        orderItemFinalPaid: 58,
      }),
      item('hf-instant-coconut-water-001', 'hf-instant-coconut-water-001-sku-3', 1, 38.2, {
        orderItemFinalPaid: 38.2,
      }),
    ],
    commissions: [
      commission('hf-member-l1-05', 1, 5.59, 139.8, 236, 'SETTLED', {
        itemIndex: 0,
        commissionRuleSource: 'PRODUCT_OVERRIDE',
      }),
      commission('hf-member-l2-03', 2, 2.29, 38.2, 236, 'SETTLED', {
        itemIndex: 2,
        commissionRuleSource: 'TENANT_DEFAULT',
      }),
    ],
  },
  {
    orderId: 'hf-order-024',
    orderSn: 'HF-ORDER-024',
    scenarioType: 'refund-partial',
    memberId: 'hf-member-regular-05',
    referrerId: 'hf-member-l1-06',
    shareUserId: 'hf-member-l1-06',
    orderType: 'PRODUCT',
    status: 'REFUNDED',
    payStatus: 'REFUNDED',
    totalAmount: 199,
    freightAmount: 0,
    discountAmount: 30,
    payAmount: 169,
    couponDiscount: 20,
    pointsUsed: 1000,
    pointsDiscount: 10,
    pointsEarned: 120,
    receiverName: '罗叙',
    receiverPhone: '13900010007',
    receiverAddress: '长沙市雨花区金海路88号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-024',
    createOffsetDays: -6,
    payOffsetDays: -6,
    remark: '部分退款后混合佣金状态',
    items: [
      item('hf-retail-nuts-gift-001', 'hf-retail-nuts-gift-001-sku-3', 1, 118, {
        orderItemDiscountAllocated: 15,
        orderItemFinalPaid: 103,
      }),
      item('hf-retail-cleaner-001', 'hf-retail-cleaner-001-sku-3', 1, 36.9, {
        orderItemDiscountAllocated: 10,
        orderItemFinalPaid: 26.9,
      }),
      item('hf-instant-oat-milk-001', 'hf-instant-oat-milk-001-sku-1', 1, 44.1, {
        orderItemDiscountAllocated: 5,
        orderItemFinalPaid: 39.1,
      }),
    ],
    commissions: [
      commission('hf-member-l1-06', 1, 4.12, 103, 169, 'CANCELLED', {
        itemIndex: 0,
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'PARTIAL_REFUND_REVOKE',
        couponDiscount: 20,
        pointsDiscount: 10,
        orderOriginalPrice: 199,
        settleOffsetDays: null,
      }),
      commission('hf-member-l2-03', 2, 2.35, 39.1, 169, 'SETTLED', {
        itemIndex: 2,
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'PARTIAL_REFUND_KEEP',
        couponDiscount: 20,
        pointsDiscount: 10,
        orderOriginalPrice: 199,
      }),
      commission('hf-member-l2-04', 2, 1.61, 26.9, 169, 'CANCELLED', {
        itemIndex: 1,
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'PARTIAL_REFUND_MIDDLE_ITEM',
        couponDiscount: 20,
        pointsDiscount: 10,
        orderOriginalPrice: 199,
        settleOffsetDays: null,
        isCrossTenant: false,
      }),
    ],
  },
  {
    orderId: 'hf-order-025',
    orderSn: 'HF-ORDER-025',
    scenarioType: 'service-normal',
    memberId: 'hf-member-regular-06',
    referrerId: 'hf-member-l1-03',
    shareUserId: 'hf-member-l1-03',
    orderType: 'SERVICE',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 1899,
    freightAmount: 0,
    discountAmount: 200,
    payAmount: 1699,
    couponDiscount: 120,
    pointsUsed: 8000,
    pointsDiscount: 80,
    pointsEarned: 900,
    serviceRemark: '高客单课程，触发封顶策略',
    payType: 'WECHAT',
    transactionId: 'hf-pay-025',
    createOffsetDays: -13,
    payOffsetDays: -13,
    items: [
      item('hf-service-piano-001', 'hf-service-piano-001-sku-1', 1, 1899, {
        orderItemDiscountAllocated: 200,
        orderItemFinalPaid: 1699,
      }),
    ],
    commissions: [
      commission('hf-member-l1-03', 1, 70, 1699, 1699, 'SETTLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'CATEGORY_OVERRIDE_CAP',
        orderOriginalPrice: 1899,
        couponDiscount: 120,
        pointsDiscount: 80,
        rateSnapshot: 0.08,
        isCapped: true,
        commissionPoolSnapshot: 175,
      }),
      commission('hf-member-l2-02', 2, 105, 1699, 1699, 'SETTLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'CATEGORY_OVERRIDE_CAP',
        orderOriginalPrice: 1899,
        couponDiscount: 120,
        pointsDiscount: 80,
        rateSnapshot: 0.12,
        isCapped: true,
        commissionPoolSnapshot: 175,
      }),
    ],
  },
  {
    orderId: 'hf-order-026',
    orderSn: 'HF-ORDER-026',
    scenarioType: 'product-normal',
    memberId: 'hf-member-regular-07',
    referrerId: 'hf-member-l1-01',
    shareUserId: 'hf-member-l1-01',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 24.9,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 24.9,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 15,
    receiverName: '汤昼',
    receiverPhone: '13900010008',
    receiverAddress: '长沙市开福区湘春路19号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-026',
    createOffsetDays: -1,
    payOffsetDays: -1,
    items: [item('hf-instant-coconut-water-001', 'hf-instant-coconut-water-001-sku-2', 1, 24.9)],
    commissions: [],
  },
  {
    orderId: 'hf-order-027',
    orderSn: 'HF-ORDER-027',
    scenarioType: 'product-normal',
    memberId: 'hf-member-regular-08',
    referrerId: 'hf-member-l1-04',
    shareUserId: 'hf-member-l1-04',
    orderType: 'PRODUCT',
    status: 'CANCELLED',
    payStatus: 'UNPAID',
    totalAmount: 120,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 120,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 0,
    receiverName: '袁邈',
    receiverPhone: '13900010009',
    receiverAddress: '长沙市天心区芙蓉南路67号',
    createOffsetDays: 0,
    remark: '未支付取消订单样本',
    items: [
      item('hf-retail-mop-001', 'hf-retail-mop-001-sku-2', 1, 120, {
        orderItemFinalPaid: 120,
      }),
    ],
    commissions: [],
  },
  {
    orderId: 'hf-order-028',
    orderSn: 'HF-ORDER-028',
    scenarioType: 'service-normal',
    memberId: 'hf-member-regular-09',
    referrerId: 'hf-member-l1-04',
    shareUserId: 'hf-member-l1-04',
    orderType: 'SERVICE',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 1299,
    freightAmount: 0,
    discountAmount: 100,
    payAmount: 1199,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 720,
    bookingOffsetDays: 1,
    serviceRemark: '服务类按实付分佣',
    payType: 'WECHAT',
    transactionId: 'hf-pay-028',
    createOffsetDays: -4,
    payOffsetDays: -4,
    items: [
      item('hf-service-swimming-001', 'hf-service-swimming-001-sku-2', 1, 1299, {
        orderItemDiscountAllocated: 100,
        orderItemFinalPaid: 1199,
      }),
    ],
    commissions: [
      commission('hf-member-l1-04', 1, 47.96, 1199, 1199, 'FROZEN', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'SERVICE_ACTUAL_PAID',
        orderOriginalPrice: 1299,
        isCrossTenant: false,
      }),
      commission('hf-member-l2-02', 2, 71.94, 1199, 1199, 'FROZEN', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'SERVICE_ACTUAL_PAID',
        orderOriginalPrice: 1299,
      }),
    ],
  },
  {
    orderId: 'hf-order-029',
    orderSn: 'HF-ORDER-029',
    scenarioType: 'product-coupon',
    memberId: 'hf-member-regular-18',
    referrerId: 'hf-member-l1-08',
    shareUserId: 'hf-member-l1-08',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 166,
    freightAmount: 0,
    discountAmount: 15,
    payAmount: 151,
    couponDiscount: 15,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 151,
    receiverName: '段既',
    receiverPhone: '13900010010',
    receiverAddress: '长沙市望城区雷锋大道66号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-029',
    createOffsetDays: -3,
    payOffsetDays: -3,
    items: [
      item('hf-instant-cherry-001', 'hf-instant-cherry-001-sku-1', 2, 38),
      item('hf-instant-red-wine-001', 'hf-instant-red-wine-001-sku-1', 1, 90),
    ],
    commissions: [
      commission('hf-member-l1-08', 1, 6.04, 151, 151, 'SETTLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'COUPON_DEDUCT_BASE',
        couponDiscount: 15,
        orderOriginalPrice: 166,
      }),
      commission('hf-member-l2-04', 2, 9.06, 151, 151, 'SETTLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'COUPON_DEDUCT_BASE',
        couponDiscount: 15,
        orderOriginalPrice: 166,
      }),
    ],
  },
  {
    orderId: 'hf-order-030',
    orderSn: 'HF-ORDER-030',
    scenarioType: 'service-course-group',
    memberId: 'hf-member-regular-17',
    referrerId: 'hf-member-l1-04',
    shareUserId: 'hf-member-l1-04',
    orderType: 'SERVICE',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 999,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 999,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 520,
    bookingOffsetDays: -1,
    serviceRemark: '拼课成团成功样本',
    payType: 'WECHAT',
    transactionId: 'hf-pay-030',
    createOffsetDays: -7,
    payOffsetDays: -7,
    items: [
      item('hf-service-spoken-001', 'hf-service-spoken-001-sku-1', 1, 999, {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-spoken',
        playInstanceId: 'hf-play-030',
        activityNameSnapshot: '口才表达拼课',
        activityStatusSnapshot: 'SUCCESS',
        activityCommissionModeSnapshot: 'INHERIT',
        activityCommissionRateSnapshot: 0.1,
        commissionRuleSource: 'COURSE_GROUP_SUCCESS',
        commissionPoolSnapshot: 99.9,
      }),
    ],
    commissions: [
      commission('hf-member-l1-04', 1, 39.96, 999, 999, 'SETTLED', {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-spoken',
        playInstanceId: 'hf-play-030',
        activityCommissionRateSnapshot: 0.1,
        commissionPoolSnapshot: 99.9,
        commissionRuleSource: 'COURSE_GROUP_SUCCESS',
      }),
      commission('hf-member-l2-02', 2, 59.94, 999, 999, 'SETTLED', {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-spoken',
        playInstanceId: 'hf-play-030',
        activityCommissionRateSnapshot: 0.1,
        commissionPoolSnapshot: 99.9,
        commissionRuleSource: 'COURSE_GROUP_SUCCESS',
      }),
    ],
    playInstances: [
      {
        playInstanceId: 'hf-play-030',
        configId: 'hf-config-course-spoken',
        templateCode: 'COURSE_GROUP_BUY',
        status: 'SUCCESS',
        bindToItemIndex: 0,
        payOffsetDays: -7,
        endOffsetDays: -6,
        instanceData: {
          isLeader: false,
          currentCount: 2,
          targetCount: 2,
          groupPrice: 999,
        },
      },
    ],
  },
  {
    orderId: 'hf-order-031',
    orderSn: 'HF-ORDER-031',
    scenarioType: 'product-full-reduction',
    memberId: 'hf-member-regular-11',
    referrerId: 'hf-member-l1-08',
    shareUserId: 'hf-member-l1-08',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 268,
    freightAmount: 0,
    discountAmount: 20,
    payAmount: 248,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 248,
    receiverName: '连阔',
    receiverPhone: '13900010011',
    receiverAddress: '长沙市岳麓区桐梓坡西路188号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-031',
    createOffsetDays: -2,
    payOffsetDays: -2,
    remark: '临时分佣链路样本：分享人不等于绑定上级',
    items: [
      item('hf-retail-mop-001', 'hf-retail-mop-001-sku-1', 1, 96, {
        activityType: 'FULL_REDUCTION',
        activityNameSnapshot: '周末满减狂欢',
        activityStatusSnapshot: 'SUCCESS',
        commissionRuleSource: 'TEMP_SHARE_OVERRIDE',
        orderItemDiscountAllocated: 8,
        orderItemFinalPaid: 88,
      }),
      item('hf-instant-red-wine-001', 'hf-instant-red-wine-001-sku-1', 1, 92, {
        activityType: 'FULL_REDUCTION',
        activityNameSnapshot: '周末满减狂欢',
        activityStatusSnapshot: 'SUCCESS',
        commissionRuleSource: 'TEMP_SHARE_OVERRIDE',
        orderItemDiscountAllocated: 6,
        orderItemFinalPaid: 86,
      }),
      item('hf-instant-coconut-water-001', 'hf-instant-coconut-water-001-sku-2', 2, 40, {
        activityType: 'FULL_REDUCTION',
        activityNameSnapshot: '周末满减狂欢',
        activityStatusSnapshot: 'SUCCESS',
        commissionRuleSource: 'TEMP_SHARE_OVERRIDE',
        orderItemDiscountAllocated: 6,
        orderItemFinalPaid: 74,
      }),
    ],
    commissions: [
      commission('hf-member-l1-08', 1, 9.92, 248, 248, 'SETTLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'TEMP_SHARE_OVERRIDE',
        orderOriginalPrice: 268,
      }),
      commission('hf-member-l2-04', 2, 14.88, 248, 248, 'SETTLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'TEMP_SHARE_OVERRIDE',
        orderOriginalPrice: 268,
      }),
    ],
  },
  {
    orderId: 'hf-order-032',
    orderSn: 'HF-ORDER-032',
    scenarioType: 'product-normal',
    memberId: 'hf-member-regular-12',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 210,
    freightAmount: 0,
    discountAmount: 30,
    payAmount: 180,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 180,
    receiverName: '祝依',
    receiverPhone: '13900010012',
    receiverAddress: '长沙市雨花区湘府东路219号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-032',
    createOffsetDays: -2,
    payOffsetDays: -2,
    remark: '绑定分佣链路样本：按会员上级关系结算',
    items: [
      item('hf-retail-nuts-gift-001', 'hf-retail-nuts-gift-001-sku-3', 1, 118, {
        commissionRuleSource: 'BINDING_PARENT_CHAIN',
        orderItemDiscountAllocated: 18,
        orderItemFinalPaid: 100,
      }),
      item('hf-instant-blueberry-001', 'hf-instant-blueberry-001-sku-2', 1, 52, {
        commissionRuleSource: 'BINDING_PARENT_CHAIN',
        orderItemDiscountAllocated: 8,
        orderItemFinalPaid: 44,
      }),
      item('hf-instant-oat-milk-001', 'hf-instant-oat-milk-001-sku-2', 1, 40, {
        commissionRuleSource: 'BINDING_PARENT_CHAIN',
        orderItemDiscountAllocated: 4,
        orderItemFinalPaid: 36,
      }),
    ],
    commissions: [
      commission('hf-member-l1-04', 1, 7.2, 180, 180, 'FROZEN', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'BINDING_PARENT_CHAIN',
        orderOriginalPrice: 210,
      }),
      commission('hf-member-l2-02', 2, 10.8, 180, 180, 'FROZEN', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'BINDING_PARENT_CHAIN',
        orderOriginalPrice: 210,
      }),
    ],
  },
  {
    orderId: 'hf-order-033',
    orderSn: 'HF-ORDER-033',
    scenarioType: 'service-course-group',
    memberId: 'hf-member-regular-13',
    referrerId: 'hf-member-l1-04',
    shareUserId: 'hf-member-l1-04',
    orderType: 'SERVICE',
    status: 'PAID',
    payStatus: 'PAID',
    totalAmount: 1099,
    freightAmount: 0,
    discountAmount: 100,
    payAmount: 999,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 620,
    bookingOffsetDays: 2,
    serviceRemark: '临时分享触发拼课佣金样本',
    payType: 'WECHAT',
    transactionId: 'hf-pay-033',
    createOffsetDays: -2,
    payOffsetDays: -2,
    items: [
      item('hf-service-basketball-001', 'hf-service-basketball-001-sku-2', 1, 1099, {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-basketball',
        playInstanceId: 'hf-play-033',
        activityNameSnapshot: '篮球周末拼课',
        activityPriceSnapshot: 999,
        activityStatusSnapshot: 'ACTIVE',
        activityCommissionModeSnapshot: 'INHERIT',
        activityCommissionRateSnapshot: 0.1,
        commissionRuleSource: 'TEMP_ACTIVITY_SHARE',
        commissionPoolSnapshot: 99.9,
        l1WeightSnapshot: 0.4,
        l2WeightSnapshot: 0.6,
        orderItemDiscountAllocated: 100,
        orderItemFinalPaid: 999,
      }),
    ],
    commissions: [
      commission('hf-member-l1-04', 1, 39.96, 999, 999, 'FROZEN', {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-basketball',
        playInstanceId: 'hf-play-033',
        activityCommissionRateSnapshot: 0.1,
        commissionPoolSnapshot: 99.9,
        commissionRuleSource: 'TEMP_ACTIVITY_SHARE',
      }),
      commission('hf-member-l2-02', 2, 59.94, 999, 999, 'FROZEN', {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-basketball',
        playInstanceId: 'hf-play-033',
        activityCommissionRateSnapshot: 0.1,
        commissionPoolSnapshot: 99.9,
        commissionRuleSource: 'TEMP_ACTIVITY_SHARE',
      }),
    ],
    playInstances: [
      {
        playInstanceId: 'hf-play-033',
        configId: 'hf-config-course-basketball',
        templateCode: 'COURSE_GROUP_BUY',
        status: 'ACTIVE',
        bindToItemIndex: 0,
        payOffsetDays: -2,
        instanceData: {
          isLeader: false,
          currentCount: 1,
          targetCount: 2,
          groupPrice: 999,
        },
      },
    ],
  },
  {
    orderId: 'hf-order-034',
    orderSn: 'HF-ORDER-034',
    scenarioType: 'product-normal',
    memberId: 'hf-pending-01',
    referrerId: 'hf-member-l1-01',
    shareUserId: 'hf-member-l1-01',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 143.8,
    freightAmount: 0,
    discountAmount: 18,
    payAmount: 125.8,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 126,
    receiverName: '沈怀',
    receiverPhone: '13900010013',
    receiverAddress: '长沙市开福区芙蓉中路550号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-034',
    createOffsetDays: -1,
    payOffsetDays: -1,
    remark: '分销申请证据单(待审核-1)',
    items: [
      item('hf-retail-cleaner-001', 'hf-retail-cleaner-001-sku-2', 2, 36.9, {
        commissionRuleSource: 'APPLICATION_EVIDENCE_ORDER',
        orderItemDiscountAllocated: 8,
        orderItemFinalPaid: 65.8,
      }),
      item('hf-retail-baby-wipes-001', 'hf-retail-baby-wipes-001-sku-2', 2, 22.55, {
        commissionRuleSource: 'APPLICATION_EVIDENCE_ORDER',
        orderItemDiscountAllocated: 5,
        orderItemFinalPaid: 40.1,
      }),
      item('hf-instant-coconut-water-001', 'hf-instant-coconut-water-001-sku-2', 1, 24.9, {
        commissionRuleSource: 'APPLICATION_EVIDENCE_ORDER',
        orderItemDiscountAllocated: 5,
        orderItemFinalPaid: 19.9,
      }),
    ],
    commissions: [
      commission('hf-member-l1-01', 1, 5.03, 125.8, 125.8, 'FROZEN', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'APPLICATION_EVIDENCE_ORDER',
        orderOriginalPrice: 143.8,
      }),
      commission('hf-member-l2-01', 2, 7.55, 125.8, 125.8, 'FROZEN', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'APPLICATION_EVIDENCE_ORDER',
        orderOriginalPrice: 143.8,
      }),
    ],
  },
  {
    orderId: 'hf-order-035',
    orderSn: 'HF-ORDER-035',
    scenarioType: 'product-flash-sale',
    memberId: 'hf-pending-02',
    referrerId: 'hf-member-l1-02',
    shareUserId: 'hf-member-l1-02',
    orderType: 'PRODUCT',
    status: 'PAID',
    payStatus: 'PAID',
    totalAmount: 59.8,
    freightAmount: 0,
    discountAmount: 10,
    payAmount: 49.8,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 50,
    receiverName: '韩圭',
    receiverPhone: '13900010014',
    receiverAddress: '长沙市天心区湘江中路29号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-035',
    createOffsetDays: -1,
    payOffsetDays: -1,
    remark: '分销申请证据单(待审核-2)',
    items: [
      item('hf-instant-coconut-water-001', 'hf-instant-coconut-water-001-sku-1', 2, 29.9, {
        activityType: 'FLASH_SALE',
        activityConfigId: 'hf-config-flash-coconut',
        activityNameSnapshot: '椰子水限时秒杀',
        activityPriceSnapshot: 24.9,
        activityStatusSnapshot: 'SUCCESS',
        activityCommissionModeSnapshot: 'NONE',
        activityCommissionRateSnapshot: 0,
        commissionRuleSource: 'FLASH_SALE_NONE',
        commissionPoolSnapshot: 0,
        orderItemDiscountAllocated: 10,
        orderItemFinalPaid: 49.8,
      }),
    ],
    commissions: [],
    playInstances: [
      {
        playInstanceId: 'hf-play-035',
        configId: 'hf-config-flash-coconut',
        templateCode: 'FLASH_SALE',
        status: 'SUCCESS',
        bindToItemIndex: 0,
        payOffsetDays: -1,
        endOffsetDays: -1,
        instanceData: {
          flashPrice: 24.9,
          quantity: 2,
          stockLocked: true,
        },
      },
    ],
  },
  {
    orderId: 'hf-order-036',
    orderSn: 'HF-ORDER-036',
    scenarioType: 'service-normal',
    memberId: 'hf-pending-03',
    referrerId: 'hf-member-l1-03',
    shareUserId: 'hf-member-l1-03',
    orderType: 'SERVICE',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 1299,
    freightAmount: 0,
    discountAmount: 100,
    payAmount: 1199,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 700,
    bookingOffsetDays: 2,
    serviceRemark: '分销申请证据单(待审核-3)',
    payType: 'WECHAT',
    transactionId: 'hf-pay-036',
    createOffsetDays: -1,
    payOffsetDays: -1,
    items: [
      item('hf-service-swimming-001', 'hf-service-swimming-001-sku-2', 1, 1299, {
        commissionRuleSource: 'APPLICATION_THRESHOLD_ORDER',
        orderItemDiscountAllocated: 100,
        orderItemFinalPaid: 1199,
      }),
    ],
    commissions: [
      commission('hf-member-l1-03', 1, 47.96, 1199, 1199, 'FROZEN', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'APPLICATION_THRESHOLD_ORDER',
        orderOriginalPrice: 1299,
      }),
      commission('hf-member-l2-02', 2, 71.94, 1199, 1199, 'FROZEN', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'APPLICATION_THRESHOLD_ORDER',
        orderOriginalPrice: 1299,
      }),
    ],
  },
  {
    orderId: 'hf-order-037',
    orderSn: 'HF-ORDER-037',
    scenarioType: 'product-normal',
    memberId: 'hf-pending-04',
    referrerId: 'hf-member-l1-04',
    shareUserId: 'hf-member-l1-04',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 188,
    freightAmount: 0,
    discountAmount: 20,
    payAmount: 168,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 168,
    receiverName: '曲觉',
    receiverPhone: '13900010015',
    receiverAddress: '长沙市雨花区井湾路90号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-037',
    createOffsetDays: -1,
    payOffsetDays: -1,
    remark: '分销申请证据单(待审核-4)',
    items: [
      item('hf-retail-mop-001', 'hf-retail-mop-001-sku-1', 1, 96, {
        commissionRuleSource: 'APPLICATION_PENDING_REVIEW',
        orderItemDiscountAllocated: 10,
        orderItemFinalPaid: 86,
      }),
      item('hf-instant-red-wine-001', 'hf-instant-red-wine-001-sku-1', 1, 92, {
        commissionRuleSource: 'APPLICATION_PENDING_REVIEW',
        orderItemDiscountAllocated: 10,
        orderItemFinalPaid: 82,
      }),
    ],
    commissions: [
      commission('hf-member-l1-04', 1, 6.72, 168, 168, 'FROZEN', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'APPLICATION_PENDING_REVIEW',
        orderOriginalPrice: 188,
      }),
      commission('hf-member-l2-02', 2, 10.08, 168, 168, 'FROZEN', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'APPLICATION_PENDING_REVIEW',
        orderOriginalPrice: 188,
      }),
    ],
  },
  {
    orderId: 'hf-order-038',
    orderSn: 'HF-ORDER-038',
    scenarioType: 'product-normal',
    memberId: 'hf-rejected-01',
    referrerId: 'hf-member-l1-03',
    shareUserId: 'hf-member-l1-03',
    orderType: 'PRODUCT',
    status: 'REFUNDED',
    payStatus: 'REFUNDED',
    totalAmount: 139.8,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 139.8,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 0,
    receiverName: '柏奚',
    receiverPhone: '13900010016',
    receiverAddress: '长沙市岳麓区麓云路77号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-038',
    createOffsetDays: -2,
    payOffsetDays: -2,
    remark: '驳回申请样本-风控拒绝后佣金回滚',
    items: [
      item('hf-instant-cherry-001', 'hf-instant-cherry-001-sku-1', 1, 39.8, {
        commissionRuleSource: 'RISK_REJECTED_REVOKE',
        orderItemFinalPaid: 39.8,
      }),
      item('hf-instant-red-wine-001', 'hf-instant-red-wine-001-sku-1', 1, 100, {
        commissionRuleSource: 'RISK_REJECTED_REVOKE',
        orderItemFinalPaid: 100,
      }),
    ],
    commissions: [
      commission('hf-member-l1-03', 1, 5.59, 139.8, 139.8, 'CANCELLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'RISK_REJECTED_REVOKE',
        settleOffsetDays: null,
      }),
      commission('hf-member-l2-02', 2, 8.39, 139.8, 139.8, 'CANCELLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'RISK_REJECTED_REVOKE',
        settleOffsetDays: null,
      }),
    ],
  },
  {
    orderId: 'hf-order-039',
    orderSn: 'HF-ORDER-039',
    scenarioType: 'service-course-group',
    memberId: 'hf-rejected-02',
    referrerId: 'hf-member-l1-04',
    shareUserId: 'hf-member-l1-04',
    orderType: 'SERVICE',
    status: 'REFUNDED',
    payStatus: 'REFUNDED',
    totalAmount: 799,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 799,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 0,
    bookingOffsetDays: 0,
    serviceRemark: '驳回申请样本-拼课超时退款',
    payType: 'WECHAT',
    transactionId: 'hf-pay-039',
    createOffsetDays: -2,
    payOffsetDays: -2,
    items: [
      item('hf-service-art-001', 'hf-service-art-001-sku-2', 1, 799, {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-art',
        playInstanceId: 'hf-play-039',
        activityNameSnapshot: '创意绘画拼课',
        activityStatusSnapshot: 'TIMEOUT',
        activityCommissionModeSnapshot: 'INHERIT',
        activityCommissionRateSnapshot: 0.1,
        commissionRuleSource: 'REJECTED_TIMEOUT_REVOKE',
        commissionPoolSnapshot: 79.9,
      }),
    ],
    commissions: [
      commission('hf-member-l1-04', 1, 31.96, 799, 799, 'CANCELLED', {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-art',
        playInstanceId: 'hf-play-039',
        commissionRuleSource: 'REJECTED_TIMEOUT_REVOKE',
        settleOffsetDays: null,
      }),
      commission('hf-member-l2-02', 2, 47.94, 799, 799, 'CANCELLED', {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-art',
        playInstanceId: 'hf-play-039',
        commissionRuleSource: 'REJECTED_TIMEOUT_REVOKE',
        settleOffsetDays: null,
      }),
    ],
    playInstances: [
      {
        playInstanceId: 'hf-play-039',
        configId: 'hf-config-course-art',
        templateCode: 'COURSE_GROUP_BUY',
        status: 'TIMEOUT',
        bindToItemIndex: 0,
        payOffsetDays: -2,
        endOffsetDays: -1,
        instanceData: {
          isLeader: false,
          currentCount: 1,
          targetCount: 2,
          groupPrice: 799,
        },
      },
    ],
  },
  {
    orderId: 'hf-order-040',
    orderSn: 'HF-ORDER-040',
    scenarioType: 'product-normal',
    memberId: 'hf-black-01',
    referrerId: 'hf-member-l1-08',
    shareUserId: 'hf-member-l1-08',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 166,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 166,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 166,
    receiverName: '魏邰',
    receiverPhone: '13900010017',
    receiverAddress: '长沙市望城区金星北路55号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-040',
    createOffsetDays: -3,
    payOffsetDays: -3,
    remark: '黑名单申请样本：有订单但佣金被风控阻断',
    items: [
      item('hf-instant-cherry-001', 'hf-instant-cherry-001-sku-1', 2, 38, {
        commissionRuleSource: 'BLACKLIST_BLOCK',
      }),
      item('hf-instant-red-wine-001', 'hf-instant-red-wine-001-sku-1', 1, 90, {
        commissionRuleSource: 'BLACKLIST_BLOCK',
      }),
    ],
    commissions: [
      commission('hf-member-l1-08', 1, 6.64, 166, 166, 'CANCELLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'BLACKLIST_BLOCK',
        settleOffsetDays: null,
      }),
      commission('hf-member-l2-04', 2, 9.96, 166, 166, 'CANCELLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'BLACKLIST_BLOCK',
        settleOffsetDays: null,
      }),
    ],
  },
  {
    orderId: 'hf-order-041',
    orderSn: 'HF-ORDER-041',
    scenarioType: 'member-upgrade',
    memberId: 'hf-member-regular-07',
    referrerId: 'hf-member-l1-07',
    shareUserId: 'hf-member-l1-07',
    orderType: 'SERVICE',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 499,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 499,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 160,
    serviceRemark: '升级申请关联订单',
    payType: 'WECHAT',
    transactionId: 'hf-pay-041',
    createOffsetDays: -3,
    payOffsetDays: -3,
    remark: '对应升级申请: hf-member-regular-07',
    items: [
      item('hf-service-scratch-001', 'hf-service-scratch-001-sku-1', 1, 499, {
        activityType: 'MEMBER_UPGRADE',
        activityConfigId: 'hf-config-upgrade-scratch',
        activityNameSnapshot: '成长会员升级包',
        activityStatusSnapshot: 'SUCCESS',
        activityCommissionModeSnapshot: 'NONE',
        activityCommissionRateSnapshot: 0,
        commissionRuleSource: 'ACTIVITY_NONE_ZERO',
        commissionPoolSnapshot: 0,
      }),
    ],
    commissions: [
      commission('hf-member-l1-07', 1, 0, 0, 499, 'SETTLED', {
        commissionBaseType: 'ZERO',
        commissionRuleSource: 'ACTIVITY_NONE_ZERO',
        orderOriginalPrice: 499,
        settleOffsetDays: 1,
      }),
      commission('hf-member-l2-04', 2, 0, 0, 499, 'SETTLED', {
        commissionBaseType: 'ZERO',
        commissionRuleSource: 'ACTIVITY_NONE_ZERO',
        orderOriginalPrice: 499,
        settleOffsetDays: 1,
      }),
    ],
  },
  {
    orderId: 'hf-order-042',
    orderSn: 'HF-ORDER-042',
    scenarioType: 'product-flash-sale',
    memberId: 'hf-member-regular-08',
    referrerId: 'hf-member-l1-07',
    shareUserId: 'hf-member-l1-07',
    orderType: 'PRODUCT',
    status: 'PAID',
    payStatus: 'PAID',
    totalAmount: 89.7,
    freightAmount: 0,
    discountAmount: 15,
    payAmount: 74.7,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 75,
    receiverName: '柳濯',
    receiverPhone: '13900010018',
    receiverAddress: '长沙市天心区友谊路311号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-042',
    createOffsetDays: -1,
    payOffsetDays: -1,
    remark: '场景触达补充样本：候选分销员持续活跃',
    items: [
      item('hf-instant-coconut-water-001', 'hf-instant-coconut-water-001-sku-1', 3, 29.9, {
        activityType: 'FLASH_SALE',
        activityConfigId: 'hf-config-flash-coconut',
        activityNameSnapshot: '椰子水限时秒杀',
        activityPriceSnapshot: 24.9,
        activityStatusSnapshot: 'SUCCESS',
        activityCommissionModeSnapshot: 'NONE',
        activityCommissionRateSnapshot: 0,
        commissionRuleSource: 'FLASH_SALE_NONE',
        commissionPoolSnapshot: 0,
        orderItemDiscountAllocated: 15,
        orderItemFinalPaid: 74.7,
      }),
    ],
    commissions: [],
    playInstances: [
      {
        playInstanceId: 'hf-play-042',
        configId: 'hf-config-flash-coconut',
        templateCode: 'FLASH_SALE',
        status: 'SUCCESS',
        bindToItemIndex: 0,
        payOffsetDays: -1,
        endOffsetDays: -1,
        instanceData: {
          flashPrice: 24.9,
          quantity: 3,
          stockLocked: true,
        },
      },
    ],
  },
  {
    orderId: 'hf-order-043',
    orderSn: 'HF-ORDER-043',
    scenarioType: 'refund-full',
    memberId: 'hf-rejected-03',
    referrerId: 'hf-member-l1-05',
    shareUserId: 'hf-member-l1-05',
    orderType: 'PRODUCT',
    status: 'REFUNDED',
    payStatus: 'REFUNDED',
    totalAmount: 120,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 120,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 0,
    receiverName: '温霁',
    receiverPhone: '13900010019',
    receiverAddress: '长沙市岳麓区谷苑路66号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-043',
    createOffsetDays: -2,
    payOffsetDays: -2,
    remark: '驳回申请样本-售后全额退款',
    items: [
      item('hf-retail-mop-001', 'hf-retail-mop-001-sku-2', 1, 120, {
        commissionRuleSource: 'REJECTED_AFTERSALES_REVOKE',
        orderItemFinalPaid: 120,
      }),
    ],
    commissions: [
      commission('hf-member-l1-05', 1, 4.8, 120, 120, 'CANCELLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'REJECTED_AFTERSALES_REVOKE',
        settleOffsetDays: null,
      }),
      commission('hf-member-l2-03', 2, 7.2, 120, 120, 'CANCELLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'REJECTED_AFTERSALES_REVOKE',
        settleOffsetDays: null,
      }),
    ],
  },
  {
    orderId: 'hf-order-044',
    orderSn: 'HF-ORDER-044',
    scenarioType: 'mixed-marketing',
    memberId: 'hf-member-regular-09',
    referrerId: 'hf-member-l1-07',
    shareUserId: 'hf-member-l1-07',
    orderType: 'MIXED',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 667.9,
    freightAmount: 0,
    discountAmount: 70,
    payAmount: 597.9,
    couponDiscount: 15,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 398,
    receiverName: '邹宁',
    receiverPhone: '13900010020',
    receiverAddress: '长沙市岳麓区含浦大道89号',
    bookingOffsetDays: 3,
    serviceRemark: '新人专享混合单，临时分享触发服务+商品联动',
    payType: 'WECHAT',
    transactionId: 'hf-pay-044',
    createOffsetDays: -3,
    payOffsetDays: -3,
    remark: '混合订单样本：新人价 + 秒杀 + 临时分享佣金',
    items: [
      item('hf-service-scratch-001', 'hf-service-scratch-001-sku-1', 1, 499, {
        commissionRuleSource: 'TEMP_SHARE_NEWCOMER',
        orderItemDiscountAllocated: 30,
        orderItemFinalPaid: 469,
        attribution: {
          sourceSceneCodeSnapshot: 'HF_SCENE_NEWCOMER',
          sourceModuleCodeSnapshot: 'HF_NEWCOMER_PRICE',
          sourceChannelSnapshot: 'miniapp',
          sourcePagePathSnapshot: '/pages/newcomer/index',
          shareUserIdSnapshot: 'hf-member-l1-07',
          referrerIdSnapshot: 'hf-member-l1-07',
          cardTemplateCodeSnapshot: 'HF_CARD_HERO',
          resolverPolicyCodeSnapshot: 'HF_RESOLVER_TEMP_SHARE',
          resolverReleaseNoSnapshot: 2,
          audienceSnapshot: { mode: 'NEW_MEMBER' },
          secondaryBenefitsSnapshot: { newcomerBundle: true },
          denyStackReasonsSnapshot: [],
          entryContextSnapshot: { entry: 'newcomer-mixed' },
        },
      }),
      item('hf-retail-powerbank-001', 'hf-retail-powerbank-001-sku-1', 1, 139, {
        activityType: 'NEWCOMER_EXCLUSIVE',
        activityConfigId: 'hf-config-newcomer-powerbank',
        activityNameSnapshot: '新人专享爆品',
        activityPriceSnapshot: 104,
        activityStatusSnapshot: 'SUCCESS',
        activityCommissionModeSnapshot: 'INHERIT',
        activityCommissionRateSnapshot: 0.1,
        commissionRuleSource: 'TEMP_SHARE_NEWCOMER',
        commissionPoolSnapshot: 57.3,
        l1WeightSnapshot: 0.4,
        l2WeightSnapshot: 0.6,
        orderItemDiscountAllocated: 35,
        orderItemFinalPaid: 104,
        attribution: {
          sourceSceneCodeSnapshot: 'HF_SCENE_NEWCOMER',
          sourceModuleCodeSnapshot: 'HF_NEWCOMER_PRICE',
          sourceChannelSnapshot: 'miniapp',
          sourcePagePathSnapshot: '/pages/newcomer/index',
          shareUserIdSnapshot: 'hf-member-l1-07',
          referrerIdSnapshot: 'hf-member-l1-07',
          cardTemplateCodeSnapshot: 'HF_CARD_HERO',
          resolverPolicyCodeSnapshot: 'HF_RESOLVER_TEMP_SHARE',
          resolverReleaseNoSnapshot: 2,
          audienceSnapshot: { mode: 'NEW_MEMBER' },
          secondaryBenefitsSnapshot: { newcomerPrice: true },
          denyStackReasonsSnapshot: [],
          entryContextSnapshot: { entry: 'newcomer-card' },
        },
      }),
      item('hf-instant-coconut-water-001', 'hf-instant-coconut-water-001-sku-1', 1, 29.9, {
        activityType: 'FLASH_SALE',
        activityConfigId: 'hf-config-flash-coconut-night',
        activityNameSnapshot: '椰子水晚场秒杀',
        activityPriceSnapshot: 24.9,
        activityStatusSnapshot: 'SUCCESS',
        activityCommissionModeSnapshot: 'NONE',
        activityCommissionRateSnapshot: 0,
        commissionRuleSource: 'FLASH_SALE_NONE',
        commissionPoolSnapshot: 0,
        l1WeightSnapshot: 0,
        l2WeightSnapshot: 0,
        orderItemDiscountAllocated: 5,
        orderItemFinalPaid: 24.9,
        attribution: {
          sourceSceneCodeSnapshot: 'HF_SCENE_FLASH',
          sourceModuleCodeSnapshot: 'HF_FLASH_TODAY',
          sourceChannelSnapshot: 'miniapp',
          sourcePagePathSnapshot: '/pages/marketing/flash',
          shareUserIdSnapshot: 'hf-member-l1-07',
          referrerIdSnapshot: 'hf-member-l1-07',
          cardTemplateCodeSnapshot: 'HF_CARD_SIMPLE',
          resolverPolicyCodeSnapshot: 'HF_RESOLVER_DEFAULT',
          resolverReleaseNoSnapshot: 1,
          audienceSnapshot: { mode: 'ALL' },
          secondaryBenefitsSnapshot: { flashSale: true },
          denyStackReasonsSnapshot: [],
          entryContextSnapshot: { entry: 'flash-zone' },
        },
      }),
    ],
    commissions: [
      commission('hf-member-l1-07', 1, 22.92, 573, 597.9, 'FROZEN', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'TEMP_SHARE_NEWCOMER',
        orderOriginalPrice: 638,
        couponDiscount: 15,
        planSettleOffsetDays: 21,
      }),
      commission('hf-member-l2-04', 2, 34.38, 573, 597.9, 'FROZEN', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'TEMP_SHARE_NEWCOMER',
        orderOriginalPrice: 638,
        couponDiscount: 15,
        planSettleOffsetDays: 21,
      }),
    ],
  },
  {
    orderId: 'hf-order-045',
    orderSn: 'HF-ORDER-045',
    scenarioType: 'product-full-reduction',
    memberId: 'hf-member-regular-10',
    referrerId: 'hf-member-l1-02',
    shareUserId: 'hf-member-l1-02',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 322,
    freightAmount: 0,
    discountAmount: 52,
    payAmount: 270,
    couponDiscount: 12,
    pointsUsed: 1000,
    pointsDiscount: 10,
    pointsEarned: 235,
    receiverName: '蓝槿',
    receiverPhone: '13900010021',
    receiverAddress: '长沙市开福区湘雅路108号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-045',
    createOffsetDays: -5,
    payOffsetDays: -5,
    remark: '手工兜底样本：原价佣金保护 + 满减大单',
    items: [
      item('hf-retail-earbud-001', 'hf-retail-earbud-001-sku-1', 1, 119, {
        activityType: 'FULL_REDUCTION',
        activityNameSnapshot: '周末满减狂欢',
        activityStatusSnapshot: 'SUCCESS',
        commissionRuleSource: 'MANUAL_BACKSTOP_ORIGINAL',
        orderItemDiscountAllocated: 18,
        orderItemFinalPaid: 101,
        attribution: {
          sourceSceneCodeSnapshot: 'HF_SCENE_HOME',
          sourceModuleCodeSnapshot: 'HF_HOME_GOODS',
          sourceChannelSnapshot: 'miniapp',
          sourcePagePathSnapshot: '/pages/index/index',
          shareUserIdSnapshot: 'hf-member-l1-02',
          referrerIdSnapshot: 'hf-member-l1-02',
          cardTemplateCodeSnapshot: 'HF_CARD_HERO',
          resolverPolicyCodeSnapshot: 'HF_RESOLVER_DEFAULT',
          resolverReleaseNoSnapshot: 1,
          audienceSnapshot: { mode: 'ALL' },
          secondaryBenefitsSnapshot: { couponCode: 'HF-CPN-HOME-12' },
          denyStackReasonsSnapshot: [],
          entryContextSnapshot: { entry: 'home-goods' },
        },
      }),
      item('hf-retail-powerbank-001', 'hf-retail-powerbank-001-sku-1', 1, 139, {
        activityType: 'FULL_REDUCTION',
        activityNameSnapshot: '周末满减狂欢',
        activityStatusSnapshot: 'SUCCESS',
        commissionRuleSource: 'MANUAL_BACKSTOP_ORIGINAL',
        orderItemDiscountAllocated: 24,
        orderItemFinalPaid: 115,
      }),
      item('hf-retail-baby-shampoo-001', 'hf-retail-baby-shampoo-001-sku-1', 1, 64, {
        activityType: 'FULL_REDUCTION',
        activityNameSnapshot: '周末满减狂欢',
        activityStatusSnapshot: 'SUCCESS',
        commissionRuleSource: 'MANUAL_BACKSTOP_ORIGINAL',
        orderItemDiscountAllocated: 10,
        orderItemFinalPaid: 54,
      }),
    ],
    commissions: [
      commission('hf-member-l1-02', 1, 12.88, 322, 270, 'SETTLED', {
        commissionBaseType: 'ORIGINAL_PRICE',
        commissionRuleSource: 'MANUAL_BACKSTOP_ORIGINAL',
        orderOriginalPrice: 322,
        couponDiscount: 12,
        pointsDiscount: 10,
        planSettleOffsetDays: 14,
        settleOffsetDays: 16,
      }),
      commission('hf-member-l2-01', 2, 19.32, 322, 270, 'SETTLED', {
        commissionBaseType: 'ORIGINAL_PRICE',
        commissionRuleSource: 'MANUAL_BACKSTOP_ORIGINAL',
        orderOriginalPrice: 322,
        couponDiscount: 12,
        pointsDiscount: 10,
        planSettleOffsetDays: 14,
        settleOffsetDays: 16,
      }),
    ],
  },
  {
    orderId: 'hf-order-046',
    orderSn: 'HF-ORDER-046',
    scenarioType: 'service-course-group',
    memberId: 'hf-member-regular-14',
    referrerId: 'hf-member-l1-03',
    shareUserId: 'hf-member-l1-03',
    orderType: 'SERVICE',
    status: 'PAID',
    payStatus: 'PAID',
    totalAmount: 1099,
    freightAmount: 0,
    discountAmount: 160,
    payAmount: 939,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 560,
    bookingOffsetDays: 4,
    serviceRemark: '课程拼课冻结期样本，等待成团后再结算',
    payType: 'WECHAT',
    transactionId: 'hf-pay-046',
    createOffsetDays: -2,
    payOffsetDays: -2,
    remark: '临时分享拼课样本：非绑定上级且延迟结算',
    items: [
      item('hf-service-basketball-001', 'hf-service-basketball-001-sku-2', 1, 1099, {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-basketball-delayed',
        playInstanceId: 'hf-play-046',
        activityNameSnapshot: '篮球冲刺拼课',
        activityPriceSnapshot: 939,
        activityStatusSnapshot: 'ACTIVE',
        activityCommissionModeSnapshot: 'INHERIT',
        activityCommissionRateSnapshot: 0.1,
        commissionRuleSource: 'TEMP_ACTIVITY_SHARE_DELAYED',
        commissionPoolSnapshot: 93.9,
        l1WeightSnapshot: 0.4,
        l2WeightSnapshot: 0.6,
        orderItemDiscountAllocated: 160,
        orderItemFinalPaid: 939,
        attribution: {
          sourceSceneCodeSnapshot: 'HF_SCENE_COURSE',
          sourceModuleCodeSnapshot: 'HF_COURSE_GROUP',
          sourceChannelSnapshot: 'miniapp',
          sourcePagePathSnapshot: '/pages/course/group',
          shareUserIdSnapshot: 'hf-member-l1-03',
          referrerIdSnapshot: 'hf-member-l1-03',
          cardTemplateCodeSnapshot: 'HF_CARD_HERO',
          resolverPolicyCodeSnapshot: 'HF_RESOLVER_TEMP_SHARE',
          resolverReleaseNoSnapshot: 2,
          audienceSnapshot: { mode: 'ALL' },
          secondaryBenefitsSnapshot: { groupBuy: true },
          denyStackReasonsSnapshot: [],
          entryContextSnapshot: { entry: 'course-group' },
        },
      }),
    ],
    commissions: [
      commission('hf-member-l1-03', 1, 37.56, 939, 939, 'FROZEN', {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-basketball-delayed',
        playInstanceId: 'hf-play-046',
        activityCommissionRateSnapshot: 0.1,
        commissionPoolSnapshot: 93.9,
        commissionRuleSource: 'TEMP_ACTIVITY_SHARE_DELAYED',
        planSettleOffsetDays: 21,
      }),
      commission('hf-member-l2-02', 2, 56.34, 939, 939, 'FROZEN', {
        activityType: 'COURSE_GROUP_BUY',
        activityConfigId: 'hf-config-course-basketball-delayed',
        playInstanceId: 'hf-play-046',
        activityCommissionRateSnapshot: 0.1,
        commissionPoolSnapshot: 93.9,
        commissionRuleSource: 'TEMP_ACTIVITY_SHARE_DELAYED',
        planSettleOffsetDays: 21,
      }),
    ],
    playInstances: [
      {
        playInstanceId: 'hf-play-046',
        configId: 'hf-config-course-basketball-delayed',
        templateCode: 'COURSE_GROUP_BUY',
        status: 'ACTIVE',
        bindToItemIndex: 0,
        payOffsetDays: -2,
        instanceData: {
          isLeader: false,
          currentCount: 2,
          targetCount: 3,
          groupPrice: 939,
        },
      },
    ],
  },
  {
    orderId: 'hf-order-047',
    orderSn: 'HF-ORDER-047',
    scenarioType: 'refund-partial',
    memberId: 'hf-freeze-01',
    referrerId: 'hf-member-l1-05',
    shareUserId: 'hf-member-l1-05',
    orderType: 'PRODUCT',
    status: 'REFUNDED',
    payStatus: 'REFUNDED',
    totalAmount: 286.8,
    freightAmount: 0,
    discountAmount: 36,
    payAmount: 250.8,
    couponDiscount: 20,
    pointsUsed: 1600,
    pointsDiscount: 16,
    pointsEarned: 130,
    receiverName: '商沐',
    receiverPhone: '13900010022',
    receiverAddress: '长沙市雨花区曲塘路120号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-047',
    createOffsetDays: -6,
    payOffsetDays: -6,
    remark: '部分退款样本：售后保留 + 风控拒绝并存',
    items: [
      item('hf-retail-powerbank-001', 'hf-retail-powerbank-001-sku-2', 1, 149.8, {
        commissionRuleSource: 'MANUAL_AFTERSALES_KEEP',
        orderItemDiscountAllocated: 18,
        orderItemFinalPaid: 131.8,
        attribution: {
          sourceSceneCodeSnapshot: 'HF_SCENE_HOME',
          sourceModuleCodeSnapshot: 'HF_HOME_GOODS',
          sourceChannelSnapshot: 'miniapp',
          sourcePagePathSnapshot: '/pages/index/index',
          shareUserIdSnapshot: 'hf-member-l1-05',
          referrerIdSnapshot: 'hf-member-l1-05',
          cardTemplateCodeSnapshot: 'HF_CARD_HERO',
          resolverPolicyCodeSnapshot: 'HF_RESOLVER_DEFAULT',
          resolverReleaseNoSnapshot: 1,
          audienceSnapshot: { mode: 'ALL' },
          secondaryBenefitsSnapshot: { afterSalesProtected: true },
          denyStackReasonsSnapshot: [],
          entryContextSnapshot: { entry: 'home-goods' },
        },
      }),
      item('hf-retail-nuts-gift-001', 'hf-retail-nuts-gift-001-sku-3', 1, 137, {
        commissionRuleSource: 'RISK_REVIEW_REJECT_AFTERSALE',
        orderItemDiscountAllocated: 18,
        orderItemFinalPaid: 119,
      }),
    ],
    commissions: [
      commission('hf-member-l1-05', 1, 5.27, 131.8, 250.8, 'SETTLED', {
        itemIndex: 0,
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'MANUAL_AFTERSALES_KEEP',
        couponDiscount: 20,
        pointsDiscount: 16,
        orderOriginalPrice: 286.8,
        settleOffsetDays: 12,
      }),
      commission('hf-member-l2-03', 2, 7.14, 119, 250.8, 'CANCELLED', {
        itemIndex: 1,
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'RISK_REVIEW_REJECT_AFTERSALE',
        couponDiscount: 20,
        pointsDiscount: 16,
        orderOriginalPrice: 286.8,
        settleOffsetDays: null,
      }),
    ],
  },
  {
    orderId: 'hf-order-048',
    orderSn: 'HF-ORDER-048',
    scenarioType: 'member-upgrade',
    memberId: 'hf-member-regular-16',
    referrerId: 'hf-member-l1-08',
    shareUserId: 'hf-member-l1-08',
    orderType: 'SERVICE',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 699,
    freightAmount: 0,
    discountAmount: 0,
    payAmount: 699,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 280,
    serviceRemark: '一级分销升级权益包',
    payType: 'WECHAT',
    transactionId: 'hf-pay-048',
    createOffsetDays: -4,
    payOffsetDays: -4,
    remark: '升级申请证据单：零佣金基数升级包',
    items: [
      item('hf-service-scratch-001', 'hf-service-scratch-001-sku-2', 1, 699, {
        activityType: 'MEMBER_UPGRADE',
        activityConfigId: 'hf-config-upgrade-growth',
        activityNameSnapshot: '成长合伙人升级包',
        activityPriceSnapshot: 699,
        activityStatusSnapshot: 'SUCCESS',
        activityCommissionModeSnapshot: 'NONE',
        activityCommissionRateSnapshot: 0,
        commissionRuleSource: 'ACTIVITY_NONE_ZERO',
        commissionPoolSnapshot: 0,
        attribution: {
          sourceSceneCodeSnapshot: 'HF_SCENE_HOME',
          sourceModuleCodeSnapshot: 'HF_HOME_GOODS',
          sourceChannelSnapshot: 'miniapp',
          sourcePagePathSnapshot: '/pages/upgrade/index',
          shareUserIdSnapshot: 'hf-member-l1-08',
          referrerIdSnapshot: 'hf-member-l1-08',
          cardTemplateCodeSnapshot: 'HF_CARD_HERO',
          resolverPolicyCodeSnapshot: 'HF_RESOLVER_DEFAULT',
          resolverReleaseNoSnapshot: 1,
          audienceSnapshot: { mode: 'ALL' },
          secondaryBenefitsSnapshot: { upgradePackage: true },
          denyStackReasonsSnapshot: [],
          entryContextSnapshot: { entry: 'upgrade-center' },
        },
      }),
    ],
    commissions: [
      commission('hf-member-l1-08', 1, 0, 0, 699, 'SETTLED', {
        commissionBaseType: 'ZERO',
        commissionRuleSource: 'ACTIVITY_NONE_ZERO',
        orderOriginalPrice: 699,
        settleOffsetDays: 1,
      }),
      commission('hf-member-l2-04', 2, 0, 0, 699, 'SETTLED', {
        commissionBaseType: 'ZERO',
        commissionRuleSource: 'ACTIVITY_NONE_ZERO',
        orderOriginalPrice: 699,
        settleOffsetDays: 1,
      }),
    ],
  },
  {
    orderId: 'hf-order-049',
    orderSn: 'HF-ORDER-049',
    scenarioType: 'product-normal',
    memberId: 'hf-member-regular-15',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 188,
    freightAmount: 0,
    discountAmount: 8,
    payAmount: 180,
    couponDiscount: 3,
    pointsUsed: 500,
    pointsDiscount: 5,
    pointsEarned: 180,
    receiverName: '季轶',
    receiverPhone: '13900010023',
    receiverAddress: '长沙市芙蓉区远大一路76号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-049',
    createOffsetDays: -7,
    payOffsetDays: -7,
    remark: '绑定分佣样本：无分享人，按 parent/indirect 链延期结算',
    items: [
      item('hf-retail-mop-001', 'hf-retail-mop-001-sku-1', 1, 96, {
        commissionRuleSource: 'BINDING_DELAY_SETTLE',
        orderItemDiscountAllocated: 4,
        orderItemFinalPaid: 92,
        attribution: {
          sourceSceneCodeSnapshot: 'HF_SCENE_HOME',
          sourceModuleCodeSnapshot: 'HF_HOME_GOODS',
          sourceChannelSnapshot: 'miniapp',
          sourcePagePathSnapshot: '/pages/index/index',
          shareUserIdSnapshot: null,
          referrerIdSnapshot: null,
          cardTemplateCodeSnapshot: 'HF_CARD_HERO',
          resolverPolicyCodeSnapshot: 'HF_RESOLVER_BINDING',
          resolverReleaseNoSnapshot: 2,
          audienceSnapshot: { mode: 'ALL' },
          secondaryBenefitsSnapshot: { pointsDeduct: true },
          denyStackReasonsSnapshot: [],
          entryContextSnapshot: { entry: 'member-center' },
        },
      }),
      item('hf-instant-blueberry-001', 'hf-instant-blueberry-001-sku-2', 1, 52, {
        commissionRuleSource: 'BINDING_DELAY_SETTLE',
        orderItemDiscountAllocated: 3,
        orderItemFinalPaid: 49,
      }),
      item('hf-instant-oat-milk-001', 'hf-instant-oat-milk-001-sku-2', 1, 40, {
        commissionRuleSource: 'BINDING_DELAY_SETTLE',
        orderItemDiscountAllocated: 1,
        orderItemFinalPaid: 39,
      }),
    ],
    commissions: [
      commission('hf-member-l1-07', 1, 7.2, 180, 180, 'SETTLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'BINDING_DELAY_SETTLE',
        orderOriginalPrice: 188,
        couponDiscount: 3,
        pointsDiscount: 5,
        planSettleOffsetDays: 18,
        settleOffsetDays: 24,
      }),
      commission('hf-member-l2-04', 2, 10.8, 180, 180, 'SETTLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'BINDING_DELAY_SETTLE',
        orderOriginalPrice: 188,
        couponDiscount: 3,
        pointsDiscount: 5,
        planSettleOffsetDays: 18,
        settleOffsetDays: 24,
      }),
    ],
  },
  {
    orderId: 'hf-order-050',
    orderSn: 'HF-ORDER-050',
    scenarioType: 'product-normal',
    memberId: 'hf-black-02',
    referrerId: 'hf-member-l1-02',
    shareUserId: 'hf-member-l1-02',
    orderType: 'PRODUCT',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 258.9,
    freightAmount: 0,
    discountAmount: 20,
    payAmount: 238.9,
    couponDiscount: 0,
    pointsUsed: 0,
    pointsDiscount: 0,
    pointsEarned: 239,
    receiverName: '童淮',
    receiverPhone: '13900010024',
    receiverAddress: '长沙市望城区银杉路99号',
    payType: 'WECHAT',
    transactionId: 'hf-pay-050',
    createOffsetDays: -3,
    payOffsetDays: -3,
    remark: '黑名单阻断样本：有成交但佣金与升级均被拒绝',
    items: [
      item('hf-retail-earbud-001', 'hf-retail-earbud-001-sku-2', 1, 159, {
        commissionRuleSource: 'BLACKLIST_BLOCK',
        orderItemDiscountAllocated: 10,
        orderItemFinalPaid: 149,
        attribution: {
          sourceSceneCodeSnapshot: 'HF_SCENE_HOME',
          sourceModuleCodeSnapshot: 'HF_HOME_INSTANT',
          sourceChannelSnapshot: 'miniapp',
          sourcePagePathSnapshot: '/pages/index/index',
          shareUserIdSnapshot: 'hf-member-l1-02',
          referrerIdSnapshot: 'hf-member-l1-02',
          cardTemplateCodeSnapshot: 'HF_CARD_SIMPLE',
          resolverPolicyCodeSnapshot: 'HF_RESOLVER_RISK_GUARD',
          resolverReleaseNoSnapshot: 2,
          audienceSnapshot: { mode: 'ALL' },
          secondaryBenefitsSnapshot: { blacklistCheck: true },
          denyStackReasonsSnapshot: ['BLACKLIST_MEMBER'],
          entryContextSnapshot: { entry: 'instant-zone' },
        },
      }),
      item('hf-instant-craft-beer-001', 'hf-instant-craft-beer-001-sku-1', 1, 59.9, {
        commissionRuleSource: 'BLACKLIST_BLOCK',
        orderItemDiscountAllocated: 5,
        orderItemFinalPaid: 54.9,
      }),
      item('hf-retail-baby-wipes-001', 'hf-retail-baby-wipes-001-sku-3', 1, 40, {
        commissionRuleSource: 'BLACKLIST_BLOCK',
        orderItemDiscountAllocated: 5,
        orderItemFinalPaid: 35,
      }),
    ],
    commissions: [
      commission('hf-member-l1-02', 1, 9.56, 238.9, 238.9, 'CANCELLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'BLACKLIST_BLOCK',
        orderOriginalPrice: 258.9,
        settleOffsetDays: null,
      }),
      commission('hf-member-l2-01', 2, 14.33, 238.9, 238.9, 'CANCELLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'BLACKLIST_BLOCK',
        orderOriginalPrice: 258.9,
        settleOffsetDays: null,
      }),
    ],
  },
  {
    orderId: 'hf-order-051',
    orderSn: 'HF-ORDER-051',
    scenarioType: 'service-normal',
    memberId: 'hf-member-l1-08',
    referrerId: 'hf-member-l2-04',
    shareUserId: 'hf-member-l2-04',
    orderType: 'SERVICE',
    status: 'COMPLETED',
    payStatus: 'PAID',
    totalAmount: 1580,
    freightAmount: 0,
    discountAmount: 180,
    payAmount: 1400,
    couponDiscount: 100,
    pointsUsed: 8000,
    pointsDiscount: 80,
    pointsEarned: 860,
    bookingOffsetDays: 5,
    serviceRemark: '升级二级分销待复核课程包',
    payType: 'WECHAT',
    transactionId: 'hf-pay-051',
    createOffsetDays: -8,
    payOffsetDays: -8,
    remark: '手工兜底样本：服务类大单延期结算并作为升级申请证据',
    items: [
      item('hf-service-piano-001', 'hf-service-piano-001-sku-2', 1, 1580, {
        commissionRuleSource: 'MANUAL_REVIEW_BACKSTOP',
        orderItemDiscountAllocated: 180,
        orderItemFinalPaid: 1400,
        attribution: {
          sourceSceneCodeSnapshot: 'HF_SCENE_COURSE',
          sourceModuleCodeSnapshot: 'HF_COURSE_RECOMMEND',
          sourceChannelSnapshot: 'miniapp',
          sourcePagePathSnapshot: '/pages/course/recommend',
          shareUserIdSnapshot: 'hf-member-l2-04',
          referrerIdSnapshot: 'hf-member-l2-04',
          cardTemplateCodeSnapshot: 'HF_CARD_HERO',
          resolverPolicyCodeSnapshot: 'HF_RESOLVER_MANUAL_BACKSTOP',
          resolverReleaseNoSnapshot: 2,
          audienceSnapshot: { mode: 'ALL' },
          secondaryBenefitsSnapshot: { serviceThreshold: true },
          denyStackReasonsSnapshot: [],
          entryContextSnapshot: { entry: 'course-recommend' },
        },
      }),
    ],
    commissions: [
      commission('hf-member-l2-04', 1, 56, 1400, 1400, 'SETTLED', {
        commissionBaseType: 'ACTUAL_PAID',
        commissionRuleSource: 'MANUAL_REVIEW_BACKSTOP',
        orderOriginalPrice: 1580,
        couponDiscount: 100,
        pointsDiscount: 80,
        planSettleOffsetDays: 30,
        settleOffsetDays: 36,
      }),
    ],
  },
];
