/**
 * 业务操作日志动作编码（写入 biz_operation_log.action，前端可映射中文）
 */
export const BizOperationActions = {
  ORDER_REASSIGN_WORKER: 'ORDER_REASSIGN_WORKER',
  ORDER_VERIFY: 'ORDER_VERIFY',
  ORDER_REFUND: 'ORDER_REFUND',
  ORDER_PARTIAL_REFUND: 'ORDER_PARTIAL_REFUND',
  ORDER_PRODUCT_SHIP: 'ORDER_PRODUCT_SHIP',
  ORDER_PRODUCT_RECEIVE: 'ORDER_PRODUCT_RECEIVE',
  ORDER_BATCH_VERIFY: 'ORDER_BATCH_VERIFY',
  ORDER_BATCH_REFUND: 'ORDER_BATCH_REFUND',
  ORDER_BATCH_REMARK: 'ORDER_BATCH_REMARK',
  ORDER_BATCH_STATUS_TRANSITION: 'ORDER_BATCH_STATUS_TRANSITION',
  MEMBER_LEVEL_UPDATE: 'MEMBER_LEVEL_UPDATE',
  MEMBER_MANUAL_LEVEL: 'MEMBER_MANUAL_LEVEL',
  MEMBER_POINT_ADJUST: 'MEMBER_POINT_ADJUST',
  MEMBER_UPGRADE_APPROVE: 'MEMBER_UPGRADE_APPROVE',
  MEMBER_UPGRADE_REJECT: 'MEMBER_UPGRADE_REJECT',
  STORE_PRODUCT_UPDATE_PRICE: 'STORE_PRODUCT_UPDATE_PRICE',
  STORE_PRODUCT_UPDATE_BASE: 'STORE_PRODUCT_UPDATE_BASE',
  STORE_PRODUCT_REMOVE: 'STORE_PRODUCT_REMOVE',
  STORE_PRODUCT_SUBMIT_AUDIT: 'STORE_PRODUCT_SUBMIT_AUDIT',
  STORE_PRODUCT_APPROVE_AUDIT: 'STORE_PRODUCT_APPROVE_AUDIT',
  STORE_PRODUCT_REJECT_AUDIT: 'STORE_PRODUCT_REJECT_AUDIT',
  STORE_PRODUCT_BATCH_APPROVE_AUDIT: 'STORE_PRODUCT_BATCH_APPROVE_AUDIT',
  STORE_PRODUCT_BATCH_UPSERT_PRICE_COMMISSION: 'STORE_PRODUCT_BATCH_UPSERT_PRICE_COMMISSION',
} as const;

export type BizOperationAction = (typeof BizOperationActions)[keyof typeof BizOperationActions];

export const BizOperationTargetTypes = {
  ORDER: 'ORDER',
  MEMBER: 'MEMBER',
  STORE_PRODUCT: 'STORE_PRODUCT',
} as const;
